import { getSupabaseConfig } from '../../core/database/supabase.client.js';
type FieldType='text'|'number'|'boolean'|'date';
export interface OrganizationField{key:string;label:string;type:FieldType;required?:boolean;reference?:string;}
export interface OrganizationCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:OrganizationField[];}
export const organizationCatalogs:OrganizationCatalog[]=[
 {slug:'fiscal-years',table:'fiscal_years',title:'Años fiscales',description:'Años fiscales',primaryKey:'fiscal_year_id',fields:[{key:'year_name',label:'Año fiscal',type:'text',required:true},{key:'start_date',label:'Fecha inicial',type:'date',required:true},{key:'end_date',label:'Fecha final',type:'date',required:true},{key:'is_closed',label:'Cerrado',type:'boolean'}]},
 {slug:'fiscal-calendars',table:'fiscal_calendars',title:'Calendarios fiscales',description:'Calendarios fiscales por región',primaryKey:'fiscal_calendar_id',fields:[{key:'calendar_name',label:'Calendario',type:'text',required:true},{key:'fiscal_year_id',label:'Año fiscal',type:'number',required:true,reference:'organization/fiscal-years'}]},
 {slug:'subsidiaries',table:'subsidiaries',title:'Subsidiarias',description:'Estructura jerárquica de empresas y subsidiarias',primaryKey:'subsidiary_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'legal_name',label:'Razón social',type:'text',required:true},{key:'parent_id',label:'Subsidiaria padre',type:'number',reference:'organization/subsidiaries'},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'currency_id',label:'Moneda',type:'number',required:true,reference:'core/currencies'},{key:'fiscal_calendar_id',label:'Calendario fiscal',type:'number',required:true,reference:'organization/fiscal-calendars'},{key:'tax_id',label:'Identificación fiscal',type:'text',required:true},{key:'is_elimination',label:'Es eliminación',type:'boolean'},{key:'is_active',label:'Activa',type:'boolean'}]},
 {slug:'branches',table:'branches',title:'Sucursales',description:'Sucursales de cada subsidiaria',primaryKey:'branch_id',fields:[{key:'branch_code',label:'Código',type:'text',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'address',label:'Dirección',type:'text'}]},
 {slug:'departments',table:'departments',title:'Departamentos',description:'Departamentos y segmentación analítica',primaryKey:'department_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'parent_id',label:'Departamento padre',type:'number',reference:'organization/departments'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactivo',type:'boolean'}]},
 {slug:'classes',table:'classes',title:'Clases',description:'Clases y líneas de negocio',primaryKey:'class_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'parent_id',label:'Clase padre',type:'number',reference:'organization/classes'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactiva',type:'boolean'}]},
 {slug:'cost-centers',table:'cost_centers',title:'Centros de costo',description:'Centros de costo',primaryKey:'cost_center_id',fields:[{key:'code',label:'Código',type:'text',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'parent_id',label:'Centro padre',type:'number',reference:'organization/cost-centers'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactivo',type:'boolean'}]},
 {slug:'locations',table:'locations',title:'Ubicaciones',description:'Ubicaciones y almacenes principales',primaryKey:'location_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'location_type',label:'Tipo de ubicación',type:'text',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'address',label:'Dirección',type:'text'}]}
];
export function getOrganizationCatalog(slug:string){const catalog=organizationCatalogs.find(item=>item.slug===slug);if(!catalog)throw new Error('El catálogo de Organización no existe.');return catalog;}
function sanitize(catalog:OrganizationCatalog,input:Record<string,unknown>){return Object.fromEntries(catalog.fields.map(field=>{const raw=input[field.key];if(field.required&&(raw===undefined||raw===null||String(raw).trim()===''))throw new Error(`${field.label} es obligatorio.`);if(field.type==='boolean')return[field.key,raw===true||raw==='true'];if(field.type==='number')return[field.key,raw===undefined||raw===null||raw===''?null:Number(raw)];return[field.key,raw===undefined||raw===null||String(raw).trim()===''?null:String(raw).trim()];}));}
async function request<T>(catalog:OrganizationCatalog,token:string,query='',init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${catalog.table}${query}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:token,'Content-Type':'application/json',...(init.headers??{})}});const payload:unknown=response.status===204?null:await response.json();if(!response.ok){const message=typeof payload==='object'&&payload!==null&&'message'in payload?String(payload.message):'No fue posible completar la operación.';throw new Error(message);}return payload as T;}
export const listOrganizationRows=(catalog:OrganizationCatalog,token:string)=>request<Record<string,unknown>[]>(catalog,token,`?select=*&order=${catalog.primaryKey}.asc`);
export async function createOrganizationRow(catalog:OrganizationCatalog,token:string,input:Record<string,unknown>){const rows=await request<Record<string,unknown>[]>(catalog,token,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(catalog,input))});return rows[0];}
export async function updateOrganizationRow(catalog:OrganizationCatalog,token:string,id:number,input:Record<string,unknown>){const rows=await request<Record<string,unknown>[]>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(catalog,input))});return rows[0];}
export const deleteOrganizationRow=(catalog:OrganizationCatalog,token:string,id:number)=>request<null>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'DELETE'});
