import { getSupabaseConfig } from '../../core/database/supabase.client.js';
type FieldType='text'|'number'|'boolean'|'date'|'multi-reference';
export interface OrganizationField{key:string;label:string;type:FieldType;required?:boolean;reference?:string;filterBy?:string;options?:string[];}
export interface OrganizationCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:OrganizationField[];}
export const organizationCatalogs:OrganizationCatalog[]=[
 {slug:'fiscal-years',table:'fiscal_years',title:'Años fiscales',description:'Años fiscales',primaryKey:'fiscal_year_id',fields:[{key:'year_name',label:'Año fiscal',type:'text',required:true},{key:'start_date',label:'Fecha inicial',type:'date',required:true},{key:'end_date',label:'Fecha final',type:'date',required:true},{key:'is_closed',label:'Cerrado',type:'boolean'}]},
 {slug:'fiscal-calendars',table:'fiscal_calendars',title:'Calendarios fiscales',description:'Calendarios fiscales por región',primaryKey:'fiscal_calendar_id',fields:[{key:'calendar_name',label:'Calendario',type:'text',required:true},{key:'fiscal_year_id',label:'Año fiscal',type:'number',required:true,reference:'organization/fiscal-years'}]},
 {slug:'subsidiaries',table:'subsidiaries',title:'Subsidiarias',description:'Estructura jerárquica de empresas y subsidiarias',primaryKey:'subsidiary_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'legal_name',label:'Razón social',type:'text',required:true},{key:'parent_id',label:'Subsidiaria padre',type:'number',reference:'organization/subsidiaries'},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'currency_id',label:'Moneda',type:'number',required:true,reference:'core/currencies'},{key:'fiscal_calendar_id',label:'Calendario fiscal',type:'number',required:true,reference:'organization/fiscal-calendars'},{key:'tax_id',label:'Identificación fiscal',type:'text',required:true},{key:'is_elimination',label:'Es eliminación',type:'boolean'},{key:'is_active',label:'Activa',type:'boolean'}]},
 {slug:'branches',table:'branches',title:'Sucursales',description:'Sucursales de cada subsidiaria',primaryKey:'branch_id',fields:[{key:'branch_code',label:'Código',type:'text',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'address',label:'Dirección',type:'text'}]},
 {slug:'departments',table:'departments',title:'Departamentos',description:'Departamentos y segmentación analítica',primaryKey:'department_id',fields:[{key:'name',label:'Nombre',type:'text',required:true},{key:'type',label:'Tipo',type:'text',required:true,options:['Cliente','Interno']},{key:'parent_id',label:'Departamento padre',type:'number',reference:'organization/departments'},{key:'subsidiary_ids',label:'Subsidiarias',type:'multi-reference',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactivo',type:'boolean'}]},
 {slug:'classes',table:'classes',title:'Clases',description:'Clases y líneas de negocio',primaryKey:'class_id',fields:[{key:'parent_id',label:'Clase padre',type:'number',reference:'organization/classes'},{key:'name',label:'Nombre',type:'text',required:true},{key:'description',label:'Descripción',type:'text'},{key:'subsidiary_ids',label:'Subsidiaria',type:'multi-reference',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactiva',type:'boolean'}]},
 {slug:'cost-centers',table:'cost_centers',title:'Centros de costo',description:'Centros de costo',primaryKey:'cost_center_id',fields:[{key:'code',label:'Código',type:'text',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'parent_id',label:'Centro padre',type:'number',reference:'organization/cost-centers'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'is_inactive',label:'Inactivo',type:'boolean'}]},
 {slug:'locations',table:'locations',title:'Ubicaciones',description:'Jerarquía de ubicaciones por país y subsidiarias',primaryKey:'location_id',fields:[{key:'parent_id',label:'Ubicación Padre',type:'number',reference:'organization/locations'},{key:'name',label:'Nombre',type:'text',required:true},{key:'country_id',label:'País',type:'number',reference:'core/countries'},{key:'subsidiary_ids',label:'Subsidiarias',type:'multi-reference',reference:'organization/subsidiaries',filterBy:'country_id'}]}
];
export function getOrganizationCatalog(slug:string){const catalog=organizationCatalogs.find(item=>item.slug===slug);if(!catalog)throw new Error('El catálogo de Organización no existe.');return catalog;}
function sanitize(catalog:OrganizationCatalog,input:Record<string,unknown>){return Object.fromEntries(catalog.fields.filter(field=>field.type!=='multi-reference').map(field=>{const raw=input[field.key];if(field.required&&(raw===undefined||raw===null||String(raw).trim()===''))throw new Error(`${field.label} es obligatorio.`);if(field.options&&!field.options.includes(String(raw)))throw new Error(`${field.label} no es válido.`);if(field.type==='boolean')return[field.key,raw===true||raw==='true'];if(field.type==='number')return[field.key,raw===undefined||raw===null||raw===''?null:Number(raw)];return[field.key,raw===undefined||raw===null||String(raw).trim()===''?null:String(raw).trim()];}));}
async function request<T>(catalog:OrganizationCatalog,token:string,query='',init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${catalog.table}${query}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:token,'Content-Type':'application/json',...(init.headers??{})}});const payload:unknown=response.status===204?null:await response.json();if(!response.ok){const message=typeof payload==='object'&&payload!==null&&'message'in payload?String(payload.message):'No fue posible completar la operación.';throw new Error(message);}return payload as T;}
function multiRelation(catalog:OrganizationCatalog){if(catalog.slug==='departments')return{table:'department_subsidiaries',owner:'department_id'};if(catalog.slug==='classes')return{table:'class_subsidiaries',owner:'class_id'};if(catalog.slug==='locations')return{table:'location_subsidiaries',owner:'location_id'};return null;}
async function relationRequest<T>(path:string,token:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:token,'Content-Type':'application/json',...(init.headers??{})}});const raw=response.status===204?'':await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok){const message=typeof payload==='object'&&payload!==null&&'message'in payload?String(payload.message):'No fue posible asignar las subsidiarias.';throw new Error(message);}return payload as T;}
function subsidiaryIds(input:Record<string,unknown>,required=true){const value=input.subsidiary_ids;const ids=Array.isArray(value)?[...new Set(value.map(Number).filter(Number.isFinite))]:[];if(required&&!ids.length)throw new Error('Debe seleccionar al menos una subsidiaria.');return ids;}
async function syncSubsidiaries(catalog:OrganizationCatalog,token:string,id:number,input:Record<string,unknown>){const relation=multiRelation(catalog);if(!relation)return;const ids=subsidiaryIds(input,catalog.slug!=='locations');await relationRequest(`${relation.table}?${relation.owner}=eq.${id}`,token,{method:'DELETE'});if(ids.length)await relationRequest(relation.table,token,{method:'POST',body:JSON.stringify(ids.map(subsidiary_id=>({[relation.owner]:id,subsidiary_id})))});}
export async function listOrganizationRows(catalog:OrganizationCatalog,token:string){const rows=await request<Record<string,unknown>[]>(catalog,token,`?select=*&order=${catalog.primaryKey}.asc`);const relation=multiRelation(catalog);if(!relation)return rows;const links=await relationRequest<Record<string,number>[]>(`${relation.table}?select=${relation.owner},subsidiary_id`,token);return rows.map(row=>({...row,subsidiary_ids:links.filter(link=>Number(link[relation.owner])===Number(row[catalog.primaryKey])).map(link=>link.subsidiary_id)}));}
export async function createOrganizationRow(catalog:OrganizationCatalog,token:string,input:Record<string,unknown>){const relation=multiRelation(catalog);const values=sanitize(catalog,input);if(relation){const ids=subsidiaryIds(input,catalog.slug!=='locations');values.subsidiary_id=ids[0]??null;}const rows=await request<Record<string,unknown>[]>(catalog,token,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(values)});await syncSubsidiaries(catalog,token,Number(rows[0][catalog.primaryKey]),input);return rows[0];}
export async function updateOrganizationRow(catalog:OrganizationCatalog,token:string,id:number,input:Record<string,unknown>){const relation=multiRelation(catalog);const values=sanitize(catalog,input);if(relation){const ids=subsidiaryIds(input,catalog.slug!=='locations');values.subsidiary_id=ids[0]??null;}const rows=await request<Record<string,unknown>[]>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(values)});await syncSubsidiaries(catalog,token,id,input);return rows[0];}
export const deleteOrganizationRow=(catalog:OrganizationCatalog,token:string,id:number)=>request<null>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'DELETE'});
