import { getSupabaseConfig } from '../../core/database/supabase.client.js';

type FieldType = 'text'|'number'|'boolean'|'password'|'datetime-local';
export interface SecurityField { key:string; label:string; type:FieldType; required?:boolean; reference?:string; }
export interface SecurityCatalog { slug:string; table:string; title:string; description:string; primaryKey:string; fields:SecurityField[]; }
export const securityCatalogs: SecurityCatalog[] = [
  {slug:'users',table:'users',title:'Usuarios',description:'Usuarios del sistema ERP',primaryKey:'user_id',fields:[{key:'email',label:'Correo',type:'text',required:true},{key:'password_hash',label:'Hash de contraseña',type:'password',required:true},{key:'first_name',label:'Nombre',type:'text',required:true},{key:'last_name',label:'Apellidos',type:'text',required:true},{key:'timezone_id',label:'Zona horaria',type:'number',reference:'core/timezones'},{key:'is_active',label:'Activo',type:'boolean'}]},
  {slug:'roles',table:'roles',title:'Roles',description:'Roles de seguridad y permisos',primaryKey:'role_id',fields:[{key:'role_name',label:'Rol',type:'text',required:true},{key:'description',label:'Descripción',type:'text'},{key:'is_system_role',label:'Rol del sistema',type:'boolean'}]},
  {slug:'permissions',table:'permissions',title:'Permisos',description:'Permisos individuales por módulo',primaryKey:'permission_id',fields:[{key:'code',label:'Código',type:'text',required:true},{key:'module',label:'Módulo',type:'text',required:true},{key:'description',label:'Descripción',type:'text'}]},
  {slug:'role-permissions',table:'role_permissions',title:'Permisos por rol',description:'Matriz de permisos por rol',primaryKey:'id',fields:[{key:'role_id',label:'Rol',type:'number',required:true,reference:'security/roles'},{key:'permission_id',label:'Permiso',type:'number',required:true,reference:'security/permissions'}]},
  {slug:'user-roles',table:'user_roles',title:'Roles por usuario',description:'Asignación de roles a usuarios',primaryKey:'id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'role_id',label:'Rol',type:'number',required:true,reference:'security/roles'}]},
  {slug:'user-subsidiaries',table:'user_subsidiaries',title:'Empresas por usuario',description:'Empresas autorizadas para cada usuario',primaryKey:'id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'subsidiary_id',label:'Empresa',type:'number',required:true,reference:'organization/subsidiaries'}]},
  {slug:'sessions',table:'sessions',title:'Sesiones',description:'Sesiones de usuario activas',primaryKey:'session_id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'session_token',label:'Token de sesión',type:'password',required:true},{key:'ip_address',label:'Dirección IP',type:'text'},{key:'expires_at',label:'Expira',type:'datetime-local',required:true},{key:'created_at',label:'Creada',type:'datetime-local'}]},
  {slug:'devices',table:'devices',title:'Dispositivos',description:'Dispositivos registrados',primaryKey:'device_id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'device_name',label:'Dispositivo',type:'text',required:true},{key:'device_token',label:'Token',type:'password',required:true},{key:'last_used',label:'Último uso',type:'datetime-local'}]},
  {slug:'login-history',table:'login_history',title:'Historial de accesos',description:'Historial de inicios de sesión',primaryKey:'history_id',fields:[{key:'user_id',label:'Usuario',type:'number',reference:'security/users'},{key:'login_time',label:'Fecha de acceso',type:'datetime-local',required:true},{key:'ip_address',label:'Dirección IP',type:'text'},{key:'status',label:'Estado',type:'text',required:true}]},
  {slug:'password-history',table:'password_history',title:'Historial de contraseñas',description:'Historial de contraseñas',primaryKey:'history_id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'password_hash',label:'Hash de contraseña',type:'password',required:true},{key:'created_at',label:'Fecha de creación',type:'datetime-local',required:true}]},
  {slug:'api-keys',table:'api_keys',title:'Claves API',description:'Claves de API',primaryKey:'api_key_id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'key_hash',label:'Hash de clave',type:'password',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'is_active',label:'Activa',type:'boolean'},{key:'expires_at',label:'Expira',type:'datetime-local'}]},
  {slug:'oauth-clients',table:'oauth_clients',title:'Clientes OAuth',description:'Clientes OAuth',primaryKey:'client_id',fields:[{key:'client_secret',label:'Secreto del cliente',type:'password',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'redirect_uri',label:'URI de redirección',type:'text',required:true},{key:'is_active',label:'Activo',type:'boolean'}]},
  {slug:'menus',table:'menus',title:'Menús',description:'Estructura de menús del ERP',primaryKey:'menu_id',fields:[{key:'title',label:'Título',type:'text',required:true},{key:'icon',label:'Icono',type:'text'},{key:'route',label:'Ruta',type:'text'},{key:'parent_id',label:'Menú padre',type:'number',reference:'security/menus'},{key:'sort_order',label:'Orden',type:'number',required:true}]},
  {slug:'menu-permissions',table:'menu_permissions',title:'Permisos de menú',description:'Permisos sobre menús',primaryKey:'id',fields:[{key:'menu_id',label:'Menú',type:'number',required:true,reference:'security/menus'},{key:'role_id',label:'Rol',type:'number',required:true,reference:'security/roles'}]}
];
export function getSecurityCatalog(slug:string){const catalog=securityCatalogs.find(item=>item.slug===slug);if(!catalog)throw new Error('El catálogo de seguridad no existe.');return catalog;}
function sanitize(catalog:SecurityCatalog,input:Record<string,unknown>){return Object.fromEntries(catalog.fields.map(field=>{const raw=input[field.key];if(field.required&&(raw===undefined||raw===null||String(raw).trim()===''))throw new Error(`${field.label} es obligatorio.`);if(field.type==='boolean')return[field.key,raw===true||raw==='true'];if(field.type==='number')return[field.key,raw===undefined||raw===null||raw===''?null:Number(raw)];return[field.key,raw===undefined||raw===null||String(raw).trim()===''?null:String(raw).trim()];}));}
async function request<T>(catalog:SecurityCatalog,token:string,query='',init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${catalog.table}${query}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:token,'Content-Type':'application/json',...(init.headers??{})}});const payload:unknown=response.status===204?null:await response.json();if(!response.ok){const message=typeof payload==='object'&&payload!==null&&'message'in payload?String(payload.message):'No fue posible completar la operación.';throw new Error(message);}return payload as T;}
export const listSecurityRows=(catalog:SecurityCatalog,token:string)=>request<Record<string,unknown>[]>(catalog,token,`?select=*${catalog.slug==='sessions'?`&expires_at=gt.${encodeURIComponent(new Date().toISOString())}`:''}&order=${catalog.primaryKey}.asc`);
export async function createSecurityRow(catalog:SecurityCatalog,token:string,input:Record<string,unknown>){if(catalog.slug==='sessions')throw new Error('Las sesiones se crean al iniciar sesión.');const rows=await request<Record<string,unknown>[]>(catalog,token,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(catalog,input))});return rows[0];}
export async function updateSecurityRow(catalog:SecurityCatalog,token:string,id:number,input:Record<string,unknown>){if(catalog.slug==='sessions')throw new Error('Las sesiones no se editan manualmente.');const rows=await request<Record<string,unknown>[]>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(catalog,input))});return rows[0];}
export const deleteSecurityRow=(catalog:SecurityCatalog,token:string,id:number)=>request<null>(catalog,token,`?${catalog.primaryKey}=eq.${id}`,{method:'DELETE'});
