import { getSupabaseConfig } from '../../../core/database/supabase.client.js';
const TRM_API='https://www.datos.gov.co/resource/32sa-8pi3.json';
type CurrencyRow={currency_id:number;currency_code:string};type TrmRow={valor:string;unidad:string;vigenciadesde:string;vigenciahasta:string};
function effectiveDate(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');return date.toISOString().slice(0,10);}
/** Consulta la TRM oficial suministrada por la Superintendencia Financiera de Colombia. */
export async function obtenerTipoDeCambioCO(monedaOrigen='USD',monedaDestino='COP',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase(),date=effectiveDate(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date,tipoCambio:1,fuente:'Superintendencia Financiera de Colombia'};if(!((from==='USD'&&to==='COP')||(from==='COP'&&to==='USD')))throw new Error('Por ahora la consulta de Colombia admite únicamente USD y COP.');const where=`vigenciadesde <= '${date}T23:59:59' AND vigenciahasta >= '${date}T00:00:00'`;const url=new URL(TRM_API);url.searchParams.set('$select','valor,unidad,vigenciadesde,vigenciahasta');url.searchParams.set('$where',where);url.searchParams.set('$order','vigenciadesde DESC');url.searchParams.set('$limit','1');const response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Nexo ERP/1.0'}}),raw=await response.text();if(!response.ok)throw new Error(`El servicio oficial de TRM respondió con estado ${response.status}.`);const row=(JSON.parse(raw)as TrmRow[])[0],trm=Number(row?.valor);if(!Number.isFinite(trm)||trm<=0)throw new Error('La Superintendencia Financiera no devolvió una TRM válida para la fecha solicitada.');return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date,tipoCambio:from==='USD'?trm:1/trm,trm,vigenciaDesde:row.vigenciadesde,vigenciaHasta:row.vigenciahasta,fuente:'Superintendencia Financiera de Colombia'};}
function claims(auth:string){const part=auth.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8'))as Record<string,unknown>;}
async function rest<T>(path:string,auth:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:auth,'Content-Type':'application/json',...(init.headers??{})}}),raw=await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(auth:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,auth);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(auth:string){const session=String(claims(auth).session_id??claims(auth).sub??''),selected=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(session)}&limit=1`,auth);if(!selected[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${selected[0].subsidiary_id}&limit=1`,auth),currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0]?.currency_id??-1}&limit=1`,auth);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}
async function save(auth:string,key:string|undefined,origin:CurrencyRow,destination:CurrencyRow,rate:Awaited<ReturnType<typeof obtenerTipoDeCambioCO>>){const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',auth,{method:'POST',headers:{...(key?{apikey:key}:{}),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
export async function consultarYGuardarTipoDeCambioCO(auth:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(auth,(input.monedaOrigen||'USD').trim().toUpperCase()),destination=input.monedaDestino?await currency(auth,input.monedaDestino.trim().toUpperCase()):await localCurrency(auth),rate=await obtenerTipoDeCambioCO(origin.currency_code,destination.currency_code,input.fechaEfectiva);return origin.currency_id===destination.currency_id?{...rate,guardado:false}:save(auth,undefined,origin,destination,rate);}
export async function consultarYGuardarTipoDeCambioCOAutomatico(fechaEfectiva?:Date|string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const auth=`Bearer ${key}`,[origin,destination]=await Promise.all([currency(auth,'USD'),currency(auth,'COP')]);return save(auth,key,origin,destination,await obtenerTipoDeCambioCO('USD','COP',fechaEfectiva));}
