import { getSupabaseConfig } from '../../../core/database/supabase.client.js';

const BCCR_SERVICE='https://gee.bccr.fi.cr/Indicadores/Suscripciones/WS/wsindicadoreseconomicos.asmx/ObtenerIndicadoresEconomicosXML';
const BUY_INDICATOR='317';
const SELL_INDICATOR='318';
type CurrencyRow={currency_id:number;currency_code:string};

function dateParts(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');const iso=date.toISOString().slice(0,10);const[year,month,day]=iso.split('-');return{iso,bccr:`${day}/${month}/${year}`};}
function xmlValue(xml:string){const match=xml.match(/<NUM_VALOR>([^<]+)<\/NUM_VALOR>/i);const value=Number(match?.[1]?.replace(',','.'));if(!Number.isFinite(value)||value<=0)throw new Error('El BCCR no devolvió una tasa válida para la fecha solicitada.');return value;}
async function indicator(code:string,date:string){const email=process.env.BCCR_EMAIL?.trim();const token=process.env.BCCR_TOKEN?.trim();if(!email||!token)throw new Error('Debe configurar BCCR_EMAIL y BCCR_TOKEN con la suscripción al servicio web del BCCR.');const url=new URL(BCCR_SERVICE);for(const[key,value]of Object.entries({Indicador:code,FechaInicio:date,FechaFinal:date,Nombre:'Nexo ERP',SubNiveles:'N',CorreoElectronico:email,Token:token}))url.searchParams.set(key,value);for(let attempt=1;attempt<=3;attempt++){const response=await fetch(url,{headers:{Accept:'application/xml','User-Agent':'Nexo ERP/1.0'}});const xml=await response.text();if(response.ok)return xmlValue(xml);if(response.status!==503||attempt===3)throw new Error(`El servicio del BCCR respondió con estado ${response.status} después de ${attempt} intento(s).`);await new Promise(resolve=>setTimeout(resolve,attempt*1500));}throw new Error('No fue posible consultar el indicador del BCCR.');}

/** Consulta la tasa oficial de venta publicada por el Banco Central de Costa Rica. */
export async function obtenerTipoDeCambioCR(monedaOrigen='USD',monedaDestino='CRC',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase();const date=dateParts(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date.iso,tipoCambio:1,fuente:'Banco Central de Costa Rica'};if(!((from==='USD'&&to==='CRC')||(from==='CRC'&&to==='USD')))throw new Error('Por ahora la consulta de Costa Rica admite únicamente USD y CRC.');const[buy,sell]=await Promise.all([indicator(BUY_INDICATOR,date.bccr),indicator(SELL_INDICATOR,date.bccr)]);return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date.iso,tipoCambio:from==='USD'?sell:1/sell,tasaCompra:buy,tasaVenta:sell,fuente:'Banco Central de Costa Rica'};}

function claims(authorization:string){const part=authorization.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8')) as Record<string,unknown>;}
async function rest<T>(path:string,authorization:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:authorization,'Content-Type':'application/json',...(init.headers??{})}});const raw=await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(authorization:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,authorization);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(authorization:string){const sessionId=String(claims(authorization).session_id??claims(authorization).sub??'');const sessions=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(sessionId)}&limit=1`,authorization);if(!sessions[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${sessions[0].subsidiary_id}&limit=1`,authorization);if(!subsidiaries[0])throw new Error('No fue posible determinar la moneda local de la empresa activa.');const currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0].currency_id}&limit=1`,authorization);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}

export async function consultarYGuardarTipoDeCambioCR(authorization:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(authorization,(input.monedaOrigen||'USD').trim().toUpperCase());const destination=input.monedaDestino?await currency(authorization,input.monedaDestino.trim().toUpperCase()):await localCurrency(authorization);const rate=await obtenerTipoDeCambioCR(origin.currency_code,destination.currency_code,input.fechaEfectiva);if(origin.currency_id===destination.currency_id)return{...rate,guardado:false};const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',authorization,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}

export async function consultarYGuardarTipoDeCambioCRAutomatico(fechaEfectiva?:Date|string){const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!serviceKey)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const authorization=`Bearer ${serviceKey}`;const[origin,destination]=await Promise.all([currency(authorization,'USD'),currency(authorization,'CRC')]);const rate=await obtenerTipoDeCambioCR('USD','CRC',fechaEfectiva);const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',authorization,{method:'POST',headers:{apikey:serviceKey,Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
