import { getSupabaseConfig } from '../../../core/database/supabase.client.js';

const BANGUAT_SERVICE='https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx';
type CurrencyRow={currency_id:number;currency_code:string};
function dateParts(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');const iso=date.toISOString().slice(0,10);const[year,month,day]=iso.split('-');return{iso,banguat:`${day}/${month}/${year}`};}
function tag(xml:string,name:string){return xml.match(new RegExp(`<${name}>([^<]+)</${name}>`,'i'))?.[1];}

/** Consulta el tipo de cambio de referencia publicado por el Banco de Guatemala. */
export async function obtenerTipoDeCambioGT(monedaOrigen='USD',monedaDestino='GTQ',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase();const date=dateParts(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date.iso,tipoCambio:1,fuente:'Banco de Guatemala'};if(!((from==='USD'&&to==='GTQ')||(from==='GTQ'&&to==='USD')))throw new Error('Por ahora la consulta de Guatemala admite únicamente USD y GTQ.');const body=`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><TipoCambioRango xmlns="http://www.banguat.gob.gt/variables/ws/"><fechainit>${date.banguat}</fechainit><fechafin>${date.banguat}</fechafin></TipoCambioRango></soap:Body></soap:Envelope>`;const response=await fetch(BANGUAT_SERVICE,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8',SOAPAction:'"http://www.banguat.gob.gt/variables/ws/TipoCambioRango"','User-Agent':'Nexo ERP/1.0'},body});const xml=await response.text();if(!response.ok)throw new Error(`El servicio del Banco de Guatemala respondió con estado ${response.status}.`);const buy=Number(tag(xml,'compra')),sell=Number(tag(xml,'venta'));if(!Number.isFinite(sell)||sell<=0)throw new Error('El Banco de Guatemala no devolvió una tasa de venta para la fecha solicitada.');return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:date.iso,tipoCambio:from==='USD'?sell:1/sell,tasaCompra:buy,tasaVenta:sell,fuente:'Banco de Guatemala'};}

function claims(authorization:string){const part=authorization.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8')) as Record<string,unknown>;}
async function rest<T>(path:string,authorization:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:authorization,'Content-Type':'application/json',...(init.headers??{})}});const raw=await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(authorization:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,authorization);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(authorization:string){const sessionId=String(claims(authorization).session_id??claims(authorization).sub??'');const sessions=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(sessionId)}&limit=1`,authorization);if(!sessions[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${sessions[0].subsidiary_id}&limit=1`,authorization);if(!subsidiaries[0])throw new Error('No fue posible determinar la moneda local de la empresa activa.');const currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0].currency_id}&limit=1`,authorization);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}
async function save(authorization:string,serviceKey:string|undefined,origin:CurrencyRow,destination:CurrencyRow,rate:Awaited<ReturnType<typeof obtenerTipoDeCambioGT>>){const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',authorization,{method:'POST',headers:{...(serviceKey?{apikey:serviceKey}:{}),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
export async function consultarYGuardarTipoDeCambioGT(authorization:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(authorization,(input.monedaOrigen||'USD').trim().toUpperCase()),destination=input.monedaDestino?await currency(authorization,input.monedaDestino.trim().toUpperCase()):await localCurrency(authorization);const rate=await obtenerTipoDeCambioGT(origin.currency_code,destination.currency_code,input.fechaEfectiva);return origin.currency_id===destination.currency_id?{...rate,guardado:false}:save(authorization,undefined,origin,destination,rate);}
export async function consultarYGuardarTipoDeCambioGTAutomatico(fechaEfectiva?:Date|string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const authorization=`Bearer ${key}`;const[origin,destination]=await Promise.all([currency(authorization,'USD'),currency(authorization,'GTQ')]);return save(authorization,key,origin,destination,await obtenerTipoDeCambioGT('USD','GTQ',fechaEfectiva));}
