import { getSupabaseConfig } from '../../../core/database/supabase.client.js';
const BOJ_PAGE='https://boj.org.jm/market/foreign-exchange/search-fx-rates-volumes/';const BOJ_DATA='https://boj.org.jm/wp-admin/admin-ajax.php?action=get_wdtable&table_id=83';
const COLUMNS=['seltradedate','Applicable','weighbuyaverusd','volumebuyusd','usdvolumebuyusd','maxbuyusd','minbuyusd','buy10usd','weighsellaverusd','volumesellusd','usdvolumesellusd','maxsellusd','minsellusd','sell10usd'];
type CurrencyRow={currency_id:number;currency_code:string};type BojData={data:string[][]};
function effectiveDate(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');return date.toISOString().slice(0,10);}
function tradeDate(iso:string){const[y,m,d]=iso.split('-').map(Number);return`${String(d).padStart(2,'0')} ${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m-1]} ${y}`;}
function previous(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days);return date.toISOString().slice(0,10);}
function cookies(headers:Headers){const map=new Map<string,string>();for(const item of headers.getSetCookie?.()??[]){const pair=item.split(';')[0],index=pair.indexOf('=');if(index>0&&pair.slice(index+1))map.set(pair.slice(0,index),pair.slice(index+1));}return[...map].map(([name,value])=>`${name}=${value}`).join('; ');}
function requestBody(nonce:string,date:string){const form=new URLSearchParams({draw:'1',start:'0',length:'10',wdtNonce:nonce,currentTime:'',wpdbPlaceholder:'',showAllRows:'0','order[0][column]':'0','order[0][dir]':'desc','search[value]':'','search[regex]':'false'});COLUMNS.forEach((name,index)=>{form.set(`columns[${index}][data]`,String(index));form.set(`columns[${index}][name]`,name);form.set(`columns[${index}][searchable]`,'true');form.set(`columns[${index}][orderable]`,'true');form.set(`columns[${index}][search][value]`,index===0?date:'');form.set(`columns[${index}][search][regex]`,'false');});return form;}
/** Consulta la tasa promedio ponderada oficial publicada por el Bank of Jamaica. */
export async function obtenerTipoDeCambioJM(monedaOrigen='USD',monedaDestino='JMD',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase(),effective=effectiveDate(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,tipoCambio:1,fuente:'Bank of Jamaica'};if(!((from==='USD'&&to==='JMD')||(from==='JMD'&&to==='USD')))throw new Error('Por ahora la consulta de Jamaica admite únicamente USD y JMD.');const page=await fetch(BOJ_PAGE,{headers:{'User-Agent':'Nexo ERP/1.0'}}),html=await page.text();if(!page.ok)throw new Error(`El Bank of Jamaica respondió con estado ${page.status}.`);const nonce=html.match(/id="wdtNonceFrontendServerSide_83"[^>]*value="([^"]+)"/)?.[1];if(!nonce)throw new Error('No fue posible iniciar la consulta histórica del Bank of Jamaica.');const cookie=cookies(page.headers);for(let days=0;days<=7;days++){const sourceDate=previous(effective,days),label=tradeDate(sourceDate);const response=await fetch(BOJ_DATA,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8','X-Requested-With':'XMLHttpRequest',Referer:BOJ_PAGE,Cookie:cookie,'User-Agent':'Nexo ERP/1.0'},body:requestBody(nonce,label)}),raw=await response.text();if(!response.ok)throw new Error(`El Bank of Jamaica respondió con estado ${response.status}.`);const row=((JSON.parse(raw)as BojData).data??[]).find(item=>item[0]===label);if(row){const buy=Number(row[2]?.replaceAll(',','')),sell=Number(row[8]?.replaceAll(',',''));if(Number.isFinite(sell)&&sell>0)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,fechaFuente:sourceDate,tipoCambio:from==='USD'?sell:1/sell,tasaCompra:buy,tasaVenta:sell,fuente:'Bank of Jamaica'};}}throw new Error('El Bank of Jamaica no devolvió una tasa de venta válida para la fecha solicitada ni los 7 días anteriores.');}
function claims(auth:string){const part=auth.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8'))as Record<string,unknown>;}
async function rest<T>(path:string,auth:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:auth,'Content-Type':'application/json',...(init.headers??{})}}),raw=await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(auth:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,auth);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(auth:string){const session=String(claims(auth).session_id??claims(auth).sub??''),selected=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(session)}&limit=1`,auth);if(!selected[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${selected[0].subsidiary_id}&limit=1`,auth),currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0]?.currency_id??-1}&limit=1`,auth);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}
async function save(auth:string,key:string|undefined,origin:CurrencyRow,destination:CurrencyRow,rate:Awaited<ReturnType<typeof obtenerTipoDeCambioJM>>){const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',auth,{method:'POST',headers:{...(key?{apikey:key}:{}),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
export async function consultarYGuardarTipoDeCambioJM(auth:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(auth,(input.monedaOrigen||'USD').trim().toUpperCase()),destination=input.monedaDestino?await currency(auth,input.monedaDestino.trim().toUpperCase()):await localCurrency(auth),rate=await obtenerTipoDeCambioJM(origin.currency_code,destination.currency_code,input.fechaEfectiva);return origin.currency_id===destination.currency_id?{...rate,guardado:false}:save(auth,undefined,origin,destination,rate);}
export async function consultarYGuardarTipoDeCambioJMAutomatico(fechaEfectiva?:Date|string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const auth=`Bearer ${key}`,[origin,destination]=await Promise.all([currency(auth,'USD'),currency(auth,'JMD')]);return save(auth,key,origin,destination,await obtenerTipoDeCambioJM('USD','JMD',fechaEfectiva));}
