import { getSupabaseConfig } from '../../../core/database/supabase.client.js';
import { request as httpsRequest } from 'node:https';
const BCN_SERVICE='https://servicios.bcn.gob.ni/Tc_Servicio/ServicioTC.asmx';
type CurrencyRow={currency_id:number;currency_code:string};
function effectiveDate(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');return date.toISOString().slice(0,10);}
function previous(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days);return date.toISOString().slice(0,10);}
function result(xml:string){return Number(xml.match(/<RecuperaTC_DiaResult>([^<]+)<\/RecuperaTC_DiaResult>/i)?.[1]);}
function postSoap(body:string){return new Promise<string>((resolve,reject)=>{const request=httpsRequest(BCN_SERVICE,{method:'POST',minVersion:'TLSv1',ciphers:'DEFAULT@SECLEVEL=0',headers:{'Content-Type':'text/xml; charset=utf-8',SOAPAction:'"http://servicios.bcn.gob.ni/RecuperaTC_Dia"','User-Agent':'Nexo ERP/1.0','Content-Length':Buffer.byteLength(body)}},response=>{let xml='';response.setEncoding('utf8');response.on('data',chunk=>xml+=chunk);response.on('end',()=>response.statusCode&&response.statusCode>=200&&response.statusCode<300?resolve(xml):reject(new Error(`El servicio del BCN respondió con estado ${response.statusCode??0}.`)));});request.setTimeout(15000,()=>request.destroy(new Error('El servicio del BCN excedió el tiempo de espera.')));request.on('error',reject);request.end(body);});}
async function officialRate(iso:string){const[year,month,day]=iso.split('-').map(Number);const body=`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><RecuperaTC_Dia xmlns="http://servicios.bcn.gob.ni/"><Ano>${year}</Ano><Mes>${month}</Mes><Dia>${day}</Dia></RecuperaTC_Dia></soap:Body></soap:Envelope>`;return result(await postSoap(body));}
/** Consulta el tipo de cambio oficial NIO por USD publicado por el BCN. */
export async function obtenerTipoDeCambioNI(monedaOrigen='USD',monedaDestino='NIO',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase(),effective=effectiveDate(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,tipoCambio:1,fuente:'Banco Central de Nicaragua'};if(!((from==='USD'&&to==='NIO')||(from==='NIO'&&to==='USD')))throw new Error('Por ahora la consulta de Nicaragua admite únicamente USD y NIO.');for(let days=0;days<=7;days++){const sourceDate=previous(effective,days),rate=await officialRate(sourceDate);if(Number.isFinite(rate)&&rate>0)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,fechaFuente:sourceDate,tipoCambio:from==='USD'?rate:1/rate,tasaVenta:rate,serie:'Tipo de cambio oficial NIO por USD',fuente:'Banco Central de Nicaragua'};}throw new Error('El BCN no devolvió una tasa oficial válida para la fecha solicitada ni los 7 días anteriores.');}
function claims(auth:string){const part=auth.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8'))as Record<string,unknown>;}
async function rest<T>(path:string,auth:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:auth,'Content-Type':'application/json',...(init.headers??{})}}),raw=await response.text(),payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(auth:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,auth);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(auth:string){const tokenClaims=claims(auth),session=String(tokenClaims.session_id??tokenClaims.sub??''),selected=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(session)}&limit=1`,auth);if(!selected[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${selected[0].subsidiary_id}&limit=1`,auth),currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0]?.currency_id??-1}&limit=1`,auth);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}
async function save(auth:string,key:string|undefined,origin:CurrencyRow,destination:CurrencyRow,rate:Awaited<ReturnType<typeof obtenerTipoDeCambioNI>>){const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',auth,{method:'POST',headers:{...(key?{apikey:key}:{}),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
export async function consultarYGuardarTipoDeCambioNI(auth:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(auth,(input.monedaOrigen||'USD').trim().toUpperCase()),destination=input.monedaDestino?await currency(auth,input.monedaDestino.trim().toUpperCase()):await localCurrency(auth),rate=await obtenerTipoDeCambioNI(origin.currency_code,destination.currency_code,input.fechaEfectiva);return origin.currency_id===destination.currency_id?{...rate,guardado:false}:save(auth,undefined,origin,destination,rate);}
export async function consultarYGuardarTipoDeCambioNIAutomatico(fechaEfectiva?:Date|string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const auth=`Bearer ${key}`,[origin,destination]=await Promise.all([currency(auth,'USD'),currency(auth,'NIO')]);return save(auth,key,origin,destination,await obtenerTipoDeCambioNI('USD','NIO',fechaEfectiva));}
