import { getSupabaseConfig } from '../../../core/database/supabase.client.js';
const SBS_SERIES_API='https://estadisticas.bcrp.gob.pe/estadisticas/series/api/PD04639PD-PD04640PD/json';
type CurrencyRow={currency_id:number;currency_code:string};type SeriesResponse={periods?:Array<{name:string;values:string[]}>};
const MONTHS:Record<string,string>={Ene:'01',Feb:'02',Mar:'03',Abr:'04',May:'05',Jun:'06',Jul:'07',Ago:'08',Sep:'09',Oct:'10',Nov:'11',Dic:'12'};
function effectiveDate(value?:Date|string){const date=value instanceof Date?value:new Date(value??Date.now());if(Number.isNaN(date.getTime()))throw new Error('La fecha efectiva no es válida.');return date.toISOString().slice(0,10);}
function previous(iso:string,days:number){const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-days);return date.toISOString().slice(0,10);}
function periodDate(name:string){const[day,month,year]=name.split('.');return month&&MONTHS[month]?`20${year}-${MONTHS[month]}-${day.padStart(2,'0')}`:'';}
async function latestSbsRate(effective:string){const start=previous(effective,7),url=`${SBS_SERIES_API}/${start}/${effective}/esp`,response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Mozilla/5.0 (compatible; Nexo ERP/1.0; +https://estadisticas.bcrp.gob.pe/)'}}),raw=await response.text();if(!response.ok)throw new Error(`El servicio de series SBS respondió con estado ${response.status}.`);let payload:SeriesResponse;try{payload=JSON.parse(raw)as SeriesResponse;}catch{throw new Error('El servicio de series SBS no devolvió una respuesta JSON válida.');}const valid=(payload.periods??[]).map(period=>({fecha:periodDate(period.name),buy:Number(period.values[0]),sell:Number(period.values[1])})).filter(row=>row.fecha&&Number.isFinite(row.sell)&&row.sell>0);return valid.at(-1);}
/** Consulta el tipo de cambio promedio ponderado de compra y venta publicado por la SBS. */
export async function obtenerTipoDeCambioPE(monedaOrigen='USD',monedaDestino='PEN',fechaEfectiva?:Date|string){const from=monedaOrigen.trim().toUpperCase(),to=monedaDestino.trim().toUpperCase(),effective=effectiveDate(fechaEfectiva);if(from===to)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,tipoCambio:1,fuente:'Superintendencia de Banca, Seguros y AFP del Perú'};if(!((from==='USD'&&to==='PEN')||(from==='PEN'&&to==='USD')))throw new Error('Por ahora la consulta de Perú admite únicamente USD y PEN.');const rate=await latestSbsRate(effective);if(rate)return{monedaOrigen:from,monedaDestino:to,fechaEfectiva:effective,fechaFuente:rate.fecha,tipoCambio:from==='USD'?rate.sell:1/rate.sell,tasaCompra:rate.buy,tasaVenta:rate.sell,serie:'TC Sistema bancario SBS (S/ por US$) - Venta',fuente:'Superintendencia de Banca, Seguros y AFP del Perú'};throw new Error('La SBS no devolvió una tasa de venta válida para la fecha solicitada ni los 7 días anteriores.');}
function claims(auth:string){const part=auth.replace(/^Bearer\s+/,'').split('.')[1];if(!part)throw new Error('La sesión no es válida.');return JSON.parse(Buffer.from(part,'base64url').toString('utf8'))as Record<string,unknown>;}
async function rest<T>(path:string,auth:string,init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${path}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:auth,'Content-Type':'application/json',...(init.headers??{})}}),raw=await response.text(),payload:unknown=raw?JSON.parse(raw):null;if(!response.ok)throw new Error(typeof payload==='object'&&payload&&'message'in payload?String(payload.message):'No fue posible guardar el tipo de cambio.');return payload as T;}
async function currency(auth:string,code:string){const rows=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_code=eq.${encodeURIComponent(code)}&limit=1`,auth);if(!rows[0])throw new Error(`La moneda ${code} no existe en el catálogo de Monedas.`);return rows[0];}
async function localCurrency(auth:string){const tokenClaims=claims(auth),session=String(tokenClaims.session_id??tokenClaims.sub??''),selected=await rest<Array<{subsidiary_id:number}>>(`user_company_sessions?select=subsidiary_id&session_id=eq.${encodeURIComponent(session)}&limit=1`,auth);if(!selected[0])throw new Error('Debe seleccionar una empresa activa antes de consultar el tipo de cambio.');const subsidiaries=await rest<Array<{currency_id:number}>>(`subsidiaries?select=currency_id&subsidiary_id=eq.${selected[0].subsidiary_id}&limit=1`,auth),currencies=await rest<CurrencyRow[]>(`currencies?select=currency_id,currency_code&currency_id=eq.${subsidiaries[0]?.currency_id??-1}&limit=1`,auth);if(!currencies[0])throw new Error('La moneda local de la empresa activa no está configurada.');return currencies[0];}
async function save(auth:string,key:string|undefined,origin:CurrencyRow,destination:CurrencyRow,rate:Awaited<ReturnType<typeof obtenerTipoDeCambioPE>>){const rows=await rest<Array<Record<string,unknown>>>('exchange_rates?on_conflict=from_currency_id,to_currency_id,effective_date',auth,{method:'POST',headers:{...(key?{apikey:key}:{}),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({from_currency_id:origin.currency_id,to_currency_id:destination.currency_id,effective_date:rate.fechaEfectiva,spot_rate:rate.tipoCambio})});return{...rate,guardado:true,registro:rows[0]};}
export async function consultarYGuardarTipoDeCambioPE(auth:string,input:{monedaOrigen?:string;monedaDestino?:string;fechaEfectiva?:Date|string}){const origin=await currency(auth,(input.monedaOrigen||'USD').trim().toUpperCase()),destination=input.monedaDestino?await currency(auth,input.monedaDestino.trim().toUpperCase()):await localCurrency(auth),rate=await obtenerTipoDeCambioPE(origin.currency_code,destination.currency_code,input.fechaEfectiva);return origin.currency_id===destination.currency_id?{...rate,guardado:false}:save(auth,undefined,origin,destination,rate);}
export async function consultarYGuardarTipoDeCambioPEAutomatico(fechaEfectiva?:Date|string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error('SUPABASE_SERVICE_ROLE_KEY no está configurada para la automatización.');const auth=`Bearer ${key}`,[origin,destination]=await Promise.all([currency(auth,'USD'),currency(auth,'PEN')]);return save(auth,key,origin,destination,await obtenerTipoDeCambioPE('USD','PEN',fechaEfectiva));}
