import{getSupabaseConfig}from'../../core/database/supabase.client.js';type T='text'|'number'|'boolean'|'datetime-local';export interface WorkflowField{key:string;label:string;type:T;required?:boolean;reference?:string;}export interface WorkflowCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:WorkflowField[];}
export const workflowCatalogs:WorkflowCatalog[]=[
{slug:'workflows',table:'workflow',title:'Flujos de trabajo',description:'Definición de flujos de trabajo',primaryKey:'workflow_id',fields:[{key:'workflow_name',label:'Flujo',type:'text',required:true},{key:'target_module',label:'Módulo objetivo',type:'text',required:true},{key:'is_active',label:'Activo',type:'boolean'}]},
{slug:'workflow-steps',table:'workflow_step',title:'Pasos del flujo',description:'Pasos y etapas del flujo',primaryKey:'step_id',fields:[{key:'workflow_id',label:'Flujo',type:'number',required:true,reference:'workflow/workflows'},{key:'step_order',label:'Orden',type:'number',required:true},{key:'step_name',label:'Paso',type:'text',required:true}]},
{slug:'workflow-rules',table:'workflow_rule',title:'Reglas del flujo',description:'Reglas y condiciones del flujo',primaryKey:'rule_id',fields:[{key:'step_id',label:'Paso',type:'number',required:true,reference:'workflow/workflow-steps'},{key:'condition_field',label:'Campo de condición',type:'text',required:true},{key:'operator',label:'Operador',type:'text',required:true},{key:'condition_value',label:'Valor',type:'text',required:true}]},
{slug:'workflow-actions',table:'workflow_action',title:'Acciones del flujo',description:'Acciones ejecutables por workflow',primaryKey:'action_id',fields:[{key:'step_id',label:'Paso',type:'number',required:true,reference:'workflow/workflow-steps'},{key:'action_type',label:'Tipo de acción',type:'text',required:true},{key:'execution_payload',label:'Datos de ejecución',type:'text',required:true}]},
{slug:'approval-matrices',table:'approval_matrix',title:'Matrices de aprobación',description:'Matrices de aprobaciones corporativas',primaryKey:'matrix_id',fields:[{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'department_id',label:'Departamento',type:'number',reference:'organization/departments'},{key:'transaction_type_id',label:'Tipo de transacción',type:'number',required:true,reference:'core/transaction-types'},{key:'min_amount',label:'Monto mínimo',type:'number',required:true},{key:'max_amount',label:'Monto máximo',type:'number',required:true},{key:'approver_role_id',label:'Rol aprobador',type:'number',required:true,reference:'security/roles'}]},
{slug:'approvals',table:'approval',title:'Solicitudes de aprobación',description:'Solicitudes de aprobación activas',primaryKey:'approval_id',fields:[{key:'transaction_id',label:'Transacción',type:'number',required:true,reference:'transaction-engine/transactions'},{key:'current_step_id',label:'Paso actual',type:'number',required:true,reference:'workflow/workflow-steps'},{key:'status',label:'Estado',type:'text',required:true}]},
{slug:'approval-logs',table:'approval_log',title:'Historial de aprobaciones',description:'Historial de decisiones de aprobación',primaryKey:'log_id',fields:[{key:'approval_id',label:'Solicitud',type:'number',required:true,reference:'workflow/approvals'},{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'action',label:'Acción',type:'text',required:true},{key:'comments',label:'Comentarios',type:'text'},{key:'action_timestamp',label:'Fecha y hora',type:'datetime-local',required:true}]}
];
export function getWorkflowCatalog(s:string){const c=workflowCatalogs.find(x=>x.slug===s);if(!c)throw new Error('El catálogo de Workflow no existe.');return c;}function sanitize(c:WorkflowCatalog,i:Record<string,unknown>){const d=Object.fromEntries(c.fields.map(f=>{const r=i[f.key];if(f.required&&(r===undefined||r===null||String(r).trim()===''))throw new Error(`${f.label} es obligatorio.`);if(f.type==='boolean')return[f.key,Boolean(r)];if(f.type==='number')return[f.key,r===undefined||r===null||r===''?null:Number(r)];return[f.key,r===undefined||r===null||String(r).trim()===''?null:String(r).trim()];}));if(c.slug==='approval-matrices'&&Number(d.max_amount)<Number(d.min_amount))throw new Error('El monto máximo debe ser mayor o igual al monto mínimo.');return d;}async function request<R>(c:WorkflowCatalog,t:string,q='',i:RequestInit={}):Promise<R>{const g=getSupabaseConfig();if(!g)throw new Error('Supabase no está configurado.');const r=await fetch(new URL(`/rest/v1/${c.table}${q}`,g.url),{...i,headers:{apikey:g.anonKey,Authorization:t,'Content-Type':'application/json',...(i.headers??{})}});const x=r.status===204?'':await r.text();const p:unknown=x?JSON.parse(x):null;if(!r.ok){const m=typeof p==='object'&&p!==null&&'message'in p?String(p.message):'No fue posible completar la operación.';throw new Error(m);}return p as R;}
export const listWorkflowRows=(c:WorkflowCatalog,t:string)=>request<Record<string,unknown>[]>(c,t,`?select=*&order=${c.primaryKey}.asc`);export async function createWorkflowRow(c:WorkflowCatalog,t:string,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export async function updateWorkflowRow(c:WorkflowCatalog,t:string,id:number,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export const deleteWorkflowRow=(c:WorkflowCatalog,t:string,id:number)=>request<null>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'DELETE'});
