import{getSupabaseConfig}from'../../core/database/supabase.client.js';type T='text'|'number'|'boolean'|'datetime-local';export interface DocumentField{key:string;label:string;type:T;required?:boolean;reference?:string;}export interface DocumentCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:DocumentField[];}
export const documentCatalogs:DocumentCatalog[]=[
{slug:'folders',table:'folders',title:'Carpetas',description:'Carpetas de almacenamiento de documentos',primaryKey:'folder_id',fields:[{key:'folder_name',label:'Carpeta',type:'text',required:true},{key:'parent_id',label:'Carpeta superior',type:'number',reference:'documents/folders'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'}]},
{slug:'document-types',table:'document_type',title:'Tipos de documentos',description:'Tipos de documentos adjuntos',primaryKey:'type_id',fields:[{key:'type_name',label:'Tipo de documento',type:'text',required:true},{key:'allowed_extensions',label:'Extensiones permitidas',type:'text',required:true},{key:'max_file_size_mb',label:'Tamaño máximo (MB)',type:'number',required:true}]},
{slug:'documents',table:'documents',title:'Documentos',description:'Documentos y archivos adjuntos',primaryKey:'document_id',fields:[{key:'file_name',label:'Archivo',type:'text',required:true},{key:'file_path',label:'Ruta del archivo',type:'text',required:true},{key:'folder_id',label:'Carpeta',type:'number',required:true,reference:'documents/folders'},{key:'type_id',label:'Tipo',type:'number',required:true,reference:'documents/document-types'},{key:'uploaded_by_user_id',label:'Cargado por',type:'number',required:true,reference:'security/users'},{key:'file_size',label:'Tamaño (bytes)',type:'number',required:true},{key:'mime_type',label:'Tipo MIME',type:'text',required:true}]},
{slug:'document-versions',table:'document_version',title:'Versiones de documentos',description:'Versiones de archivos',primaryKey:'version_id',fields:[{key:'document_id',label:'Documento',type:'number',required:true,reference:'documents/documents'},{key:'version_number',label:'Versión',type:'number',required:true},{key:'file_path',label:'Ruta del archivo',type:'text',required:true},{key:'uploaded_at',label:'Fecha y hora',type:'datetime-local',required:true}]},
{slug:'document-relations',table:'document_relation',title:'Relaciones de documentos',description:'Relación con entidades o transacciones',primaryKey:'relation_id',fields:[{key:'document_id',label:'Documento',type:'number',required:true,reference:'documents/documents'},{key:'target_entity_type',label:'Tipo de entidad',type:'text',required:true},{key:'target_entity_id',label:'ID de entidad',type:'number',required:true}]},
{slug:'document-permissions',table:'document_permission',title:'Permisos de documentos',description:'Permisos de acceso a documentos',primaryKey:'permission_id',fields:[{key:'document_id',label:'Documento',type:'number',required:true,reference:'documents/documents'},{key:'role_id',label:'Rol',type:'number',reference:'security/roles'},{key:'user_id',label:'Usuario',type:'number',reference:'security/users'},{key:'can_read',label:'Puede leer',type:'boolean'},{key:'can_write',label:'Puede escribir',type:'boolean'}]}
];
export function getDocumentCatalog(s:string){const c=documentCatalogs.find(x=>x.slug===s);if(!c)throw new Error('El catálogo de Documentos no existe.');return c;}function sanitize(c:DocumentCatalog,i:Record<string,unknown>){const d=Object.fromEntries(c.fields.map(f=>{const r=i[f.key];if(f.required&&(r===undefined||r===null||String(r).trim()===''))throw new Error(`${f.label} es obligatorio.`);if(f.type==='boolean')return[f.key,Boolean(r)];if(f.type==='number')return[f.key,r===undefined||r===null||r===''?null:Number(r)];return[f.key,r===undefined||r===null||String(r).trim()===''?null:String(r).trim()];}));if(c.slug==='document-permissions'&&!d.role_id&&!d.user_id)throw new Error('Debe seleccionar un rol o un usuario.');return d;}async function request<R>(c:DocumentCatalog,t:string,q='',i:RequestInit={}):Promise<R>{const g=getSupabaseConfig();if(!g)throw new Error('Supabase no está configurado.');const r=await fetch(new URL(`/rest/v1/${c.table}${q}`,g.url),{...i,headers:{apikey:g.anonKey,Authorization:t,'Content-Type':'application/json',...(i.headers??{})}});const x=r.status===204?'':await r.text();const p:unknown=x?JSON.parse(x):null;if(!r.ok){const m=typeof p==='object'&&p!==null&&'message'in p?String(p.message):'No fue posible completar la operación.';throw new Error(m);}return p as R;}
export const listDocumentRows=(c:DocumentCatalog,t:string)=>request<Record<string,unknown>[]>(c,t,`?select=*&order=${c.primaryKey}.asc`);export async function createDocumentRow(c:DocumentCatalog,t:string,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export async function updateDocumentRow(c:DocumentCatalog,t:string,id:number,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export const deleteDocumentRow=(c:DocumentCatalog,t:string,id:number)=>request<null>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'DELETE'});
