import { fetchSupabase, getSupabaseConfig } from '../../core/database/supabase.client.js';

const rpcNames:Record<string,string>={options:'pdf_template_options',save:'pdf_template_save',clone:'pdf_template_clone',delete:'pdf_template_delete',get:'pdf_template_compiled'};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const allowedTypes=new Set(['text','image','divider','spacer','columns','items_table','totals','qr','signature','fiscal']);
const cleanColor=(v:unknown)=>/^#[0-9a-f]{3,8}$/i.test(String(v))?String(v):'';
const size=(v:unknown,min:number,max:number,fallback:number)=>Math.min(max,Math.max(min,Number(v)||fallback));

function componentHtml(raw:unknown):string{
 const c=(raw&&typeof raw==='object'?raw:{})as Record<string,unknown>,type=String(c.type||'text');if(!allowedTypes.has(type))return'';
 const st=(c.style&&typeof c.style==='object'?c.style:{})as Record<string,unknown>;
 const style=`font-size:${size(st.fontSize,7,48,11)}pt;color:${cleanColor(st.color)||'#172033'};background:${cleanColor(st.background)||'transparent'};text-align:${['left','center','right'].includes(String(st.align))?st.align:'left'};font-weight:${Number(st.fontWeight)>=600?700:400};padding:${size(st.padding,0,30,4)}px;margin:${size(st.margin,0,30,2)}px;border:${st.border?'1px solid #d6dee8':'0'}`;
 if(type==='divider')return'<hr class="block-divider">';if(type==='spacer')return`<div style="height:${size(c.height,4,100,18)}px"></div>`;
 if(type==='image')return`<div style="${style}"><img class="dynamic-image" src="${esc(c.binding||'{{company.logo_url}}')}" alt="Logo"></div>`;
 if(type==='items_table')return'<table class="items"><thead><tr>'+((Array.isArray(c.columns)?c.columns:['description','quantity','unit_price','subtotal'])as unknown[]).map(x=>`<th>${esc(String(x).replaceAll('_',' '))}</th>`).join('')+'</tr></thead><tbody>{{items.rows}}</tbody></table>';
 if(type==='totals')return'<section class="totals"><div>Subtotal <b>{{totals.subtotal}}</b></div><div>Descuentos <b>{{totals.discount_total}}</b></div><div>Impuestos <b>{{totals.tax_total}}</b></div><div class="grand">Total <b>{{totals.grand_total}}</b></div><small>{{totals.amount_in_words}}</small></section>';
 if(type==='qr')return'<div class="qr">▦<small>{{fiscal.electronic_key}}</small></div>';
 if(type==='signature')return'<div class="signature"><span>Firma autorizada</span><span>Recibido por</span></div>';
 if(type==='fiscal')return`<div class="fiscal" style="${style}">${esc(c.content||'Clave: {{fiscal.electronic_key}} · Consecutivo: {{document.number}}')}</div>`;
 if(type==='columns'){const children=Array.isArray(c.children)?c.children:[];return`<div class="columns">${children.map(componentHtml).join('')}</div>`}
 return`<div class="text-block" style="${style}">${esc(c.content||'Texto')}</div>`;
}
export function compilePdfTemplate(schema:unknown,pageSize='A4',orientation='PORTRAIT'){
 const s=(schema&&typeof schema==='object'?schema:{})as Record<string,unknown>,zones=(s.zones&&typeof s.zones==='object'?s.zones:{})as Record<string,unknown>,m=(s.margins&&typeof s.margins==='object'?s.margins:{})as Record<string,unknown>;
 const zone=(name:string)=>((Array.isArray(zones[name])?zones[name]:[])as unknown[]).map(componentHtml).join('');
 const dims=pageSize==='LETTER'?'216mm 279mm':pageSize==='THERMAL_80'?'80mm auto':'210mm 297mm';
 return`<!doctype html><html><head><meta charset="utf-8"><style>@page{size:${dims} ${orientation==='LANDSCAPE'?'landscape':'portrait'};margin:${size(m.top,0,40,12)}mm ${size(m.right,0,40,12)}mm ${size(m.bottom,0,40,12)}mm ${size(m.left,0,40,12)}mm}*{box-sizing:border-box}body{font:11pt Arial;color:#172033;margin:0}.page-header{border-bottom:2px solid #17845f;padding-bottom:7px}.page-footer{border-top:1px solid #ccd5df;padding-top:7px;font-size:8pt}.items{width:100%;border-collapse:collapse;margin:14px 0}.items th,.items td{padding:7px;border-bottom:1px solid #dce3eb;text-align:left}.items th{background:#eef4f1;text-transform:capitalize}.totals{width:310px;margin-left:auto}.totals div{display:flex;justify-content:space-between;padding:5px}.totals .grand{border-top:2px solid #16855f;font-size:14pt}.dynamic-image{max-width:160px;max-height:75px}.signature{display:flex;justify-content:space-between;margin-top:55px}.signature span{width:42%;border-top:1px solid;padding-top:6px;text-align:center}.qr{font-size:48px;text-align:center}.qr small{font-size:7pt;display:block}.columns{display:flex;gap:10px}.columns>*{flex:1}@media print{.page-header{position:running(header)}.page-footer{position:running(footer)}tr{break-inside:avoid}.totals{break-inside:avoid}}</style></head><body><header class="page-header">${zone('header')}</header><main>${zone('body')}</main><footer class="page-footer">${zone('footer')}</footer></body></html>`;
}
const mock=(number='FAC-001045')=>({company:{name:'S.T.T. HOLDINGS LIMITED',tax_id:'3-101-123456',logo_url:'',address:'San José, Costa Rica',phone:'+506 2200-0000',email:'facturacion@empresa.com',economic_activity:'Servicios profesionales'},entity:{name:'Cliente de ejemplo S.A.',tax_id:'3-101-654321',address:'San José',phone:'+506 8888-0000',email:'cliente@ejemplo.com',credit_days:'30'},document:{title:'Documento comercial',number,issue_date:'10/09/2026',due_date:'10/10/2026',currency_symbol:'$',seller_name:'Usuario NEXO',payment_method:'Crédito'},totals:{subtotal:'1 000,00',discount_total:'0,00',tax_total:'130,00',grand_total:'1 130,00',amount_in_words:'Mil ciento treinta con 00/100'},fiscal:{electronic_key:'50610092600310112345600100001010000001045100000001',qr_code:''},items:[{code:'SERV-001',description:'Servicio profesional',quantity:'1',unit_price:'1 000,00',discount:'0,00',tax_rate:'13%',subtotal:'1 000,00'}]});
function render(compiled:string,data:Record<string,unknown>){let html=compiled;const flat:Record<string,unknown>={};for(const[k,v]of Object.entries(data))if(v&&typeof v==='object'&&!Array.isArray(v))for(const[a,b]of Object.entries(v))flat[`${k}.${a}`]=b;for(const[k,v]of Object.entries(flat))html=html.replaceAll(`{{${k}}}`,esc(v));const cols=['code','description','quantity','unit_price','discount','tax_rate','subtotal'],items=Array.isArray(data.items)?data.items as Array<Record<string,unknown>>:[];html=html.replace('{{items.rows}}',items.map(i=>`<tr>${cols.map(k=>`<td>${esc(i[k]??'')}</td>`).join('')}</tr>`).join(''));return html.replace(/\{\{[\w.]+\}\}/g,'');}
async function rpc(auth:string,name:string,params:Record<string,unknown>={}){const c=getSupabaseConfig();if(!c)throw Error('Supabase no está configurado.');const r=await fetchSupabase(new URL(`/rest/v1/rpc/${name}`,c.url),{method:'POST',headers:{apikey:c.anonKey,Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify(params)}),raw=await r.text(),out=raw?JSON.parse(raw):null;if(!r.ok)throw Error(out?.message||'No fue posible procesar la plantilla.');return out}
export async function pdfTemplates(auth:string,action:string,p:Record<string,unknown>={}){if(action==='save'){const schema=structuredClone(p.schema??{});const zones=((schema as Record<string,unknown>).zones??{})as Record<string,unknown>;if(p.documentType==='FAC_VEN'){const footer=Array.isArray(zones.footer)?zones.footer:[];if(!footer.some(x=>x&&typeof x==='object'&&(x as Record<string,unknown>).type==='fiscal'))footer.push({id:`fiscal-${Date.now()}`,type:'fiscal',content:'Clave: {{fiscal.electronic_key}} · Consecutivo: {{document.number}}',locked:true});zones.footer=footer}return rpc(auth,rpcNames.save,{p:{...p,schema,compiled:compilePdfTemplate(schema,String(p.pageSize||'A4'),String(p.orientation||'PORTRAIT'))}})}if(action==='render'){const compiled=p.compiled?String(p.compiled):compilePdfTemplate(p.schema,String(p.pageSize||'A4'),String(p.orientation||'PORTRAIT')),number=String(p.documentNumber||'').trim(),data=number?await rpc(auth,'pdf_template_document_data',{p_type:String(p.documentType),p_number:number}):mock();return{html:render(compiled,data as Record<string,unknown>)}}const name=rpcNames[action];if(!name)throw Error('Acción de plantilla inválida.');return rpc(auth,name,action==='clone'||action==='delete'||action==='get'?{p_id:Number(p.id)}:{})}
