import{getSupabaseConfig}from'../../core/database/supabase.client.js';type T='text'|'number'|'date'|'boolean';export interface ExpenseField{key:string;label:string;type:T;required?:boolean;reference?:string;}export interface ExpenseCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:ExpenseField[];}
export const expenseCatalogs:ExpenseCatalog[]=[
{slug:'expense-types',table:'expense_type',title:'Tipos de gastos',description:'Tipos de gastos',primaryKey:'expense_type_id',fields:[{key:'type_name',label:'Tipo de gasto',type:'text',required:true},{key:'account_id',label:'Cuenta contable',type:'number',required:true,reference:'accounting/chart-accounts'},{key:'requires_receipt',label:'Requiere comprobante',type:'boolean'}]},
{slug:'expense-policies',table:'expense_policy',title:'Políticas de gastos',description:'Políticas de gastos por subsidiaria',primaryKey:'policy_id',fields:[{key:'policy_name',label:'Política',type:'text',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'max_amount_per_expense',label:'Monto máximo por gasto',type:'number',required:true}]},
{slug:'expenses',table:'expense',title:'Informes de gastos',description:'Informes y declaraciones de gastos',primaryKey:'expense_id',fields:[{key:'expense_number',label:'Número',type:'text',required:true},{key:'employee_id',label:'Empleado',type:'number',required:true,reference:'entities/employees'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'currency_id',label:'Moneda',type:'number',required:true,reference:'core/currencies'},{key:'total_amount',label:'Monto total',type:'number',required:true},{key:'status_id',label:'Estado',type:'number',required:true,reference:'core/status'}]},
{slug:'expense-lines',table:'expense_line',title:'Detalle de gastos',description:'Detalle de gastos declarados',primaryKey:'expense_line_id',fields:[{key:'expense_id',label:'Informe de gasto',type:'number',required:true,reference:'expenses/expenses'},{key:'expense_type_id',label:'Tipo de gasto',type:'number',required:true,reference:'expenses/expense-types'},{key:'amount',label:'Monto',type:'number',required:true},{key:'tax_amount',label:'Impuesto',type:'number',required:true},{key:'department_id',label:'Departamento',type:'number',reference:'organization/departments'},{key:'class_id',label:'Clase',type:'number',reference:'organization/classes'}]},
{slug:'expense-approvals',table:'expense_approval',title:'Aprobaciones de gastos',description:'Aprobaciones de informes de gastos',primaryKey:'approval_id',fields:[{key:'expense_id',label:'Informe de gasto',type:'number',required:true,reference:'expenses/expenses'},{key:'approver_user_id',label:'Usuario aprobador',type:'number',required:true,reference:'security/users'},{key:'approval_date',label:'Fecha de aprobación',type:'date',required:true},{key:'status',label:'Estado',type:'text',required:true}]},
{slug:'expense-payments',table:'expense_payment',title:'Pagos de gastos',description:'Reembolsos y pagos de gastos a empleados',primaryKey:'payment_id',fields:[{key:'payment_date',label:'Fecha de pago',type:'date',required:true},{key:'expense_id',label:'Informe de gasto',type:'number',required:true,reference:'expenses/expenses'},{key:'bank_account_id',label:'Cuenta bancaria',type:'number',required:true,reference:'banking/bank-accounts'},{key:'amount_paid',label:'Monto pagado',type:'number',required:true}]}
];
export function getExpenseCatalog(s:string){const c=expenseCatalogs.find(x=>x.slug===s);if(!c)throw new Error('El catálogo de Gastos no existe.');return c;}function sanitize(c:ExpenseCatalog,i:Record<string,unknown>){return Object.fromEntries(c.fields.map(f=>{const r=i[f.key];if(f.required&&(r===undefined||r===null||String(r).trim()===''))throw new Error(`${f.label} es obligatorio.`);if(f.type==='boolean')return[f.key,Boolean(r)];if(f.type==='number')return[f.key,r===undefined||r===null||r===''?null:Number(r)];return[f.key,r===undefined||r===null||String(r).trim()===''?null:String(r).trim()];}));}async function request<R>(c:ExpenseCatalog,t:string,q='',i:RequestInit={}):Promise<R>{const g=getSupabaseConfig();if(!g)throw new Error('Supabase no está configurado.');const r=await fetch(new URL(`/rest/v1/${c.table}${q}`,g.url),{...i,headers:{apikey:g.anonKey,Authorization:t,'Content-Type':'application/json',...(i.headers??{})}});const x=r.status===204?'':await r.text();const p:unknown=x?JSON.parse(x):null;if(!r.ok){const m=typeof p==='object'&&p!==null&&'message'in p?String(p.message):'No fue posible completar la operación.';throw new Error(m);}return p as R;}
export const listExpenseRows=(c:ExpenseCatalog,t:string)=>request<Record<string,unknown>[]>(c,t,`?select=*&order=${c.primaryKey}.asc`);export async function createExpenseRow(c:ExpenseCatalog,t:string,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export async function updateExpenseRow(c:ExpenseCatalog,t:string,id:number,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export const deleteExpenseRow=(c:ExpenseCatalog,t:string,id:number)=>request<null>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'DELETE'});
