import {chromium} from '../.tmp/record-audit-validation/node_modules/playwright-core/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try{
 const page=await browser.newPage({viewport:{width:1500,height:1000}});page.setDefaultTimeout(15000);await page.addInitScript(()=>localStorage.setItem('nexo_token','consolidated-report-test'));const calls=[];
 await page.route('**/api/reports/accounting/options',route=>route.fulfill({json:{subsidiaries:[{id:1,name:'Empresa Uno',currencyId:1},{id:2,name:'Empresa Dos',currencyId:2}],currencies:[{id:1,code:'JMD',symbol:'J$'},{id:2,code:'CRC',symbol:'₡'}],books:[],periods:[],departments:[],locations:[],classes:[],costCenters:[],accounts:[],thirdParties:[],accountGroups:[],journalOptions:{canReverse:true,modules:[]},pendingInvoiceOptions:{customers:[]},agingOptions:{customers:[{id:5,name:'Cliente Consolidado',subsidiaryId:2}],suppliers:[{id:8,name:'Proveedor Consolidado',subsidiaryId:2}],salesRepresentatives:[],supplierCategories:[]}}}));
 for(const [path,kind]of[['receivables-aging','AR'],['payables-aging','AP']])await page.route(`**/api/reports/accounting/${path}`,route=>{const p=route.request().postDataJSON();calls.push({kind,p});const ar=kind==='AR',row={document_id:10,entity_id:ar?5:8,entity_code:ar?'CLI-5':'PRO-8',identification:'ID-1',entity_name:ar?'Cliente Consolidado':'Proveedor Consolidado',entity_category:'Servicios',manager:'Gestor',document_number:'DOC-1',external_document_number:'EXT-1',issue_date:'2026-08-01',due_date:'2026-08-31',overdue_days:0,bucket:'CURRENT',original_amount:100,pending:100,entity_advances:0,journal_id:4,...(p.consolidated?{subsidiary_id:2,subsidiary_name:'Empresa Dos',presentation_currency:'USD',conversion_rate:.007}:{})};route.fulfill({json:{rows:[row],total:1,summary:{subledger:100,advances:0,netBalance:100,controlBalance:100,difference:0},...(p.consolidated?{consolidated:true,currency:'USD'}:{})}})});
 await page.goto('http://localhost:3000/',{waitUntil:'domcontentloaded',timeout:30000});await page.setContent('<iframe id="reports" src="http://localhost:3000/accounting-reports.html" style="width:1450px;height:950px"></iframe>');const app=page.frameLocator('#reports');
 for(const [title,kind]of[['Cuentas por Cobrar','AR'],['Cuentas por Pagar','AP']]){await app.getByText(title,{exact:true}).click();await app.locator('#agingCurrencyMode').selectOption('CONSOLIDATED');await app.locator('#tbody').getByText('Empresa Dos',{exact:true}).waitFor();assert.equal(calls.at(-1).kind,kind);assert.equal(calls.at(-1).p.consolidated,true);assert.equal(calls.at(-1).p.agingCurrencyMode,'LOCAL');assert.match(await app.locator('#summary').innerText(),/US\$/);assert.equal(await app.locator('[data-statement],[data-email-statement]').count(),0);await app.locator('#catalog').click()}
 console.log(JSON.stringify({receivablesConsolidated:true,payablesConsolidated:true,usdPresentation:true,companyOrigin:true,allAccessibleScope:true}));
}finally{await browser.close()}
