-- Isolated PostgreSQL fixture for import validation; production posting is stubbed.
create role anon; create role authenticated;
create table subsidiaries(subsidiary_id bigint primary key,currency_id bigint);
create table currencies(currency_id bigint primary key,currency_code text);
create table subsidiary_currencies(subsidiary_id bigint,currency_id bigint);
create table transaction_types(abbreviation text,name text);
create table fiscal_periods(fiscal_period_id bigint,subsidiary_id bigint,start_date date,end_date date,is_inactive boolean);
create table exchange_rates(exchange_rate_id bigint,from_currency_id bigint,to_currency_id bigint,effective_date date,spot_rate numeric);
create table chart_accounts(account_id bigint,account_number text,is_inactive boolean,accepts_entries boolean);
create table account_subsidiaries(account_id bigint,subsidiary_id bigint,is_active boolean);
create table journal(journal_id bigint generated always as identity primary key,journal_number text,memo text);
create table journal_line(journal_id bigint,debit numeric,credit numeric);
create table users(user_id bigint,email text);
create table user_company_sessions(user_id bigint,session_id text,selected_at timestamptz);
insert into subsidiaries values(1,1),(2,1);
insert into currencies values(1,'CRC');
insert into transaction_types values('ASI_DIA','Asiento de Diario General');
insert into fiscal_periods values(1,1,'2026-09-01','2026-09-30',false);
insert into chart_accounts values(1,'001',false,true),(2,'002',false,true),(3,'003',true,true),(4,'004',false,false),(5,'005',false,true);
insert into account_subsidiaries values(1,1,true),(2,1,true),(3,1,true),(4,1,true),(5,2,true);
insert into users values(1,'csv-test@example.invalid');
insert into user_company_sessions values(1,'test-session',now());
create function active_subsidiary_id() returns bigint language sql as $$select 1::bigint$$;
create function create_journal_entry(payload jsonb) returns bigint language plpgsql as $$
declare jid bigint;
begin
  insert into journal(memo) values(payload->>'memo') returning journal_id into jid;
  update journal set journal_number='TEST-'||jid where journal_id=jid;
  insert into journal_line select jid,(r->>'debit')::numeric,(r->>'credit')::numeric from jsonb_array_elements(payload->'lines')r;
  return jid;
end$$;
create table customers(customer_id bigint,company_name text,department_id bigint,is_inactive boolean);
create table suppliers(supplier_id bigint,company_name text,is_inactive boolean);
create table employees(employee_id bigint,first_name text,last_name text,subsidiary_id bigint,is_inactive boolean);
create table entity_subsidiaries(customer_id bigint,supplier_id bigint,subsidiary_id bigint);
create table departments(department_id bigint,name text,type text,is_inactive boolean);
create table department_subsidiaries(department_id bigint,subsidiary_id bigint);
create table classes(class_id bigint,name text,is_inactive boolean);
create table class_subsidiaries(class_id bigint,subsidiary_id bigint);
create table cost_centers(cost_center_id bigint,name text,customer_id bigint,class_id bigint,subsidiary_id bigint);
create table financial_creditors(financial_creditor_id bigint,name text,is_inactive boolean);
create table financial_creditor_subsidiaries(financial_creditor_id bigint,subsidiary_id bigint);
create table related_companies(related_company_id bigint,name text,is_inactive boolean);
create table related_company_subsidiaries(related_company_id bigint,subsidiary_id bigint);
insert into customers values(10,'Cliente prueba',20,false),(11,'Cliente ajeno',20,false);
insert into suppliers values(10,'Proveedor prueba',false);
insert into employees values(10,'Ana','Prueba',1,false);
insert into entity_subsidiaries values(10,null,1),(11,null,2),(null,10,1);
insert into departments values(20,'Servicios','Cliente',false),(21,'Administracion','Interno',false),(22,'Inactivo','Interno',true);
insert into department_subsidiaries values(20,1),(21,1),(22,1);
insert into classes values(30,'Consultoria',false),(31,'Otra clase',false);
insert into class_subsidiaries values(30,1),(31,1);
insert into cost_centers values(40,'Proyecto',10,30,1);
insert into financial_creditors values(50,'Banco prueba',false),(51,'Duplicado',false),(52,'Duplicado',false);
insert into financial_creditor_subsidiaries values(50,1),(51,1),(52,1);
insert into related_companies values(60,'Relacionada prueba',false);
insert into related_company_subsidiaries values(60,1);
