import { readFile } from 'node:fs/promises';
import { renderBankReconciliationPdf } from '../dist/modules/reports/accounting-reports.service.js';
import { chromium } from '../.tmp/record-audit-validation/node_modules/playwright-core/index.mjs';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1500,height:1000}});page.setDefaultTimeout(7000);
page.on('pageerror',error=>console.error('PAGE_ERROR',error.message));
await page.addInitScript(()=>localStorage.setItem('nexo_token','ui-check'));
let reversalPayload=null,pdfPayload=null;
await page.route('**/api/reports/accounting/pending-invoice-control/pdf',async route=>{pdfPayload=route.request().postDataJSON();await route.fulfill({json:await renderBankReconciliationPdf(pdfPayload)})});

const requestedInvoiceDates=[];
await page.route('**/api/reports/accounting/options',route=>route.fulfill({json:{subsidiaries:[{id:1,name:'Empresa',currencyId:1}],currencies:[{id:1,code:'USD',symbol:'$'}],books:[],periods:[],departments:[],locations:[],classes:[],costCenters:[],accounts:[],thirdParties:[],accountGroups:[],journalOptions:{canReverse:true,modules:[]},pendingInvoiceOptions:{customers:[{id:5,name:'Cliente Uno'}]}}}));
await page.route('**/api/reports/accounting/pending-invoice-control',route=>route.fulfill({json:{rows:[{journal_id:7,journal_number:'ASI_PEN-00000001',date:'2026-09-01',customer_id:5,customer:'Cliente Uno',initial:1000,reversed:250,balance:750,status:'REVERSADO_PARCIAL',reversals:[{journalId:8,number:'ASI_REV_PEN-00000001',date:'2026-09-10',amount:250,type:'FACTURACION',reference:'FAC_VEN-25',user:'Usuario Prueba'}]},{journal_id:11,journal_number:'ASI_PEN-00000011',date:'2026-09-01',customer:'Cliente Uno',initial:500,reversed:500,balance:0,status:'REVERSADO_TOTAL',reversals:[]},{journal_id:12,journal_number:'ASI_PEN-00000012',date:'2026-09-01',customer:'Cliente Uno',initial:300,reversed:0,balance:300,status:'PENDIENTE',reversals:[]}],total:3,summary:{initial:1800,reversed:750,balance:1050}}}));
await page.route('**/api/reports/accounting/pending-invoices/7/reversal-options*',route=>{const date=new URL(route.request().url()).searchParams.get('date');requestedInvoiceDates.push(date);route.fulfill({json:{journal:{id:7,number:'ASI_PEN-00000001',initialLocal:1000,reversedLocal:250,balanceLocal:750,status:'REVERSADO_PARCIAL'},invoices:date?.startsWith('2026-09')?[{id:9,number:'FAC_VEN-25',date:'2026-09-08',customerId:5,customer:'Cliente Uno',total:800}]:[],reversals:[]}})});
await page.route('**/api/reports/accounting/pending-invoices/7/reverse',async route=>{reversalPayload=route.request().postDataJSON();await route.fulfill({status:201,json:{journalId:10,number:'ASI_REV_PEN-00000002',amount:200,remaining:550}})});
await page.goto('http://localhost:3000/');await page.setContent('<iframe id="app" src="http://localhost:3000/accounting-reports.html" style="width:1400px;height:900px"></iframe>');const app=page.frameLocator('#app');
await app.getByText('Control de Pendientes de Facturar',{exact:true}).click();await app.locator('#tbody tr').first().waitFor();
if(await app.locator('#pendingCustomer option').count()!==2)throw Error('No se cargÃ³ el filtro de clientes.');
if(!(await app.getByText('REVERSADO PARCIAL',{exact:true}).count()))throw Error('No se mostrÃ³ el estado del pendiente.');
if(await app.locator('.pending-parent').count()!==2)throw Error('La pesta?a inicial debe mostrar pendientes y parciales.');
if(await app.locator('#summary .metric b').first().textContent()!=='$ 1 300,00'&&!(await app.locator('#summary .metric b').first().textContent()).replace(/\s/g,'').includes('1300,00'))throw Error('El total incluye asientos cerrados.');
await app.locator('#pendingClosedTab').click();
if(await app.locator('.pending-parent').count()!==1||!await app.locator('[data-node="pending-11"]').count())throw Error('La pesta?a cerrada no filtra los reversados totales.');
if(await app.locator('#pendingStatus').count())throw Error('No debe existir un filtro que separe pendientes y parciales.');
if(await app.locator('#pendingClosedTab').getAttribute('aria-pressed')!=='true')throw Error('No se marca la pesta?a activa.');
const closedDownload=page.waitForEvent('download',{timeout:60000});await app.locator('#pdf').click();const closedPdf=await closedDownload;
if(!(await readFile(await closedPdf.path())).subarray(0,5).equals(Buffer.from('%PDF-')))throw Error('No se descargo un PDF real.');
if(!pdfPayload.html.includes('ASI_PEN-00000011')||pdfPayload.html.includes('ASI_PEN-00000012'))throw Error('El PDF no respeta la vista cerrada.');
await app.locator('#pendingOpenTab').click();
const openDownload=page.waitForEvent('download',{timeout:60000});await app.locator('#pdf').click();await openDownload;
if(!pdfPayload.html.includes('ASI_PEN-00000012')||!pdfPayload.html.includes('ASI_PEN-00000001')||pdfPayload.html.includes('ASI_PEN-00000011'))throw Error('El PDF no incluye pendientes y parciales juntos.');

await app.locator('[data-toggle="pending-7"]').click();
const alignedReversal=app.locator('tr.pending-reversal-row[data-parent="pending-7"]');await alignedReversal.waitFor();
if(await alignedReversal.locator('td').count()!==8)throw Error('La reversiÃ³n no quedÃ³ alineada con las columnas del asiento inicial.');
if(!(await alignedReversal.textContent()).includes('ASI_PEN-00000001'))throw Error('La reversiÃ³n no identifica claramente su asiento inicial.');
if(!(await alignedReversal.textContent()).includes('Cliente Uno'))throw Error('La reversiÃ³n no conserva el cliente o tercero del asiento inicial.');
await app.locator('[data-reverse-pending="7"]').click();await app.locator('#pendingReversalModal[open]').waitFor();
await app.locator('#pendingReversalType').selectOption('FACTURACION');await app.locator('#pendingInvoice option[value="9"]').waitFor({state:'attached'});if(!(await app.locator('#pendingInvoice').textContent()).includes('2026-09-08'))throw Error('La factura no muestra su fecha de emisión.');await app.locator('#pendingReversalDate').fill('2026-10-16');await app.locator('#pendingReversalDate').dispatchEvent('change');await app.locator('#pendingInvoice option').filter({hasText:/No hay facturas de este cliente en octubre de 2026/}).waitFor({state:'attached'});if(!requestedInvoiceDates.includes('2026-10-16'))throw Error('El cambio de fecha no volvió a filtrar las facturas por mes.');
await app.locator('#pendingReversalType').selectOption('ERROR_CORRECCION');if(await app.locator('#pendingErrorLabel').isHidden())throw Error('No apareciÃ³ el campo de justificaciÃ³n.');
if(await app.locator('#pendingSupportsPanel').isHidden())throw Error('No se muestran los respaldos para error/correcci?n.');
await app.locator('#pendingSupportFiles').setInputFiles({name:'respaldo.txt',mimeType:'text/plain',buffer:Buffer.from('Prueba')});
await app.getByRole('button',{name:'Quitar respaldo.txt',exact:true}).click();
if(await app.locator('#pendingSupportList li').count())throw Error('No se quit? el respaldo.');
await app.locator('#pendingSupportFiles').setInputFiles({name:'descartado.txt',mimeType:'text/plain',buffer:Buffer.from('Prueba')});
await app.locator('#pendingReversalType').selectOption('FACTURACION');
if(!(await app.locator('#pendingSupportsPanel').isHidden()))throw Error('Los respaldos aparecen para facturaci?n.');
await app.locator('#pendingReversalType').selectOption('ERROR_CORRECCION');
if(await app.locator('#pendingSupportList li').count())throw Error('No se limpiaron los respaldos al cambiar de tipo.');
await app.locator('#pendingSupportFiles').setInputFiles([{name:'respaldo.txt',mimeType:'text/plain',buffer:Buffer.from('Prueba')},{name:'respaldo2.txt',mimeType:'text/plain',buffer:Buffer.from('Otro')}]);
await app.locator('#pendingSupportLinkUrl').fill('javascript:alert(1)');
await app.locator('#addPendingSupportLink').click();
if(await app.locator('#pendingSupportList a').count())throw Error('Se acepto un enlace inseguro.');
await app.locator('#pendingSupportLinkName').fill('Documento de respaldo');
await app.locator('#pendingSupportLinkUrl').fill('https://example.com/respaldo');
await app.locator('#addPendingSupportLink').click();
if(await app.locator('#pendingSupportList a').getAttribute('href')!=='https://example.com/respaldo')throw Error('No se agrego el enlace.');
await app.locator('#pendingReversalAmount').fill('200');await app.locator('#pendingErrorDescription').fill('CorrecciÃ³n de estimaciÃ³n duplicada');const invalid=await app.locator('#pendingReversalForm').evaluate(form=>[...form.elements].filter(element=>element.willValidate&&!element.checkValidity()).map(element=>({id:element.id,message:element.validationMessage,value:element.value})));if(invalid.length)throw Error(`Formulario invÃ¡lido: ${JSON.stringify(invalid)}`);await app.locator('#pendingReversalForm button[type=submit]').click();
for(let attempt=0;attempt<20&&!reversalPayload;attempt++)await page.waitForTimeout(100);if(!reversalPayload||reversalPayload.type!=='ERROR_CORRECCION'||Number(reversalPayload.amount)!==200)throw Error(`El modal no enviÃ³ la reversiÃ³n esperada: ${await app.locator('#pendingReversalError').textContent()}`);
if(reversalPayload.supports?.length!==3||reversalPayload.supports.find(item=>item.support_type==='Enlace')?.support_url!=='https://example.com/respaldo'||reversalPayload.supports.find(item=>item.support_type==='Archivo')?.file_data!=='data:text/plain;base64,UHJ1ZWJh')throw Error('No se enviaron correctamente los respaldos.');
await app.locator('#pendingReversalSuccess[open]').waitFor();
if(await app.locator('#pendingSuccessNumber').textContent()!=='ASI_REV_PEN-00000002')throw Error('No se mostró el número del asiento generado.');
if(!(await app.locator('#pendingSuccessAmount').textContent()).includes('200'))throw Error('No se mostró el monto reversado.');
if(!(await app.locator('#pendingSuccessRemaining').textContent()).includes('550'))throw Error('No se mostró el saldo pendiente.');
if(!(await app.locator('#viewPendingSuccessJournal').getAttribute('href')).includes('/journal-view.html?id=10'))throw Error('El acceso al asiento generado es incorrecto.');
console.log(JSON.stringify({report:true,history:true,modal:true,dynamicReason:true,payload:true,successDialog:true,journalLink:true,statusTabs:true,directPdfDownload:true}));await browser.close();
