-- The journal report must show the entries that were actually posted to the
-- selected accounting book.  Tax counterparts are generated by
-- sync_journal_gl_impacts and therefore do not always exist in journal_line.
-- Reading only journal_line made valid sales and supplier documents appear
-- unbalanced even though their ledger posting was balanced.
create or replace function public.run_general_journal_report(
  p_filters jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  sids bigint[];
  date_from date;
  date_to date;
  book_id bigint;
  filter_department_id bigint;
  filter_location_id bigint;
  filter_class_id bigint;
  filter_cost_id bigint;
  filter_department_type text;
  module_filter text;
  status_filter text;
  search_text text;
  page_no int;
  page_size int;
  result jsonb;
begin
  select coalesce(array_agg(value::bigint),array[]::bigint[])
    into sids
  from jsonb_array_elements_text(coalesce(p_filters->'subsidiaryIds','[]'::jsonb));

  if cardinality(sids)=0 then
    sids:=array[active_subsidiary_id()];
  end if;
  if sids[1] is null or exists(
    select 1 from unnest(sids) selected_id
    where not exists(
      select 1 from user_subsidiaries access
      where access.user_id=app_user_id()
        and access.subsidiary_id=selected_id
    )
  ) then
    raise exception 'No tiene acceso a una o más subsidiarias seleccionadas.';
  end if;

  date_from:=nullif(p_filters->>'dateFrom','')::date;
  date_to:=nullif(p_filters->>'dateTo','')::date;
  if date_from is null or date_to is null then
    raise exception 'El rango de fechas es obligatorio.';
  end if;
  if date_from>date_to then
    raise exception 'El rango de fechas no es válido.';
  end if;

  book_id:=nullif(p_filters->>'bookId','')::bigint;
  filter_department_id:=nullif(p_filters->>'departmentId','')::bigint;
  filter_location_id:=nullif(p_filters->>'locationId','')::bigint;
  filter_class_id:=nullif(p_filters->>'classId','')::bigint;
  filter_cost_id:=nullif(p_filters->>'costCenterId','')::bigint;
  filter_department_type:=nullif(p_filters->>'departmentType','');
  module_filter:=nullif(p_filters->>'moduleCategory','');
  status_filter:=nullif(p_filters->>'journalStatus','');
  search_text:=lower(nullif(trim(p_filters->>'search'),''));
  page_no:=greatest(coalesce((p_filters->>'page')::int,1),1);
  page_size:=least(greatest(coalesce((p_filters->>'pageSize')::int,20),10),100);

  with journal_scope as materialized (
    select
      j.journal_id,j.journal_number,j.journal_date,j.transaction_id,
      j.subsidiary_id,j.exchange_rate,j.memo,j.status,
      report_book.accounting_book_id report_book_id,
      t.tran_number document_number,
      tt.code transaction_code,tt.abbreviation,tt.name transaction_type,
      tt.module_category,st.code transaction_status,
      coalesce(u.first_name||' '||u.last_name,u.email,'Sistema') created_by_name
    from journal j
    left join "transaction" t using(transaction_id)
    left join transaction_types tt using(transaction_type_id)
    left join status st on st.status_id=t.status_id
    left join users u on u.user_id=j.created_by
    left join lateral (
      select available_book.accounting_book_id
      from accounting_books available_book
      where available_book.subsidiary_id=j.subsidiary_id
        and available_book.is_active
      order by available_book.is_primary desc,available_book.accounting_book_id
      limit 1
    ) report_book on true
    where j.subsidiary_id=any(sids)
      and j.journal_date between date_from and date_to
      and (status_filter is null or j.status=status_filter)
      and (module_filter is null or tt.module_category=module_filter)
      and (
        book_id is null
        or exists(
          select 1 from gl_impact selected_book_impact
          where selected_book_impact.transaction_id=j.transaction_id
            and selected_book_impact.accounting_book_id=book_id
        )
      )
      -- Dimension filters select complete vouchers.  Returning only the
      -- matching side of an entry would itself create a false imbalance.
      and (filter_department_id is null or exists(
        select 1 from journal_line dimension_line
        where dimension_line.journal_id=j.journal_id
          and dimension_line.department_id=filter_department_id
      ))
      and (filter_location_id is null or exists(
        select 1 from journal_line dimension_line
        where dimension_line.journal_id=j.journal_id
          and dimension_line.location_id=filter_location_id
      ))
      and (filter_class_id is null or exists(
        select 1 from journal_line dimension_line
        where dimension_line.journal_id=j.journal_id
          and dimension_line.class_id=filter_class_id
      ))
      and (filter_cost_id is null or exists(
        select 1 from journal_line dimension_line
        where dimension_line.journal_id=j.journal_id
          and dimension_line.cost_center_id=filter_cost_id
      ))
      and (filter_department_type is null or exists(
        select 1
        from journal_line dimension_line
        join departments selected_department using(department_id)
        where dimension_line.journal_id=j.journal_id
          and lower(selected_department.type)=lower(filter_department_type)
      ))
      and (
        search_text is null
        or lower(j.journal_number) like '%'||search_text||'%'
        or lower(coalesce(t.tran_number,'')) like '%'||search_text||'%'
        or lower(coalesce(j.memo,'')) like '%'||search_text||'%'
        or exists(
          select 1
          from journal_line search_line
          left join customers c using(customer_id)
          left join suppliers sp using(supplier_id)
          left join employees e using(employee_id)
          where search_line.journal_id=j.journal_id
            and lower(concat_ws(' ',c.company_name,c.tax_id,sp.company_name,
              sp.tax_id,e.first_name,e.last_name,e.identification,
              search_line.note)) like '%'||search_text||'%'
        )
      )
  ), posted_lines as materialized (
    select
      scope.journal_id,
      impact.gl_impact_id sort_id,
      coalesce(direct_line.journal_line_id,tax_source.journal_line_id) line_id,
      impact.account_id,
      coalesce(direct_line.entity_type,tax_source.entity_type) entity_type,
      coalesce(direct_line.entity_name,tax_source.entity_name) entity_name,
      coalesce(direct_line.cost_center,tax_source.cost_center) cost_center,
      coalesce(
        direct_line.note,
        case when tax_source.tax_code is not null
          then 'Impuesto generado automáticamente · '||tax_source.tax_code
        end,
        'Movimiento contabilizado'
      ) note,
      impact.debit_amount debit,
      impact.credit_amount credit,
      direct_line.journal_line_id is null and tax_source.journal_line_id is not null
        as system_generated
    from journal_scope scope
    join gl_impact impact on impact.transaction_id=scope.transaction_id
      and impact.accounting_book_id=coalesce(book_id,scope.report_book_id)
    left join lateral (
      select
        line.journal_line_id,line.entity_type,
        coalesce(c.company_name,sp.company_name,concat_ws(' ',e.first_name,e.last_name)) entity_name,
        cc.code cost_center,line.note
      from journal_line line
      left join customers c using(customer_id)
      left join suppliers sp using(supplier_id)
      left join employees e using(employee_id)
      left join cost_centers cc using(cost_center_id)
      where line.journal_id=scope.journal_id
        and line.account_id=impact.account_id
        and abs(line.debit*scope.exchange_rate-impact.debit_amount)<0.0005
        and abs(line.credit*scope.exchange_rate-impact.credit_amount)<0.0005
      order by line.journal_line_id
      limit 1
    ) direct_line on true
    left join lateral (
      select
        line.journal_line_id,line.entity_type,
        coalesce(c.company_name,sp.company_name,concat_ws(' ',e.first_name,e.last_name)) entity_name,
        cc.code cost_center,line.note,tax_code.code_name tax_code
      from journal_line line
      join tax_codes tax_code using(tax_code_id)
      join tax_types tax_type using(tax_type_id)
      left join customers c using(customer_id)
      left join suppliers sp using(supplier_id)
      left join employees e using(employee_id)
      left join cost_centers cc using(cost_center_id)
      where direct_line.journal_line_id is null
        and line.journal_id=scope.journal_id
        and case when line.debit>0
          then tax_type.asset_account_id
          else tax_type.liability_account_id
        end=impact.account_id
        and abs(
          greatest(line.debit,line.credit)
          *coalesce(line.tax_rate,tax_code.rate_percentage,0)/100
          *scope.exchange_rate
          -greatest(impact.debit_amount,impact.credit_amount)
        )<0.0005
        and (line.debit>0)=(impact.debit_amount>0)
      order by line.journal_line_id
      limit 1
    ) tax_source on true
  ), fallback_lines as materialized (
    -- A draft/manual voucher without a ledger impact remains inspectable.  It
    -- is converted to local currency so the report keeps one monetary basis.
    select
      scope.journal_id,line.journal_line_id sort_id,line.journal_line_id,
      line.account_id,line.entity_type,
      coalesce(c.company_name,sp.company_name,concat_ws(' ',e.first_name,e.last_name)) entity_name,
      cc.code cost_center,line.note,
      line.debit*scope.exchange_rate debit,
      line.credit*scope.exchange_rate credit,
      false system_generated
    from journal_scope scope
    join journal_line line using(journal_id)
    left join customers c using(customer_id)
    left join suppliers sp using(supplier_id)
    left join employees e using(employee_id)
    left join cost_centers cc using(cost_center_id)
    where book_id is null
      and not exists(
        select 1 from gl_impact impact
        where impact.transaction_id=scope.transaction_id
          and impact.accounting_book_id=scope.report_book_id
      )
  ), report_lines as materialized (
    select * from posted_lines
    union all
    select * from fallback_lines
  ), journal_totals as materialized (
    select journal_id,coalesce(sum(debit),0) journal_debit,
      coalesce(sum(credit),0) journal_credit
    from report_lines
    group by journal_id
  ), eligible as materialized (
    select scope.*,totals.journal_debit,totals.journal_credit
    from journal_scope scope
    join journal_totals totals using(journal_id)
  ), counted as (
    select eligible.*,count(*) over() total_count
    from eligible
  ), paged as (
    select * from counted
    order by journal_date,journal_id
    limit page_size offset (page_no-1)*page_size
  )
  select jsonb_build_object(
    'rows',coalesce(jsonb_agg(jsonb_build_object(
      'journal_id',paged.journal_id,
      'journal_number',paged.journal_number,
      'status',paged.status,
      'date',paged.journal_date,
      'transaction_code',coalesce(paged.abbreviation,paged.transaction_code),
      'transaction_type',paged.transaction_type,
      'module_category',paged.module_category,
      'document_number',paged.document_number,
      'memo',paged.memo,
      'created_by',paged.created_by_name,
      'debit',paged.journal_debit,
      'credit',paged.journal_credit,
      'difference',paged.journal_debit-paged.journal_credit,
      'lines',coalesce((
        select jsonb_agg(jsonb_build_object(
          'line_id',line.line_id,
          'account_number',account.account_number,
          'account_name',account.account_name,
          'entity_type',line.entity_type,
          'entity_name',line.entity_name,
          'cost_center',line.cost_center,
          'note',line.note,
          'debit',line.debit,
          'credit',line.credit,
          'system_generated',line.system_generated
        ) order by line.sort_id)
        from report_lines line
        join chart_accounts account using(account_id)
        where line.journal_id=paged.journal_id
      ),'[]'::jsonb)
    ) order by paged.journal_date,paged.journal_id),'[]'::jsonb),
    'total',coalesce(max(paged.total_count),0),
    'page',page_no,
    'pageSize',page_size,
    'summary',jsonb_build_object(
      'debit',coalesce((select sum(journal_debit) from eligible),0),
      'credit',coalesce((select sum(journal_credit) from eligible),0)
    )
  ) into result
  from paged;

  return coalesce(result,jsonb_build_object(
    'rows','[]'::jsonb,
    'total',0,
    'page',page_no,
    'pageSize',page_size,
    'summary',jsonb_build_object('debit',0,'credit',0)
  ));
end
$$;

revoke all on function public.run_general_journal_report(jsonb) from public,anon;
grant execute on function public.run_general_journal_report(jsonb) to authenticated;
