alter table public.bank_transaction add column if not exists value_date date,add column if not exists reconciliation_status text not null default 'PENDIENTE_EN_TRANSITO',add column if not exists beneficiary text,add column if not exists description text;
alter table public.bank_transaction drop constraint if exists bank_transaction_reconciliation_status_allowed;
alter table public.bank_transaction add constraint bank_transaction_reconciliation_status_allowed check(reconciliation_status in('PENDIENTE_EN_TRANSITO','CONCILIADO'));
alter table public.bank_statement add column if not exists imported_at timestamptz not null default now(),add column if not exists source_file_name text;
alter table public.bank_reconciliation add column if not exists book_balance numeric(24,6),add column if not exists statement_balance numeric(24,6),add column if not exists transit_payments numeric(24,6) not null default 0,add column if not exists transit_deposits numeric(24,6) not null default 0,add column if not exists bank_adjustments numeric(24,6) not null default 0,add column if not exists difference numeric(24,6),add column if not exists closed_at timestamptz,add column if not exists closed_by bigint references public.users(user_id);

create table if not exists public.bank_statement_line(
 statement_line_id bigint generated always as identity primary key,statement_id bigint not null references public.bank_statement(statement_id) on delete cascade,
 bank_date date not null,value_date date,reference text,description text,beneficiary text,amount numeric(24,6) not null check(amount<>0),
 reconciliation_status text not null default 'PENDIENTE' check(reconciliation_status in('PENDIENTE','CONCILIADO')),source_row integer,
 unique(statement_id,source_row)
);
create table if not exists public.bank_reconciliation_match(
 match_id bigint generated always as identity primary key,reconciliation_id bigint not null references public.bank_reconciliation(reconciliation_id) on delete cascade,
 bank_tran_id bigint not null references public.bank_transaction(bank_tran_id),statement_line_id bigint not null references public.bank_statement_line(statement_line_id),
 match_type text not null check(match_type in('AUTOMATICO','MANUAL')),matched_at timestamptz not null default now(),matched_by bigint references public.users(user_id),
 unique(bank_tran_id),unique(statement_line_id)
);
create index if not exists bank_transaction_reconciliation_idx on public.bank_transaction(bank_account_id,tran_date,reconciliation_status,bank_tran_id);
create index if not exists bank_statement_line_match_idx on public.bank_statement_line(statement_id,bank_date,reconciliation_status,amount);
create index if not exists bank_reconciliation_close_idx on public.bank_reconciliation(bank_account_id,reconciliation_date,status);
alter table public.bank_statement_line enable row level security;alter table public.bank_reconciliation_match enable row level security;
drop policy if exists bank_statement_line_company_access on public.bank_statement_line;
create policy bank_statement_line_company_access on public.bank_statement_line for all to authenticated using(exists(select 1 from bank_statement bs join bank_account ba using(bank_account_id) join user_subsidiaries u using(subsidiary_id) where bs.statement_id=bank_statement_line.statement_id and u.user_id=app_user_id())) with check(exists(select 1 from bank_statement bs join bank_account ba using(bank_account_id) join user_subsidiaries u using(subsidiary_id) where bs.statement_id=bank_statement_line.statement_id and u.user_id=app_user_id()));
drop policy if exists bank_match_company_access on public.bank_reconciliation_match;
create policy bank_match_company_access on public.bank_reconciliation_match for all to authenticated using(exists(select 1 from bank_reconciliation br join bank_account ba using(bank_account_id) join user_subsidiaries u using(subsidiary_id) where br.reconciliation_id=bank_reconciliation_match.reconciliation_id and u.user_id=app_user_id())) with check(exists(select 1 from bank_reconciliation br join bank_account ba using(bank_account_id) join user_subsidiaries u using(subsidiary_id) where br.reconciliation_id=bank_reconciliation_match.reconciliation_id and u.user_id=app_user_id()));

create or replace function public.bank_reconciliation_options() returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('accounts',coalesce(jsonb_agg(jsonb_build_object('id',ba.bank_account_id,'number',ba.account_number,'name',b.bank_name||' - '||ba.account_number,'subsidiaryId',ba.subsidiary_id,'currencyId',ba.currency_id,'currencyCode',c.currency_code,'currencySymbol',c.symbol) order by b.bank_name,ba.account_number),'[]'::jsonb)) from bank_account ba join banks b using(bank_id) join currencies c using(currency_id) join user_subsidiaries u using(subsidiary_id) where u.user_id=app_user_id()$$;

create or replace function public.import_bank_statement(p_bank_account_id bigint,p_statement_date date,p_opening_balance numeric,p_closing_balance numeric,p_file_name text,p_lines jsonb)
returns bigint language plpgsql security definer set search_path=public as $$declare statement_key bigint;line jsonb;row_no int:=0;begin
 if not exists(select 1 from bank_account ba join user_subsidiaries u using(subsidiary_id) where ba.bank_account_id=p_bank_account_id and u.user_id=app_user_id()) then raise exception 'No tiene acceso a la cuenta bancaria.';end if;
 if exists(select 1 from bank_reconciliation where bank_account_id=p_bank_account_id and status='CERRADA' and reconciliation_date>=p_statement_date) then raise exception 'No se puede reemplazar un extracto incluido en una conciliación cerrada.';end if;
 insert into bank_statement(statement_date,bank_account_id,opening_balance,closing_balance,source_file_name) values(p_statement_date,p_bank_account_id,p_opening_balance,p_closing_balance,p_file_name) on conflict(statement_date,bank_account_id) do update set opening_balance=excluded.opening_balance,closing_balance=excluded.closing_balance,source_file_name=excluded.source_file_name,imported_at=now() returning statement_id into statement_key;
 delete from bank_statement_line where statement_id=statement_key;
 for line in select value from jsonb_array_elements(p_lines) loop row_no:=row_no+1;insert into bank_statement_line(statement_id,bank_date,value_date,reference,description,beneficiary,amount,source_row) values(statement_key,(line->>'date')::date,nullif(line->>'valueDate','')::date,nullif(line->>'reference',''),nullif(line->>'description',''),nullif(line->>'beneficiary',''),(line->>'amount')::numeric,row_no);end loop;
 return statement_key;end$$;

create or replace function public.run_bank_reconciliation_report(p_filters jsonb default '{}'::jsonb) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare account_key bigint;date_from date;date_to date;mode text;page_no int;page_size int;result jsonb;begin
 account_key:=nullif(p_filters->>'bankAccountId','')::bigint;date_from:=nullif(p_filters->>'dateFrom','')::date;date_to:=nullif(p_filters->>'dateTo','')::date;mode:=coalesce(nullif(p_filters->>'bankView',''),'AUXILIARY');page_no:=greatest(coalesce((p_filters->>'page')::int,1),1);page_size:=least(greatest(coalesce((p_filters->>'pageSize')::int,50),10),250);
 if account_key is null or not exists(select 1 from bank_account ba join user_subsidiaries u using(subsidiary_id) where ba.bank_account_id=account_key and u.user_id=app_user_id()) then raise exception 'Seleccione una cuenta bancaria autorizada.';end if;if date_from is null or date_to is null then raise exception 'El rango de fechas es obligatorio.';end if;
 with movements as(select bt.bank_tran_id id,bt.tran_date date,coalesce(bt.value_date,bt.tran_date) value_date,bt.reconciliation_status,coalesce(tt.abbreviation,bt.tran_type) transaction_type,coalesce(bt.reference_number,t.tran_number) reference,coalesce(bt.beneficiary,c.company_name,s.company_name,e.first_name||' '||e.last_name,'—') beneficiary,coalesce(bt.description,tt.name,bt.tran_type) description,greatest(bt.amount,0) deposits,greatest(-bt.amount,0) withdrawals,
  coalesce((select sum(previous.amount) from bank_transaction previous where previous.bank_account_id=account_key and (previous.tran_date<bt.tran_date or previous.tran_date=bt.tran_date and previous.bank_tran_id<=bt.bank_tran_id)),0) running_balance,count(*) over() total_count
  from bank_transaction bt left join "transaction" t using(transaction_id) left join transaction_types tt using(transaction_type_id) left join customers c on c.customer_id=t.customer_id left join suppliers s on s.supplier_id=t.supplier_id left join journal j using(transaction_id) left join journal_line jl on jl.journal_id=j.journal_id left join employees e using(employee_id)
  where bt.bank_account_id=account_key and bt.tran_date between date_from and date_to group by bt.bank_tran_id,tt.abbreviation,tt.name,t.tran_number,c.company_name,s.company_name,e.first_name,e.last_name),paged as(select * from movements order by date,id limit page_size offset(page_no-1)*page_size),latest_statement as(select * from bank_statement where bank_account_id=account_key and statement_date<=date_to order by statement_date desc limit 1),latest_reconciliation as(select * from bank_reconciliation where bank_account_id=account_key and reconciliation_date<=date_to order by reconciliation_date desc limit 1)
 select jsonb_build_object('rows',coalesce((select jsonb_agg(to_jsonb(p)-'total_count') from paged p),'[]'::jsonb),'total',coalesce((select max(total_count) from movements),0),'page',page_no,'pageSize',page_size,'statementLines',coalesce((select jsonb_agg(to_jsonb(sl) order by sl.bank_date,sl.statement_line_id) from latest_statement bs join bank_statement_line sl using(statement_id)),'[]'::jsonb),'reconciliation',coalesce((select to_jsonb(r) from latest_reconciliation r),'{}'::jsonb),'summary',jsonb_build_object('bookBalance',coalesce((select sum(amount) from bank_transaction where bank_account_id=account_key and tran_date<=date_to),0),'statementBalance',coalesce((select closing_balance from latest_statement),0),'transitPayments',coalesce((select sum(withdrawals) from movements where reconciliation_status='PENDIENTE_EN_TRANSITO'),0),'transitDeposits',coalesce((select sum(deposits) from movements where reconciliation_status='PENDIENTE_EN_TRANSITO'),0))) into result;
 return result;end$$;

create or replace function public.auto_match_bank_reconciliation(p_bank_account_id bigint,p_cutoff date) returns integer language plpgsql security definer set search_path=public as $$declare rec_id bigint;matched integer:=0;r record;begin
 if not exists(select 1 from bank_account ba join user_subsidiaries u using(subsidiary_id) where ba.bank_account_id=p_bank_account_id and u.user_id=app_user_id()) then raise exception 'No tiene acceso a la cuenta bancaria.';end if;
 select reconciliation_id into rec_id from bank_reconciliation where bank_account_id=p_bank_account_id and reconciliation_date=p_cutoff;if rec_id is null then insert into bank_reconciliation(reconciliation_date,bank_account_id,fiscal_period_id,status) select p_cutoff,p_bank_account_id,fp.fiscal_period_id,'ABIERTA' from bank_account ba join fiscal_periods fp on fp.subsidiary_id=ba.subsidiary_id and p_cutoff between fp.start_date and fp.end_date where ba.bank_account_id=p_bank_account_id limit 1 returning reconciliation_id into rec_id;end if;
 if exists(select 1 from bank_reconciliation where reconciliation_id=rec_id and status='CERRADA') then raise exception 'La conciliación está cerrada.';end if;
 for r in select bt.bank_tran_id,sl.statement_line_id from bank_transaction bt join bank_statement bs on bs.bank_account_id=bt.bank_account_id and bs.statement_date=p_cutoff join bank_statement_line sl using(statement_id) where bt.bank_account_id=p_bank_account_id and bt.tran_date<=p_cutoff and bt.reconciliation_status<>'CONCILIADO' and sl.reconciliation_status<>'CONCILIADO' and abs(bt.amount-sl.amount)<.005 and abs(bt.tran_date-sl.bank_date)<=3 and coalesce(lower(bt.reference_number),'')=coalesce(lower(sl.reference),'') loop insert into bank_reconciliation_match(reconciliation_id,bank_tran_id,statement_line_id,match_type,matched_by) values(rec_id,r.bank_tran_id,r.statement_line_id,'AUTOMATICO',app_user_id()) on conflict do nothing;if found then update bank_transaction set reconciliation_status='CONCILIADO',value_date=(select bank_date from bank_statement_line where statement_line_id=r.statement_line_id) where bank_tran_id=r.bank_tran_id;update bank_statement_line set reconciliation_status='CONCILIADO' where statement_line_id=r.statement_line_id;matched:=matched+1;end if;end loop;return matched;end$$;

create or replace function public.match_bank_transaction(p_bank_tran_id bigint,p_statement_line_id bigint,p_cutoff date) returns bigint language plpgsql security definer set search_path=public as $$declare rec_id bigint;account_key bigint;new_id bigint;begin select bank_account_id into account_key from bank_transaction where bank_tran_id=p_bank_tran_id;if not exists(select 1 from bank_account ba join user_subsidiaries u using(subsidiary_id) where ba.bank_account_id=account_key and u.user_id=app_user_id()) then raise exception 'No tiene acceso.';end if;if not exists(select 1 from bank_statement_line sl join bank_statement bs using(statement_id) where sl.statement_line_id=p_statement_line_id and bs.bank_account_id=account_key) then raise exception 'El movimiento del extracto pertenece a otra cuenta bancaria.';end if;select reconciliation_id into rec_id from bank_reconciliation where bank_account_id=account_key and reconciliation_date=p_cutoff;if rec_id is null then insert into bank_reconciliation(reconciliation_date,bank_account_id,fiscal_period_id,status) select p_cutoff,account_key,fp.fiscal_period_id,'ABIERTA' from bank_account ba join fiscal_periods fp on fp.subsidiary_id=ba.subsidiary_id and p_cutoff between fp.start_date and fp.end_date where ba.bank_account_id=account_key limit 1 returning reconciliation_id into rec_id;end if;if exists(select 1 from bank_reconciliation where reconciliation_id=rec_id and status='CERRADA') then raise exception 'La conciliación está cerrada.';end if;insert into bank_reconciliation_match(reconciliation_id,bank_tran_id,statement_line_id,match_type,matched_by) values(rec_id,p_bank_tran_id,p_statement_line_id,'MANUAL',app_user_id()) returning match_id into new_id;update bank_transaction set reconciliation_status='CONCILIADO',value_date=(select bank_date from bank_statement_line where statement_line_id=p_statement_line_id) where bank_tran_id=p_bank_tran_id;update bank_statement_line set reconciliation_status='CONCILIADO' where statement_line_id=p_statement_line_id;return new_id;end$$;

create or replace function public.close_bank_reconciliation(p_bank_account_id bigint,p_cutoff date,p_bank_adjustments numeric default 0) returns bigint language plpgsql security definer set search_path=public as $$declare rec_id bigint;books numeric;statement numeric;checks numeric;deposits numeric;diff numeric;begin perform auto_match_bank_reconciliation(p_bank_account_id,p_cutoff);select reconciliation_id into rec_id from bank_reconciliation where bank_account_id=p_bank_account_id and reconciliation_date=p_cutoff for update;select coalesce(sum(amount),0) into books from bank_transaction where bank_account_id=p_bank_account_id and tran_date<=p_cutoff;select closing_balance into statement from bank_statement where bank_account_id=p_bank_account_id and statement_date=p_cutoff;select coalesce(sum(greatest(-amount,0)),0),coalesce(sum(greatest(amount,0)),0) into checks,deposits from bank_transaction where bank_account_id=p_bank_account_id and tran_date<=p_cutoff and reconciliation_status='PENDIENTE_EN_TRANSITO';diff:=(books+checks-deposits+p_bank_adjustments)-coalesce(statement,0);if abs(diff)>=.005 then raise exception 'No se puede cerrar: existe un descuadre de %.',diff;end if;update bank_reconciliation set status='CERRADA',book_balance=books,statement_balance=statement,transit_payments=checks,transit_deposits=deposits,bank_adjustments=p_bank_adjustments,difference=diff,closed_at=now(),closed_by=app_user_id() where reconciliation_id=rec_id;return rec_id;end$$;

create or replace function public.prevent_closed_bank_changes() returns trigger language plpgsql security definer set search_path=public as $$declare account_key bigint;movement_date date;begin account_key:=old.bank_account_id;movement_date:=old.tran_date;if exists(select 1 from bank_reconciliation where bank_account_id=account_key and status='CERRADA' and reconciliation_date>=movement_date) then raise exception 'El movimiento pertenece a una conciliación bancaria cerrada y no puede modificarse.';end if;if tg_op='DELETE' then return old;end if;return new;end$$;
drop trigger if exists prevent_closed_bank_transaction_changes on public.bank_transaction;create trigger prevent_closed_bank_transaction_changes before update or delete on public.bank_transaction for each row execute function public.prevent_closed_bank_changes();

create or replace function public.prevent_closed_bank_origin_changes() returns trigger language plpgsql security definer set search_path=public as $$declare transaction_key bigint;begin transaction_key:=case when tg_table_name='journal' then old.transaction_id else old.transaction_id end;if exists(select 1 from bank_transaction bt join bank_reconciliation br using(bank_account_id) where bt.transaction_id=transaction_key and br.status='CERRADA' and br.reconciliation_date>=bt.tran_date) then raise exception 'La transacción pertenece a una conciliación bancaria cerrada y no puede modificarse ni anularse.';end if;if tg_op='DELETE' then return old;end if;return new;end$$;
drop trigger if exists prevent_closed_transaction_origin_changes on public."transaction";create trigger prevent_closed_transaction_origin_changes before update or delete on public."transaction" for each row execute function public.prevent_closed_bank_origin_changes();
drop trigger if exists prevent_closed_journal_origin_changes on public.journal;create trigger prevent_closed_journal_origin_changes before update or delete on public.journal for each row execute function public.prevent_closed_bank_origin_changes();

grant select,insert,update,delete on bank_statement_line,bank_reconciliation_match to authenticated;grant usage,select on sequence bank_statement_line_statement_line_id_seq,bank_reconciliation_match_match_id_seq to authenticated;grant execute on function public.bank_reconciliation_options(),public.import_bank_statement(bigint,date,numeric,numeric,text,jsonb),public.run_bank_reconciliation_report(jsonb),public.auto_match_bank_reconciliation(bigint,date),public.match_bank_transaction(bigint,bigint,date),public.close_bank_reconciliation(bigint,date,numeric) to authenticated;
