create or replace function public.bank_reconciliation_close_report(p_bank_account_id bigint,p_cutoff date)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare rec bank_reconciliation%rowtype;period_row fiscal_periods%rowtype;account_row record;closer record;creator record;result jsonb;
begin
 select r.*into rec from bank_reconciliation r join bank_account ba using(bank_account_id)join user_subsidiaries us using(subsidiary_id)where r.bank_account_id=p_bank_account_id and r.reconciliation_date=p_cutoff and r.status='CERRADA'and us.user_id=app_user_id();
 if rec.reconciliation_id is null then raise exception'No existe una conciliación cerrada para la cuenta y fecha seleccionadas.';end if;
 select*into period_row from fiscal_periods where fiscal_period_id=rec.fiscal_period_id;
 select ba.account_number,b.bank_name,c.currency_code,c.name currency_name,c.symbol,s.name subsidiary,s.legal_name,s.tax_id,s.logo_url into account_row from bank_account ba join banks b using(bank_id)join currencies c using(currency_id)join subsidiaries s using(subsidiary_id)where ba.bank_account_id=p_bank_account_id;
 select coalesce(nullif(concat_ws(' ',u.first_name,u.last_name),''),u.email,'Sistema')name,coalesce(e.job_title,'No registrado')title into closer from users u left join employees e on e.user_id=u.user_id and e.is_active where u.user_id=rec.closed_by limit 1;
 select coalesce(nullif(rec.created_by_name,''),'Proceso de sistema')name,coalesce(e.job_title,'No registrado')title,rec.closed_at created_at into creator from employees e right join users u on u.user_id=e.user_id and e.is_active where u.user_id::text=rec.created_by_id limit 1;
 if creator.name is null then creator.name:=coalesce(nullif(rec.created_by_name,''),'Proceso de sistema');creator.title:='No registrado';creator.created_at:=rec.closed_at;end if;
 select jsonb_build_object(
  'header',jsonb_build_object('reconciliationId',rec.reconciliation_id,'code','CON-BAN-'||lpad(rec.reconciliation_id::text,8,'0'),'subsidiary',account_row.subsidiary,'legalName',account_row.legal_name,'taxId',account_row.tax_id,'logoUrl',coalesce(account_row.logo_url,''),'bank',account_row.bank_name,'account',account_row.account_number,'currency',account_row.currency_code,'currencyName',account_row.currency_name,'symbol',account_row.symbol,'period',period_row.period_name,'periodStart',period_row.start_date,'periodEnd',least(period_row.end_date,rec.reconciliation_date),'cutoff',rec.reconciliation_date,'issuedAt',now(),'createdAt',creator.created_at,'createdBy',creator.name,'createdByTitle',creator.title,'closedAt',rec.closed_at,'closedBy',coalesce(closer.name,'Sistema'),'closedByTitle',coalesce(closer.title,'No registrado'),'status',rec.status),
  'summary',jsonb_build_object('openingBalance',coalesce((select sum(bt.amount)from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date<period_row.start_date),0),'entries',coalesce((select sum(greatest(bt.amount,0))from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),0),'exits',coalesce((select sum(greatest(-bt.amount,0))from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),0),'transitEntries',coalesce(rec.transit_deposits,0),'transitExits',coalesce(rec.transit_payments,0),'adjustments',coalesce(rec.bank_adjustments,0),'bookBalance',coalesce(rec.book_balance,0),'reconciledBookBalance',coalesce(rec.book_balance,0)+coalesce(rec.transit_payments,0)-coalesce(rec.transit_deposits,0)+coalesce(rec.bank_adjustments,0),'statementBalance',coalesce(rec.statement_balance,0),'difference',coalesce(rec.difference,0)),
  'movements',coalesce((select jsonb_agg(jsonb_build_object('id',bt.bank_tran_id,'date',bt.tran_date,'valueDate',coalesce(bt.value_date,bt.tran_date),'type',coalesce(tt.abbreviation,bt.tran_type),'reference',coalesce(bt.reference_number,t.tran_number),'beneficiary',coalesce(bt.beneficiary,cu.company_name,sp.company_name,'—'),'note',coalesce(nullif(j.memo,''),notes.line_notes,nullif(bt.description,''),'Sin nota registrada'),'entry',greatest(bt.amount,0),'exit',greatest(-bt.amount,0),'status',bt.reconciliation_status)order by bt.tran_date,bt.bank_tran_id)from bank_transaction bt left join"transaction"t using(transaction_id)left join transaction_types tt using(transaction_type_id)left join customers cu on cu.customer_id=t.customer_id left join suppliers sp on sp.supplier_id=t.supplier_id left join journal j using(transaction_id)left join lateral(select string_agg(distinct nullif(trim(jl.note),''),' · ')line_notes from journal_line jl where jl.journal_id=j.journal_id)notes on true where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),'[]'::jsonb),
  'pendingBankMovements',coalesce((select jsonb_agg(jsonb_build_object('id',bt.bank_tran_id,'date',bt.tran_date,'type',bt.tran_type,'reference',bt.reference_number,'beneficiary',coalesce(bt.beneficiary,'—'),'concept',coalesce(nullif(bt.description,''),'Sin nota registrada'),'amount',bt.amount)order by bt.tran_date,bt.bank_tran_id)from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date<=rec.reconciliation_date and bt.reconciliation_status='PENDIENTE_EN_TRANSITO'),'[]'::jsonb),
  'pendingBookMovements',coalesce((select jsonb_agg(jsonb_build_object('id',sl.statement_line_id,'date',sl.bank_date,'type',case when sl.amount>=0 then'CRÉDITO BANCARIO'else'DÉBITO BANCARIO'end,'reference',sl.reference,'beneficiary',coalesce(sl.beneficiary,'—'),'concept',coalesce(nullif(sl.description,''),'Sin nota en el extracto'),'amount',sl.amount)order by sl.bank_date,sl.statement_line_id)from bank_statement bs join bank_statement_line sl using(statement_id)where bs.bank_account_id=p_bank_account_id and bs.statement_date=rec.reconciliation_date and sl.reconciliation_status<>'CONCILIADO'),'[]'::jsonb)
 )into result;return result;
end$$;
revoke all on function public.bank_reconciliation_close_report(bigint,date)from public,anon;
grant execute on function public.bank_reconciliation_close_report(bigint,date)to authenticated;
notify pgrst,'reload schema';
