insert into transaction_types(abbreviation,name,module_category,description) select 'CHQ_TRF','Cheque o Transferencia','Bancos y Tesorería','Salida bancaria mediante cheque o transferencia a terceros.' where not exists(select 1 from transaction_types where abbreviation='CHQ_TRF');
alter table bank_check add column if not exists payment_type text,add column if not exists bank_reference text,add column if not exists payment_date date,add column if not exists subsidiary_id bigint references subsidiaries(subsidiary_id),add column if not exists currency_id bigint references currencies(currency_id),add column if not exists exchange_rate numeric(24,10),add column if not exists fiscal_period_id bigint references fiscal_periods(fiscal_period_id),add column if not exists location_id bigint references locations(location_id),add column if not exists beneficiary text,add column if not exists memo text,add column if not exists journal_id bigint references journal(journal_id),add column if not exists transaction_id bigint references "transaction"(transaction_id),add column if not exists created_by bigint references users(user_id),add column if not exists created_at timestamptz not null default now();
alter table bank_check drop constraint if exists bank_check_payment_type_allowed;alter table bank_check add constraint bank_check_payment_type_allowed check(payment_type is null or payment_type in('CHEQUE','TRANSFERENCIA'));
create table if not exists bank_check_line(check_line_id bigint generated always as identity primary key,check_id bigint not null references bank_check(check_id) on delete cascade,line_number int not null,amount numeric(24,6) not null check(amount>0),account_id bigint not null references chart_accounts(account_id),entity_type text,customer_id bigint references customers(customer_id),supplier_id bigint references suppliers(supplier_id),employee_id bigint references employees(employee_id),department_id bigint references departments(department_id),cost_center_id bigint references cost_centers(cost_center_id),class_id bigint references classes(class_id),financial_creditor_id bigint references financial_creditors(financial_creditor_id),related_company_id bigint references related_companies(related_company_id),note text,unique(check_id,line_number));
alter table bank_check_line enable row level security;drop policy if exists bank_check_line_access on bank_check_line;create policy bank_check_line_access on bank_check_line for select to authenticated using(exists(select 1 from bank_check h where h.check_id=bank_check_line.check_id and h.subsidiary_id=active_subsidiary_id()));
create index if not exists bank_check_report_idx on bank_check(subsidiary_id,payment_date,payment_type,status);

create or replace function bank_check_options() returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('subsidiary',jsonb_build_object('id',s.subsidiary_id,'name',s.name,'currencyId',s.currency_id),'location',(select jsonb_build_object('id',l.location_id,'name',l.name) from locations l where l.subsidiary_id=s.subsidiary_id order by l.location_id limit 1),'accounts',coalesce((select jsonb_agg(jsonb_build_object('id',ba.bank_account_id,'bankId',b.bank_id,'bankName',b.bank_name,'number',ba.account_number,'currencyId',ba.currency_id,'currencyCode',c.currency_code,'ledgerAccountId',ba.account_id,'balance',ba.balance) order by b.bank_name,ba.account_number) from bank_account ba join banks b using(bank_id) join currencies c using(currency_id) where ba.subsidiary_id=s.subsidiary_id and not coalesce(ba.is_credit_card,false)),'[]'::jsonb)) from subsidiaries s where s.subsidiary_id=active_subsidiary_id()$$;

create or replace function save_bank_check_transfer(p_payload jsonb,p_check_id bigint default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare sid bigint:=active_subsidiary_id();uid bigint:=app_user_id();old bank_check%rowtype;ba bank_account%rowtype;kind text:=upper(p_payload->>'payment_type');d date:=(p_payload->>'payment_date')::date;rate numeric:=(p_payload->>'exchange_rate')::numeric;period_key bigint:=(p_payload->>'fiscal_period_id')::bigint;location_key bigint:=nullif(p_payload->>'location_id','')::bigint;line jsonb;total numeric:=0;n int:=0;tt bigint;st bigint;num text;tid bigint;jid bigint;hid bigint;entity_kind text;entity_key bigint;
begin
 if kind not in('CHEQUE','TRANSFERENCIA') then raise exception 'Seleccione ingresar si es Cheque o Transferencia.';end if;if d is null or rate<=0 then raise exception 'Fecha y tipo de cambio son obligatorios.';end if;
 select * into ba from bank_account where bank_account_id=(p_payload->>'bank_account_id')::bigint and subsidiary_id=sid for update;if ba.bank_account_id is null then raise exception 'Seleccione una cuenta bancaria de la subsidiaria.';end if;if ba.currency_id<>(p_payload->>'currency_id')::bigint then raise exception 'La moneda no corresponde a la cuenta bancaria.';end if;
 if kind='CHEQUE' and nullif(trim(p_payload->>'bank_reference'),'') is null then raise exception 'Ingrese el número de cheque.';end if;if kind='TRANSFERENCIA' and nullif(trim(p_payload->>'bank_reference'),'') is null then raise exception 'Ingrese la referencia bancaria.';end if;
 if not exists(select 1 from fiscal_periods where fiscal_period_id=period_key and subsidiary_id=sid and d between start_date and end_date and not is_closed) then raise exception 'No existe período contable abierto para la fecha.';end if;
 for line in select value from jsonb_array_elements(coalesce(p_payload->'lines','[]')) loop if coalesce((line->>'amount')::numeric,0)<=0 or nullif(line->>'account_id','') is null then raise exception 'Cada línea requiere importe y cuenta contable.';end if;total:=total+(line->>'amount')::numeric;end loop;if total<=0 then raise exception 'Agregue al menos una línea.';end if;
 if p_check_id is null then
  if ba.balance<total then raise exception 'Saldo insuficiente: disponible %, requerido %.',round(ba.balance,2),round(total,2);end if;select transaction_type_id into tt from transaction_types where abbreviation='CHQ_TRF';select status_id into st from status where code='APROBADO' and module='Transacciones' limit 1;begin num:=next_transaction_number(tt,sid);exception when others then num:='CHQ_TRF-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');end;
  insert into "transaction"(tran_number,tran_date,transaction_type_id,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,total_amount,status_id)values(num,d,tt,sid,ba.currency_id,rate,period_key,total,st)returning transaction_id into tid;insert into journal(journal_number,journal_date,transaction_id,subsidiary_id,currency_id,fiscal_period_id,exchange_rate,memo,journal_type,location_id,total_debit,total_credit,status)values(num,d,tid,sid,ba.currency_id,period_key,rate,nullif(p_payload->>'memo',''),kind,location_key,total,total,'CONTABILIZADO')returning journal_id into jid;insert into bank_check(check_number,bank_account_id,amount,status,payment_type,bank_reference,payment_date,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,location_id,beneficiary,memo,journal_id,transaction_id,created_by)values(num,ba.bank_account_id,total,'APROBADA',kind,nullif(p_payload->>'bank_reference',''),d,sid,ba.currency_id,rate,period_key,location_key,nullif(p_payload->>'beneficiary',''),nullif(p_payload->>'memo',''),jid,tid,uid)returning check_id into hid;
 else
  select * into old from bank_check where check_id=p_check_id and subsidiary_id=sid for update;if old.check_id is null then raise exception 'No se encontró la transacción.';end if;if ba.balance+old.amount<total then raise exception 'Saldo insuficiente para actualizar.';end if;hid:=old.check_id;num:=old.check_number;tid:=old.transaction_id;jid:=old.journal_id;update bank_account set balance=balance+old.amount where bank_account_id=old.bank_account_id;delete from bank_check_line where check_id=hid;delete from journal_line where journal_id=jid;update "transaction" set tran_date=d,currency_id=ba.currency_id,exchange_rate=rate,fiscal_period_id=period_key,total_amount=total where transaction_id=tid;update journal set journal_date=d,currency_id=ba.currency_id,exchange_rate=rate,fiscal_period_id=period_key,memo=nullif(p_payload->>'memo',''),journal_type=kind,location_id=location_key,total_debit=total,total_credit=total where journal_id=jid;update bank_check set bank_account_id=ba.bank_account_id,amount=total,payment_type=kind,bank_reference=nullif(p_payload->>'bank_reference',''),payment_date=d,currency_id=ba.currency_id,exchange_rate=rate,fiscal_period_id=period_key,location_id=location_key,beneficiary=nullif(p_payload->>'beneficiary',''),memo=nullif(p_payload->>'memo','') where check_id=hid;update bank_transaction set tran_date=d,value_date=d,bank_account_id=ba.bank_account_id,amount=-total,reference_number=p_payload->>'bank_reference',description=coalesce(nullif(p_payload->>'memo',''),kind) where transaction_id=tid;
 end if;
 insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,location_id,note)values(jid,ba.account_id,0,total,0,total*rate,location_key,coalesce(nullif(p_payload->>'memo',''),kind));
 for line in select value from jsonb_array_elements(p_payload->'lines') loop n:=n+1;entity_kind:=nullif(line->>'entity_type','');entity_key:=nullif(line->>'entity_id','')::bigint;insert into bank_check_line(check_id,line_number,amount,account_id,entity_type,customer_id,supplier_id,employee_id,department_id,cost_center_id,class_id,financial_creditor_id,related_company_id,note)values(hid,n,(line->>'amount')::numeric,(line->>'account_id')::bigint,entity_kind,case when entity_kind='Cliente' then entity_key end,case when entity_kind='Proveedor' then entity_key end,case when entity_kind='Empleado' then entity_key end,nullif(line->>'department_id','')::bigint,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'class_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint,nullif(line->>'note',''));insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,department_id,class_id,location_id,note,entity_type,customer_id,supplier_id,employee_id,cost_center_id,financial_creditor_id,related_company_id)values(jid,(line->>'account_id')::bigint,(line->>'amount')::numeric,0,(line->>'amount')::numeric*rate,0,nullif(line->>'department_id','')::bigint,nullif(line->>'class_id','')::bigint,location_key,nullif(line->>'note',''),entity_kind,case when entity_kind='Cliente' then entity_key end,case when entity_kind='Proveedor' then entity_key end,case when entity_kind='Empleado' then entity_key end,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint);end loop;
 if p_check_id is null then insert into bank_transaction(tran_date,value_date,bank_account_id,transaction_id,amount,tran_type,reference_number,description,beneficiary,reconciliation_status)values(d,d,ba.bank_account_id,tid,-total,kind,p_payload->>'bank_reference',coalesce(nullif(p_payload->>'memo',''),kind),nullif(p_payload->>'beneficiary',''),'PENDIENTE_EN_TRANSITO');end if;update bank_account set balance=balance-total where bank_account_id=ba.bank_account_id;return jsonb_build_object('checkId',hid,'transactionNumber',num,'journalId',jid,'total',total);
end$$;

create or replace function bank_check_report(p_filters jsonb default '{}')returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',h.check_id,'number',h.check_number,'type',h.payment_type,'reference',h.bank_reference,'date',h.payment_date,'bank',b.bank_name,'account',ba.account_number,'currency',c.currency_code,'beneficiary',h.beneficiary,'amount',h.amount,'status',h.status,'memo',h.memo)order by h.payment_date desc,h.check_id desc),'[]'::jsonb))from bank_check h join bank_account ba using(bank_account_id)join banks b using(bank_id)join currencies c on c.currency_id=h.currency_id where h.subsidiary_id=active_subsidiary_id()and h.payment_date between coalesce(nullif(p_filters->>'dateFrom','')::date,date_trunc('month',current_date)::date)and coalesce(nullif(p_filters->>'dateTo','')::date,current_date)and(nullif(p_filters->>'type','')is null or h.payment_type=p_filters->>'type')and(nullif(p_filters->>'accountId','')is null or h.bank_account_id=(p_filters->>'accountId')::bigint)and(nullif(trim(p_filters->>'search'),'')is null or concat_ws(' ',h.check_number,h.bank_reference,h.beneficiary,h.memo,b.bank_name,ba.account_number)ilike'%'||trim(p_filters->>'search')||'%')$$;
create or replace function bank_check_detail(p_check_id bigint)returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('header',to_jsonb(h)||jsonb_build_object('bankName',b.bank_name,'accountNumber',ba.account_number,'currencyCode',c.currency_code,'currencyName',c.name,'subsidiaryName',s.name,'locationName',l.name),'lines',coalesce((select jsonb_agg(to_jsonb(x)order by line_number)from bank_check_line x where x.check_id=h.check_id),'[]'),'impact',coalesce((select jsonb_agg(to_jsonb(jl)||jsonb_build_object('accountNumber',ca.account_number,'accountName',ca.account_name)order by journal_line_id)from journal_line jl join chart_accounts ca using(account_id)where jl.journal_id=h.journal_id),'[]'))from bank_check h join bank_account ba using(bank_account_id)join banks b using(bank_id)join currencies c on c.currency_id=h.currency_id join subsidiaries s on s.subsidiary_id=h.subsidiary_id left join locations l on l.location_id=h.location_id where h.check_id=p_check_id and h.subsidiary_id=active_subsidiary_id()$$;
create or replace function delete_bank_check_transfer(p_check_id bigint)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare h bank_check%rowtype;begin select * into h from bank_check where check_id=p_check_id and subsidiary_id=active_subsidiary_id()for update;if h.check_id is null then raise exception 'No se encontró la transacción.';end if;update bank_account set balance=balance+h.amount where bank_account_id=h.bank_account_id;delete from bank_transaction where transaction_id=h.transaction_id;delete from bank_check_line where check_id=h.check_id;delete from bank_check where check_id=h.check_id;delete from journal_support where journal_id=h.journal_id;delete from journal_line where journal_id=h.journal_id;delete from journal where journal_id=h.journal_id;delete from "transaction" where transaction_id=h.transaction_id;return jsonb_build_object('success',true,'number',h.check_number);end$$;
revoke all on function bank_check_options(),save_bank_check_transfer(jsonb,bigint),bank_check_report(jsonb),bank_check_detail(bigint),delete_bank_check_transfer(bigint) from public,anon;grant execute on function bank_check_options(),save_bank_check_transfer(jsonb,bigint),bank_check_report(jsonb),bank_check_detail(bigint),delete_bank_check_transfer(bigint) to authenticated;notify pgrst,'reload schema';
