create table if not exists public.purchase_requisition(requisition_id bigint generated always as identity primary key,requisition_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,employee_id bigint not null references public.employees(employee_id),subsidiary_id bigint not null references public.subsidiaries(subsidiary_id),status_id bigint not null references public.status(status_id));
create table if not exists public.purchase_quote(quote_id bigint generated always as identity primary key,quote_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),valid_until date not null);
create table if not exists public.purchase_order(po_id bigint generated always as identity primary key,po_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),subsidiary_id bigint not null references public.subsidiaries(subsidiary_id),currency_id bigint not null references public.currencies(currency_id),status_id bigint not null references public.status(status_id));
create table if not exists public.goods_receipt(receipt_id bigint generated always as identity primary key,receipt_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,po_id bigint not null references public.purchase_order(po_id),location_id bigint not null references public.locations(location_id),receipt_date date not null);
create table if not exists public.supplier_invoice(invoice_id bigint generated always as identity primary key,invoice_number text not null,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),po_id bigint references public.purchase_order(po_id),subsidiary_id bigint not null references public.subsidiaries(subsidiary_id),due_date date not null,total_amount numeric(24,6) not null check(total_amount>=0),unique(invoice_number,supplier_id));
create table if not exists public.supplier_payment(payment_id bigint generated always as identity primary key,payment_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),bank_account_id bigint not null references public.bank_account(bank_account_id),payment_date date not null,amount_paid numeric(24,6) not null check(amount_paid>0));
create table if not exists public.supplier_credit_note(cn_id bigint generated always as identity primary key,cn_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),invoice_id bigint not null references public.supplier_invoice(invoice_id),amount numeric(24,6) not null check(amount>0));
create table if not exists public.supplier_debit_note(dn_id bigint generated always as identity primary key,dn_number text not null unique,transaction_id bigint references public."transaction"(transaction_id) on delete set null,supplier_id bigint not null references public.suppliers(supplier_id),invoice_id bigint not null references public.supplier_invoice(invoice_id),amount numeric(24,6) not null check(amount>0));
do $$declare t text;begin foreach t in array array['purchase_requisition','purchase_quote','purchase_order','goods_receipt','supplier_invoice','supplier_payment','supplier_credit_note','supplier_debit_note']loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists "purchasing_select" on public.%I',t);execute format('drop policy if exists "purchasing_insert" on public.%I',t);execute format('drop policy if exists "purchasing_update" on public.%I',t);execute format('drop policy if exists "purchasing_delete" on public.%I',t);execute format('create policy "purchasing_select" on public.%I for select to authenticated using(true)',t);execute format('create policy "purchasing_insert" on public.%I for insert to authenticated with check(true)',t);execute format('create policy "purchasing_update" on public.%I for update to authenticated using(true) with check(true)',t);execute format('create policy "purchasing_delete" on public.%I for delete to authenticated using(true)',t);end loop;end$$;
