insert into public.status(code,name,module,description) values
('ACTIVO','Activo','CORE','Registro operativo y listo para usar'),
('INACTIVO','Inactivo','CORE','Registro deshabilitado (Soft Delete)'),
('BLOQUEADO','Bloqueado','CORE','Registro congelado por seguridad o regla de negocio'),
('SOLICITADO','Solicitado','Compras','Requisición de compra enviada para revisión'),
('ORDENADO','Ordenado','Compras','Orden de compra enviada al proveedor'),
('RECIBIDO_PARCIAL','Recibido Parcial','Compras','Mercancía o servicio entregado parcialmente'),
('RECIBIDO_TOTAL','Recibido Total','Compras','Mercancía o servicio recibido por completo'),
('COTIZADO','Cotizado','Ventas','Cotización enviada al cliente'),
('PEDIDO_CONFIRMADO','Pedido Confirmado','Ventas','Orden de venta aprobada por el cliente'),
('DESPACHADO','Despachado / Entregado','Ventas','Mercancía entregada o en camino al cliente'),
('FACTURADO','Facturado','Ventas','Comprobante fiscal o factura generada'),
('BORRADOR','Borrador','Transacciones','Documento preliminar sin impacto financiero ni stock'),
('PENDIENTE_APROBACION','Pendiente de Aprobación','Transacciones','Documento en espera de autorización superior'),
('APROBADO','Aprobado','Transacciones','Documento autorizado listo para ejecutarse'),
('ANULADO','Anulado / Cancelado','Transacciones','Documento cancelado sin validez legal o contable'),
('CERRADO','Cerrado','Transacciones','Proceso del documento finalizado por completo'),
('PENDIENTE_PAGO','Pendiente de Pago','Finanzas','Factura emitida pendiente de cobro o pago'),
('PAGADO_PARCIAL','Pagado Parcial','Finanzas','Factura con un abono registrado'),
('PAGADO','Pagado Totalmente','Finanzas','Factura cancelada en su totalidad (saldo $0)'),
('DISPONIBLE','Disponible','Inventario','Stock libre para venta o producción'),
('COMPROMETIDO','Comprometido','Inventario','Stock reservado para un pedido de venta'),
('EN_TRANSITO','En Tránsito','Inventario','Stock moviéndose entre almacenes o subsidiarias'),
('PERIODO_ABIERTO','Período Abierto','Contabilidad','Período fiscal habilitado para recibir asientos'),
('PERIODO_CERRADO','Período Cerrado','Contabilidad','Período fiscal bloqueado para modificaciones')
on conflict(code,module) do update set name=excluded.name,description=excluded.description;
