alter table asset_transfer add column if not exists source_location_id bigint references locations;
alter table asset_transfer add column if not exists target_location_id bigint references locations;
alter table asset_transfer add column if not exists note text;
alter table asset_transfer add column if not exists transfer_number text;
alter table asset_transfer add column if not exists created_at timestamptz not null default now();
alter table asset_disposal add column if not exists disposal_number text;
alter table asset_disposal add column if not exists book_value numeric(24,6)not null default 0;
alter table asset_disposal add column if not exists accumulated_depreciation numeric(24,6)not null default 0;
alter table asset_disposal add column if not exists note text;
alter table asset_disposal add column if not exists created_at timestamptz not null default now();
alter table asset_maintenance add column if not exists maintenance_number text;
alter table asset_maintenance add column if not exists maintenance_type text not null default'PREVENTIVO'check(maintenance_type in('PREVENTIVO','CORRECTIVO'));
alter table asset_maintenance add column if not exists status text not null default'PROGRAMADO'check(status in('PROGRAMADO','EN PROCESO','COMPLETADO','CANCELADO'));
alter table asset_maintenance add column if not exists completion_date date;
alter table asset_maintenance add column if not exists reference text;
alter table asset_maintenance add column if not exists created_at timestamptz not null default now();

create or replace function asset_operation_number(p_prefix text,p_table text,p_column text)returns text language plpgsql security definer set search_path=public,pg_temp as $$declare n bigint;begin perform pg_advisory_xact_lock(hashtextextended(p_prefix||active_subsidiary_id(),0));execute format('select coalesce(max(case when %I~%L then substring(%I from %L)::bigint end),0)+1 from %I',p_column,'^'||p_prefix||'-[0-9]+$',p_column,'[0-9]+$',p_table)into n;return p_prefix||'-'||lpad(n::text,8,'0');end$$;

create or replace function fixed_asset_operation_options()returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('subsidiary',jsonb_build_object('id',s.subsidiary_id,'name',s.name,'currency',cu.currency_code),'assets',coalesce((select jsonb_agg(jsonb_build_object('id',a.asset_id,'number',a.asset_number,'name',a.asset_name,'locationId',a.location_id,'cost',a.purchase_cost,'accumulated',coalesce(d.total,0),'bookValue',greatest(a.purchase_cost-coalesce(d.total,0),0))order by a.asset_number)from asset a left join lateral(select sum(depreciation_amount)total from asset_depreciation where asset_id=a.asset_id)d on true where a.subsidiary_id=s.subsidiary_id and a.status='ACTIVO'),'[]'),'subsidiaries',coalesce((select jsonb_agg(jsonb_build_object('id',x.subsidiary_id,'name',x.name)order by x.name)from subsidiaries x where x.is_active),'[]'),'locations',coalesce((select jsonb_agg(jsonb_build_object('id',l.location_id,'name',l.name,'subsidiaryId',coalesce(ls.subsidiary_id,l.subsidiary_id))order by l.name)from locations l left join location_subsidiaries ls using(location_id)where l.subsidiary_id=s.subsidiary_id or ls.subsidiary_id=s.subsidiary_id),'[]'),'suppliers',coalesce((select jsonb_agg(jsonb_build_object('id',p.supplier_id,'name',p.company_name)order by p.company_name)from suppliers p left join entity_subsidiaries es using(supplier_id)where p.primary_subsidiary_id=s.subsidiary_id or(es.subsidiary_id=s.subsidiary_id)),'[]'))from subsidiaries s join currencies cu using(currency_id)where s.subsidiary_id=active_subsidiary_id()$$;

create or replace function fixed_asset_operation_report(p_filters jsonb)returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$declare sid bigint:=active_subsidiary_id();kind text:=p_filters->>'type';f date:=coalesce(nullif(p_filters->>'from','')::date,'1900-01-01');t date:=coalesce(nullif(p_filters->>'to','')::date,'2999-12-31');q text:=coalesce(p_filters->>'search','');result jsonb;begin
if kind='TRANSFER'then select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',x.transfer_id,'number',x.transfer_number,'date',x.transfer_date,'assetId',a.asset_id,'asset',a.asset_number||' · '||a.asset_name,'source',ss.name,'target',ts.name,'sourceLocationId',x.source_location_id,'sourceLocation',sl.name,'targetLocationId',x.target_location_id,'targetLocation',tl.name,'targetSubsidiaryId',x.target_subsidiary_id,'note',x.note)order by x.transfer_date desc,x.transfer_id desc),'[]'))into result from asset_transfer x join asset a using(asset_id)join subsidiaries ss on ss.subsidiary_id=x.source_subsidiary_id join subsidiaries ts on ts.subsidiary_id=x.target_subsidiary_id left join locations sl on sl.location_id=x.source_location_id left join locations tl on tl.location_id=x.target_location_id where x.source_subsidiary_id=sid and x.transfer_date between f and t and concat_ws(' ',x.transfer_number,a.asset_number,a.asset_name,x.note)ilike'%'||q||'%';
elsif kind='DISPOSAL'then select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',d.disposal_id,'number',d.disposal_number,'date',d.disposal_date,'assetId',a.asset_id,'asset',a.asset_number||' · '||a.asset_name,'type',d.disposal_type,'bookValue',d.book_value,'accumulated',d.accumulated_depreciation,'saleAmount',d.sale_amount,'gainLoss',d.gain_loss_amount,'note',d.note)order by d.disposal_date desc,d.disposal_id desc),'[]'))into result from asset_disposal d join asset a using(asset_id)where a.subsidiary_id=sid and d.disposal_date between f and t and concat_ws(' ',d.disposal_number,a.asset_number,a.asset_name,d.note)ilike'%'||q||'%';
else select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',m.maintenance_id,'number',m.maintenance_number,'date',m.maintenance_date,'assetId',a.asset_id,'asset',a.asset_number||' · '||a.asset_name,'type',m.maintenance_type,'status',m.status,'completionDate',m.completion_date,'description',m.description,'cost',m.cost,'supplierId',m.supplier_id,'supplier',p.company_name,'reference',m.reference)order by m.maintenance_date desc,m.maintenance_id desc),'[]'))into result from asset_maintenance m join asset a using(asset_id)left join suppliers p using(supplier_id)where a.subsidiary_id=sid and m.maintenance_date between f and t and concat_ws(' ',m.maintenance_number,a.asset_number,a.asset_name,m.description,m.reference)ilike'%'||q||'%';end if;return result;end$$;

create or replace function save_fixed_asset_operation(p_payload jsonb,p_operation_id bigint default null)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare sid bigint:=active_subsidiary_id();kind text:=p_payload->>'type';id bigint:=p_operation_id;aid bigint:=(p_payload->>'asset_id')::bigint;num text;acc numeric;book numeric;begin
if not exists(select 1 from asset where asset_id=aid and subsidiary_id=sid)then raise exception'El activo no pertenece a la subsidiaria activa.';end if;
if kind='TRANSFER'then if id is null then num:=asset_operation_number('TRA-ACT','asset_transfer','transfer_number');insert into asset_transfer(transfer_number,transfer_date,asset_id,source_subsidiary_id,target_subsidiary_id,source_location_id,target_location_id,note)values(num,(p_payload->>'date')::date,aid,sid,(p_payload->>'target_subsidiary_id')::bigint,nullif(p_payload->>'source_location_id','')::bigint,(p_payload->>'target_location_id')::bigint,p_payload->>'note')returning transfer_id into id;else update asset_transfer set transfer_date=(p_payload->>'date')::date,target_subsidiary_id=(p_payload->>'target_subsidiary_id')::bigint,target_location_id=(p_payload->>'target_location_id')::bigint,note=p_payload->>'note'where transfer_id=id and source_subsidiary_id=sid returning transfer_number into num;end if;
elsif kind='DISPOSAL'then select coalesce(sum(depreciation_amount),0)into acc from asset_depreciation where asset_id=aid;select greatest(purchase_cost-acc,0)into book from asset where asset_id=aid;if id is null then num:=asset_operation_number('BAJ-ACT','asset_disposal','disposal_number');insert into asset_disposal(disposal_number,disposal_date,asset_id,disposal_type,sale_amount,gain_loss_amount,book_value,accumulated_depreciation,note)values(num,(p_payload->>'date')::date,aid,p_payload->>'disposal_type',coalesce(nullif(p_payload->>'sale_amount','')::numeric,0),coalesce(nullif(p_payload->>'sale_amount','')::numeric,0)-book,book,acc,p_payload->>'note')returning disposal_id into id;update asset set status='BAJA'where asset_id=aid;else update asset_disposal set disposal_date=(p_payload->>'date')::date,disposal_type=p_payload->>'disposal_type',sale_amount=coalesce(nullif(p_payload->>'sale_amount','')::numeric,0),gain_loss_amount=coalesce(nullif(p_payload->>'sale_amount','')::numeric,0)-book,note=p_payload->>'note'where disposal_id=id returning disposal_number into num;end if;
else if id is null then num:=asset_operation_number('MAN-ACT','asset_maintenance','maintenance_number');insert into asset_maintenance(maintenance_number,maintenance_date,asset_id,maintenance_type,status,completion_date,description,cost,supplier_id,reference)values(num,(p_payload->>'date')::date,aid,p_payload->>'maintenance_type',p_payload->>'status',nullif(p_payload->>'completion_date','')::date,p_payload->>'description',coalesce(nullif(p_payload->>'cost','')::numeric,0),nullif(p_payload->>'supplier_id','')::bigint,p_payload->>'reference')returning maintenance_id into id;else update asset_maintenance set maintenance_date=(p_payload->>'date')::date,maintenance_type=p_payload->>'maintenance_type',status=p_payload->>'status',completion_date=nullif(p_payload->>'completion_date','')::date,description=p_payload->>'description',cost=coalesce(nullif(p_payload->>'cost','')::numeric,0),supplier_id=nullif(p_payload->>'supplier_id','')::bigint,reference=p_payload->>'reference'where maintenance_id=id returning maintenance_number into num;end if;end if;return jsonb_build_object('id',id,'number',num,'message','Operación guardada correctamente.');end$$;

create or replace function delete_fixed_asset_operation(p_type text,p_operation_id bigint)returns boolean language plpgsql security definer set search_path=public,pg_temp as $$declare aid bigint;begin if p_type='TRANSFER'then delete from asset_transfer where transfer_id=p_operation_id and source_subsidiary_id=active_subsidiary_id();elsif p_type='DISPOSAL'then select a.asset_id into aid from asset_disposal d join asset a using(asset_id)where d.disposal_id=p_operation_id and a.subsidiary_id=active_subsidiary_id();delete from asset_disposal where disposal_id=p_operation_id;update asset set status='ACTIVO'where asset_id=aid;else delete from asset_maintenance m using asset a where m.maintenance_id=p_operation_id and a.asset_id=m.asset_id and a.subsidiary_id=active_subsidiary_id();end if;return true;end$$;
grant execute on function fixed_asset_operation_options(),fixed_asset_operation_report(jsonb),save_fixed_asset_operation(jsonb,bigint),delete_fixed_asset_operation(text,bigint)to authenticated;notify pgrst,'reload schema';
