alter table public.supplier_invoice add column if not exists invoice_type text not null default 'Factura estándar',add column if not exists payment_term_id bigint references public.payment_terms(term_id),add column if not exists location_id bigint references public.locations(location_id),add column if not exists invoice_date date,add column if not exists fiscal_period_id bigint references public.fiscal_periods(fiscal_period_id),add column if not exists currency_id bigint references public.currencies(currency_id),add column if not exists exchange_rate numeric(24,10) not null default 1,add column if not exists memo text,add column if not exists journal_id bigint references public.journal(journal_id);
alter table public.supplier_invoice alter column invoice_type set default 'Factura estándar';
update public.supplier_invoice set invoice_type=case invoice_type when 'Gastos' then 'Factura Expense' when 'Activos' then 'Factura Activos Fijos' else 'Factura estándar' end where invoice_type not in('Factura estándar','Factura Expense','Factura Tarjeta','Factura Caja Chica','Factura Activos Fijos');
alter table public.supplier_invoice drop constraint if exists supplier_invoice_type_check;alter table public.supplier_invoice add constraint supplier_invoice_type_check check(invoice_type in('Factura estándar','Factura Expense','Factura Tarjeta','Factura Caja Chica','Factura Activos Fijos'));
create or replace function public.sync_journal_transaction() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare tt bigint;st bigint;tid bigint;begin if new.transaction_id is null then select transaction_type_id into tt from transaction_types where abbreviation='ASI_DIA' limit 1;select status_id into st from status where code='APROBADO' and module='Transacciones' limit 1;if st is null then select status_id into st from status order by status_id limit 1;end if;insert into "transaction"(tran_number,tran_date,transaction_type_id,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,total_amount,status_id) values(new.journal_number,new.journal_date,tt,new.subsidiary_id,new.currency_id,new.exchange_rate,new.fiscal_period_id,greatest(coalesce(new.total_debit,0),coalesce(new.total_credit,0)),st) on conflict(tran_number) do update set tran_date=excluded.tran_date,subsidiary_id=excluded.subsidiary_id,currency_id=excluded.currency_id,exchange_rate=excluded.exchange_rate,fiscal_period_id=excluded.fiscal_period_id,total_amount=excluded.total_amount returning transaction_id into tid;new.transaction_id:=tid;else update "transaction" set tran_date=new.journal_date,subsidiary_id=new.subsidiary_id,currency_id=new.currency_id,exchange_rate=new.exchange_rate,fiscal_period_id=new.fiscal_period_id,total_amount=greatest(coalesce(new.total_debit,0),coalesce(new.total_credit,0)) where transaction_id=new.transaction_id;end if;return new;end$$;
update public.supplier_invoice i set invoice_date=coalesce(i.invoice_date,t.tran_date,i.due_date),fiscal_period_id=coalesce(i.fiscal_period_id,t.fiscal_period_id),currency_id=coalesce(i.currency_id,t.currency_id),exchange_rate=coalesce(i.exchange_rate,t.exchange_rate,1),journal_id=coalesce(i.journal_id,j.journal_id) from public."transaction" t left join public.journal j on j.transaction_id=t.transaction_id where i.transaction_id=t.transaction_id;
create table if not exists public.supplier_invoice_line(line_id bigint generated always as identity primary key,invoice_id bigint not null references public.supplier_invoice(invoice_id) on delete cascade,account_id bigint not null references public.chart_accounts(account_id),amount numeric(24,6) not null check(amount>0),tax_code_id bigint references public.tax_codes(tax_code_id),tax_rate numeric(12,6) not null default 0,tax_amount numeric(24,6) not null default 0,gross_amount numeric(24,6) not null,note text,department_id bigint references public.departments(department_id),cost_center_id bigint references public.cost_centers(cost_center_id),class_id bigint references public.classes(class_id),financial_creditor_id bigint references public.financial_creditors(financial_creditor_id),related_company_id bigint references public.related_companies(related_company_id));
alter table public.supplier_invoice_line enable row level security;drop policy if exists supplier_invoice_line_access on public.supplier_invoice_line;create policy supplier_invoice_line_access on public.supplier_invoice_line for all to authenticated using(exists(select 1 from supplier_invoice i join user_subsidiaries u using(subsidiary_id) where i.invoice_id=supplier_invoice_line.invoice_id and u.user_id=app_user_id())) with check(exists(select 1 from supplier_invoice i join user_subsidiaries u using(subsidiary_id) where i.invoice_id=supplier_invoice_line.invoice_id and u.user_id=app_user_id()));
insert into public.permissions(code,module,description) values('purchasing:supplier-invoice:create','Compras','Permite crear y contabilizar facturas de proveedores.'),('purchasing:supplier-invoice:update','Compras','Permite modificar facturas de proveedores contabilizadas.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.role_id,p.permission_id from public.roles r cross join public.permissions p where p.code in('purchasing:supplier-invoice:create','purchasing:supplier-invoice:update') and (r.is_system_role or lower(r.role_name) like '%admin%') on conflict do nothing;

create or replace function public.save_supplier_invoice(payload jsonb,target_invoice_id bigint default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare sid bigint:=active_subsidiary_id();iid bigint:=target_invoice_id;tid bigint;jid bigint;loc bigint;tt bigint;status_key bigint;book_key bigint;ap_account bigint;line jsonb;tax_account bigint;amount numeric;tax numeric;gross numeric;total numeric:=0;number text;rate numeric;
begin
 if sid is null then raise exception 'Debe seleccionar una subsidiaria.';end if;
 if not exists(select 1 from user_subsidiaries u where u.user_id=app_user_id() and u.subsidiary_id=sid) then raise exception 'No tiene acceso a la subsidiaria activa.';end if;
 if not exists(select 1 from user_roles ur join role_permissions rp using(role_id) join permissions p using(permission_id) where ur.user_id=app_user_id() and p.code=case when target_invoice_id is null then 'purchasing:supplier-invoice:create' else 'purchasing:supplier-invoice:update' end) then raise exception 'No tiene permiso para crear o modificar facturas de proveedores.';end if;
 if jsonb_array_length(coalesce(payload->'lines','[]'::jsonb))<1 then raise exception 'La factura debe contener al menos una línea.';end if;
 if nullif(trim(payload->>'invoice_number'),'') is null then raise exception 'El número de factura es obligatorio.';end if;if nullif(payload->>'supplier_id','') is null then raise exception 'Debe seleccionar un proveedor.';end if;if nullif(payload->>'payment_term_id','') is null or not exists(select 1 from payment_terms where term_id=(payload->>'payment_term_id')::bigint) then raise exception 'Debe seleccionar términos de pago válidos.';end if;if coalesce(payload->>'invoice_type','') not in('Factura estándar','Factura Expense','Factura Tarjeta','Factura Caja Chica','Factura Activos Fijos') then raise exception 'El tipo de factura no es válido.';end if;
 if not exists(select 1 from entity_subsidiaries where supplier_id=(payload->>'supplier_id')::bigint and subsidiary_id=sid) then raise exception 'El proveedor no está habilitado para la subsidiaria activa.';end if;
 if not exists(select 1 from fiscal_periods where fiscal_period_id=(payload->>'fiscal_period_id')::bigint and subsidiary_id=sid and not is_closed and not coalesce(is_inactive,false) and not coalesce(ap_closed,false) and (payload->>'invoice_date')::date between start_date and end_date) then raise exception 'El período de Compras no está abierto para la fecha indicada.';end if;
 rate:=coalesce(nullif(payload->>'exchange_rate','')::numeric,1);select l.location_id into loc from locations l join location_subsidiaries ls using(location_id) where ls.subsidiary_id=sid order by l.name,l.location_id limit 1;
 select transaction_type_id into tt from transaction_types where abbreviation='FAC_PRO' limit 1;select status_id into status_key from status order by case upper(code) when 'CONTABILIZADO' then 1 when 'APROBADO' then 2 when 'ACTIVO' then 3 else 4 end,status_id limit 1;select accounting_book_id into book_key from accounting_books where subsidiary_id=sid and is_active and is_primary order by accounting_book_id limit 1;
 select a.account_id into ap_account from chart_accounts a join account_subsidiaries s using(account_id) where s.subsidiary_id=sid and s.is_active and a.category='Pasivo' and (lower(a.account_name) like '%cuenta%por pagar%' or lower(a.account_name) like '%proveedor%por pagar%') order by a.account_number limit 1;
 if tt is null then raise exception 'No está configurado el tipo de transacción FAC_PRO.';end if;if status_key is null then raise exception 'No existe un estado de transacción configurado.';end if;if ap_account is null then raise exception 'No existe una cuenta activa de Cuentas por Pagar para la subsidiaria.';end if;if book_key is null then raise exception 'No existe un libro contable principal activo para la subsidiaria.';end if;
 for line in select * from jsonb_array_elements(payload->'lines') loop amount:=coalesce(nullif(line->>'amount','')::numeric,0);tax:=round(amount*coalesce(nullif(line->>'tax_rate','')::numeric,0)/100,6);total:=total+amount+tax;end loop;
 if iid is null then
  begin number:=next_transaction_number(tt,sid);exception when others then number:='FAC_PRO-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');end;
  insert into "transaction"(tran_number,tran_date,transaction_type_id,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,total_amount,status_id,supplier_id,payment_term_id) values(number,(payload->>'invoice_date')::date,tt,sid,(payload->>'currency_id')::bigint,rate,(payload->>'fiscal_period_id')::bigint,total,status_key,(payload->>'supplier_id')::bigint,(payload->>'payment_term_id')::bigint) returning transaction_id into tid;
  insert into journal(journal_number,journal_date,transaction_id,subsidiary_id,currency_id,fiscal_period_id,exchange_rate,memo,journal_type,location_id,total_debit,total_credit,status) values(number,(payload->>'invoice_date')::date,tid,sid,(payload->>'currency_id')::bigint,(payload->>'fiscal_period_id')::bigint,rate,payload->>'memo','Factura de proveedor',loc,total,total,'CONTABILIZADO') returning journal_id into jid;
  insert into supplier_invoice(invoice_number,transaction_id,supplier_id,subsidiary_id,due_date,total_amount,invoice_type,payment_term_id,location_id,invoice_date,fiscal_period_id,currency_id,exchange_rate,memo,journal_id) select trim(payload->>'invoice_number'),tid,(payload->>'supplier_id')::bigint,sid,(payload->>'invoice_date')::date+pt.days_due,total,payload->>'invoice_type',pt.term_id,loc,(payload->>'invoice_date')::date,(payload->>'fiscal_period_id')::bigint,(payload->>'currency_id')::bigint,rate,payload->>'memo',jid from payment_terms pt where pt.term_id=(payload->>'payment_term_id')::bigint returning invoice_id into iid;
 else
  select transaction_id,journal_id into tid,jid from supplier_invoice where invoice_id=iid and subsidiary_id=sid for update;if tid is null or jid is null then raise exception 'No se encontró la factura solicitada.';end if;
  update "transaction" set tran_date=(payload->>'invoice_date')::date,currency_id=(payload->>'currency_id')::bigint,exchange_rate=rate,fiscal_period_id=(payload->>'fiscal_period_id')::bigint,total_amount=total,supplier_id=(payload->>'supplier_id')::bigint,payment_term_id=(payload->>'payment_term_id')::bigint where transaction_id=tid;
  update journal set journal_date=(payload->>'invoice_date')::date,currency_id=(payload->>'currency_id')::bigint,exchange_rate=rate,fiscal_period_id=(payload->>'fiscal_period_id')::bigint,memo=payload->>'memo',location_id=loc,total_debit=total,total_credit=total where journal_id=jid;
  update supplier_invoice i set invoice_number=trim(payload->>'invoice_number'),supplier_id=(payload->>'supplier_id')::bigint,due_date=(payload->>'invoice_date')::date+pt.days_due,total_amount=total,invoice_type=payload->>'invoice_type',payment_term_id=pt.term_id,location_id=loc,invoice_date=(payload->>'invoice_date')::date,fiscal_period_id=(payload->>'fiscal_period_id')::bigint,currency_id=(payload->>'currency_id')::bigint,exchange_rate=rate,memo=payload->>'memo' from payment_terms pt where i.invoice_id=iid and pt.term_id=(payload->>'payment_term_id')::bigint;
  delete from gl_impact where transaction_id=tid;delete from journal_line where journal_id=jid;delete from supplier_invoice_line where invoice_id=iid;
 end if;
 for line in select * from jsonb_array_elements(payload->'lines') loop
  amount:=(line->>'amount')::numeric;tax:=round(amount*coalesce(nullif(line->>'tax_rate','')::numeric,0)/100,6);gross:=amount+tax;
  if amount<=0 or not exists(select 1 from chart_accounts a join account_subsidiaries s using(account_id) where a.account_id=(line->>'account_id')::bigint and s.subsidiary_id=sid and s.is_active and a.accepts_entries and not a.is_inactive) then raise exception 'Una línea contiene una cuenta no autorizada o un importe inválido.';end if;
  if payload->>'invoice_type'='Factura Activos Fijos' then
   if not exists(with recursive groups as(select g.group_id,g.parent_id,g.group_name from chart_accounts a join account_group g on g.group_id=a.account_group_id where a.account_id=(line->>'account_id')::bigint union all select parent.group_id,parent.parent_id,parent.group_name from account_group parent join groups child on child.parent_id=parent.group_id) select 1 from groups where lower(group_name) ~ 'propiedad.*planta.*equipo') then raise exception 'Las facturas de Activos Fijos solo permiten cuentas del grupo Propiedad, Planta y Equipo.';end if;
  elsif not exists(select 1 from chart_accounts a join account_group g on g.group_id=a.account_group_id where a.account_id=(line->>'account_id')::bigint and coalesce(a.category,g.category) in('Costo','Gasto')) then raise exception 'Este tipo de factura solo permite cuentas de Costos y Gastos.';end if;
  if nullif(line->>'department_id','') is not null and not exists(select 1 from chart_accounts a join account_group g on g.group_id=a.account_group_id join departments d on d.department_id=(line->>'department_id')::bigint where a.account_id=(line->>'account_id')::bigint and lower(d.type)=case when coalesce(a.category,g.category)='Costo' then 'cliente' else 'interno' end and (d.subsidiary_id=sid or exists(select 1 from department_subsidiaries ds where ds.department_id=d.department_id and ds.subsidiary_id=sid))) then raise exception 'El departamento seleccionado no corresponde al tipo requerido por la cuenta.';end if;
  if nullif(line->>'cost_center_id','') is not null and (nullif(line->>'department_id','') is null or not exists(select 1 from cost_centers cc join customers c on c.customer_id=cc.customer_id where cc.cost_center_id=(line->>'cost_center_id')::bigint and c.department_id=(line->>'department_id')::bigint and cc.subsidiary_id=sid and not cc.is_inactive)) then raise exception 'El centro de costos seleccionado no corresponde al departamento de la línea.';end if;
  if nullif(line->>'tax_code_id','') is not null and not exists(select 1 from tax_code_subsidiaries where tax_code_id=(line->>'tax_code_id')::bigint and subsidiary_id=sid) then raise exception 'Una línea contiene un código de impuesto no autorizado para la subsidiaria.';end if;
  insert into supplier_invoice_line(invoice_id,account_id,amount,tax_code_id,tax_rate,tax_amount,gross_amount,note,department_id,cost_center_id,class_id,financial_creditor_id,related_company_id) values(iid,(line->>'account_id')::bigint,amount,nullif(line->>'tax_code_id','')::bigint,coalesce(nullif(line->>'tax_rate','')::numeric,0),tax,gross,line->>'note',nullif(line->>'department_id','')::bigint,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'class_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint);
  insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,tax_code_id,tax_rate,gross_amount,note,entity_type,supplier_id,department_id,class_id,location_id,cost_center_id,financial_creditor_id,related_company_id) values(jid,(line->>'account_id')::bigint,amount,0,amount,0,nullif(line->>'tax_code_id','')::bigint,coalesce(nullif(line->>'tax_rate','')::numeric,0),gross,line->>'note','Proveedor',(payload->>'supplier_id')::bigint,nullif(line->>'department_id','')::bigint,nullif(line->>'class_id','')::bigint,loc,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint);
  insert into gl_impact(transaction_id,account_id,subsidiary_id,fiscal_period_id,accounting_book_id,debit_amount,credit_amount,debit_fx,credit_fx,posting_date) values(tid,(line->>'account_id')::bigint,sid,(payload->>'fiscal_period_id')::bigint,book_key,amount*rate,0,amount,0,(payload->>'invoice_date')::date);
  if tax>0 then select ty.asset_account_id into tax_account from tax_codes tc join tax_types ty using(tax_type_id) where tc.tax_code_id=(line->>'tax_code_id')::bigint;if tax_account is null then raise exception 'El código de impuesto no tiene cuenta contable de impuesto soportado.';end if;insert into gl_impact(transaction_id,account_id,subsidiary_id,fiscal_period_id,accounting_book_id,debit_amount,credit_amount,debit_fx,credit_fx,posting_date) values(tid,tax_account,sid,(payload->>'fiscal_period_id')::bigint,book_key,tax*rate,0,tax,0,(payload->>'invoice_date')::date);end if;
 end loop;
 insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,note,entity_type,supplier_id,location_id) values(jid,ap_account,0,total,0,total,'Cuenta por pagar · '||trim(payload->>'invoice_number'),'Proveedor',(payload->>'supplier_id')::bigint,loc);
 insert into gl_impact(transaction_id,account_id,subsidiary_id,fiscal_period_id,accounting_book_id,debit_amount,credit_amount,debit_fx,credit_fx,posting_date) values(tid,ap_account,sid,(payload->>'fiscal_period_id')::bigint,book_key,0,total*rate,0,total,(payload->>'invoice_date')::date);
 perform sync_journal_gl_impacts(jid);
 return jsonb_build_object('invoiceId',iid,'journalId',jid,'transactionNumber',number,'total',total);
end$$;
do $$declare supplier_journal bigint;begin for supplier_journal in select distinct journal_id from supplier_invoice where journal_id is not null loop perform sync_journal_gl_impacts(supplier_journal);end loop;end$$;
revoke all on public.supplier_invoice_line from authenticated;grant select on public.supplier_invoice_line to authenticated;grant usage,select on sequence public.supplier_invoice_line_line_id_seq to authenticated;revoke all on function public.save_supplier_invoice(jsonb,bigint) from public;grant execute on function public.save_supplier_invoice(jsonb,bigint) to authenticated;
