alter table public.bank_deposit add column if not exists subsidiary_id bigint references public.subsidiaries(subsidiary_id),add column if not exists currency_id bigint references public.currencies(currency_id),add column if not exists exchange_rate numeric(24,10),add column if not exists fiscal_period_id bigint references public.fiscal_periods(fiscal_period_id),add column if not exists location_id bigint references public.locations(location_id),add column if not exists memo text,add column if not exists journal_id bigint references public.journal(journal_id),add column if not exists created_by bigint references public.users(user_id),add column if not exists created_at timestamptz not null default now();
create table if not exists public.bank_deposit_line(deposit_line_id bigint generated always as identity primary key,deposit_id bigint not null references public.bank_deposit(deposit_id) on delete cascade,line_number integer not null,amount numeric(24,6) not null check(amount>0),account_id bigint not null references public.chart_accounts(account_id),payment_method_id bigint references public.payment_methods(payment_method_id),entity_type text,customer_id bigint references public.customers(customer_id),supplier_id bigint references public.suppliers(supplier_id),employee_id bigint references public.employees(employee_id),department_id bigint references public.departments(department_id),cost_center_id bigint references public.cost_centers(cost_center_id),class_id bigint references public.classes(class_id),financial_creditor_id bigint references public.financial_creditors(financial_creditor_id),related_company_id bigint references public.related_companies(related_company_id),note text,unique(deposit_id,line_number),check(entity_type is null or entity_type in('Cliente','Proveedor','Empleado')));
create index if not exists bank_deposit_company_date_idx on public.bank_deposit(subsidiary_id,deposit_date,bank_account_id);
create index if not exists bank_deposit_line_deposit_idx on public.bank_deposit_line(deposit_id,line_number);
alter table public.bank_deposit_line enable row level security;drop policy if exists bank_deposit_line_access on public.bank_deposit_line;create policy bank_deposit_line_access on public.bank_deposit_line for select to authenticated using(exists(select 1 from bank_deposit d where d.deposit_id=bank_deposit_line.deposit_id and d.subsidiary_id=active_subsidiary_id()));

create or replace function public.save_bank_deposit(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare sid bigint:=active_subsidiary_id();uid bigint:=app_user_id();ba bank_account%rowtype;d date:=(p_payload->>'deposit_date')::date;currency_key bigint:=(p_payload->>'currency_id')::bigint;rate numeric:=(p_payload->>'exchange_rate')::numeric;period_key bigint:=(p_payload->>'fiscal_period_id')::bigint;location_key bigint:=nullif(p_payload->>'location_id','')::bigint;tt bigint;status_key bigint;number text;tid bigint;jid bigint;did bigint;line jsonb;line_no int:=0;total numeric:=0;entity_kind text;entity_key bigint;
begin
 if sid is null then raise exception 'Seleccione una subsidiaria.';end if;if d is null or rate<=0 then raise exception 'Fecha y tipo de cambio son obligatorios.';end if;
 select * into ba from bank_account where bank_account_id=(p_payload->>'bank_account_id')::bigint for update;if ba.bank_account_id is null or ba.subsidiary_id<>sid then raise exception 'Seleccione una cuenta bancaria de la subsidiaria activa.';end if;if ba.currency_id<>currency_key then raise exception 'La moneda debe corresponder con la cuenta bancaria.';end if;
 if not exists(select 1 from fiscal_periods where fiscal_period_id=period_key and subsidiary_id=sid and d between start_date and end_date and not is_closed) then raise exception 'Seleccione un período contable abierto correspondiente a la fecha.';end if;
 if location_key is not null and not exists(select 1 from locations where location_id=location_key and (subsidiary_id=sid or subsidiary_id is null)) then raise exception 'La ubicación no pertenece a la subsidiaria.';end if;
 if jsonb_array_length(coalesce(p_payload->'lines','[]'::jsonb))=0 then raise exception 'Agregue al menos una línea al depósito.';end if;
 for line in select value from jsonb_array_elements(p_payload->'lines') loop if coalesce((line->>'amount')::numeric,0)<=0 or nullif(line->>'account_id','') is null then raise exception 'Cada línea requiere importe positivo y cuenta contable.';end if;total:=total+(line->>'amount')::numeric;end loop;
 select transaction_type_id into tt from transaction_types where abbreviation='DEP_BAN' limit 1;select status_id into status_key from status where code='APROBADO' and module='Transacciones' limit 1;if tt is null or status_key is null then raise exception 'Configure DEP_BAN y el estado APROBADO.';end if;begin number:=next_transaction_number(tt,sid);exception when others then number:='DEP_BAN-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS');end;
 insert into "transaction"(tran_number,tran_date,transaction_type_id,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,total_amount,status_id)values(number,d,tt,sid,currency_key,rate,period_key,total,status_key)returning transaction_id into tid;
 insert into journal(journal_number,journal_date,transaction_id,subsidiary_id,currency_id,fiscal_period_id,exchange_rate,memo,journal_type,location_id,total_debit,total_credit,status)values(number,d,tid,sid,currency_key,period_key,rate,nullif(p_payload->>'memo',''),'Depósito bancario',location_key,total,total,'CONTABILIZADO')returning journal_id into jid;
 insert into bank_deposit(deposit_number,bank_reference,bank_account_id,deposit_date,total_amount,subsidiary_id,currency_id,exchange_rate,fiscal_period_id,location_id,memo,journal_id,created_by)values(number,nullif(p_payload->>'bank_reference',''),ba.bank_account_id,d,total,sid,currency_key,rate,period_key,location_key,nullif(p_payload->>'memo',''),jid,uid)returning deposit_id into did;
 insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,location_id,note)values(jid,ba.account_id,total,0,total*rate,0,location_key,coalesce(nullif(p_payload->>'memo',''),'Depósito bancario'));
 for line in select value from jsonb_array_elements(p_payload->'lines') loop line_no:=line_no+1;entity_kind:=nullif(line->>'entity_type','');entity_key:=nullif(line->>'entity_id','')::bigint;
  insert into bank_deposit_line(deposit_id,line_number,amount,account_id,payment_method_id,entity_type,customer_id,supplier_id,employee_id,department_id,cost_center_id,class_id,financial_creditor_id,related_company_id,note)values(did,line_no,(line->>'amount')::numeric,(line->>'account_id')::bigint,nullif(line->>'payment_method_id','')::bigint,entity_kind,case when entity_kind='Cliente' then entity_key end,case when entity_kind='Proveedor' then entity_key end,case when entity_kind='Empleado' then entity_key end,nullif(line->>'department_id','')::bigint,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'class_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint,nullif(line->>'note',''));
  insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,department_id,class_id,location_id,note,entity_type,customer_id,supplier_id,employee_id,cost_center_id,financial_creditor_id,related_company_id)values(jid,(line->>'account_id')::bigint,0,(line->>'amount')::numeric,0,(line->>'amount')::numeric*rate,nullif(line->>'department_id','')::bigint,nullif(line->>'class_id','')::bigint,location_key,nullif(line->>'note',''),entity_kind,case when entity_kind='Cliente' then entity_key end,case when entity_kind='Proveedor' then entity_key end,case when entity_kind='Empleado' then entity_key end,nullif(line->>'cost_center_id','')::bigint,nullif(line->>'financial_creditor_id','')::bigint,nullif(line->>'related_company_id','')::bigint);
 end loop;
 insert into bank_transaction(tran_date,value_date,bank_account_id,transaction_id,amount,tran_type,reference_number,description,reconciliation_status)values(d,d,ba.bank_account_id,tid,total,'DEP_BAN',number,coalesce(nullif(p_payload->>'memo',''),'Depósito bancario'),'PENDIENTE_EN_TRANSITO');update bank_account set balance=balance+total where bank_account_id=ba.bank_account_id;return jsonb_build_object('depositId',did,'transactionNumber',number,'journalId',jid,'total',total);
end$$;
revoke all on function public.save_bank_deposit(jsonb) from public,anon;grant execute on function public.save_bank_deposit(jsonb) to authenticated;
alter table public.bank_deposit add column if not exists bank_reference text;
create or replace function public.bank_deposit_options() returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('subsidiary',jsonb_build_object('id',s.subsidiary_id,'name',s.name,'currencyId',s.currency_id),'location',(select jsonb_build_object('id',l.location_id,'name',l.name) from locations l where l.subsidiary_id=s.subsidiary_id order by l.location_id limit 1),'accounts',coalesce((select jsonb_agg(jsonb_build_object('id',ba.bank_account_id,'bankId',b.bank_id,'bankName',b.bank_name,'number',ba.account_number,'currencyId',ba.currency_id,'currencyCode',c.currency_code,'ledgerAccountId',ba.account_id,'balance',ba.balance) order by b.bank_name,ba.account_number) from bank_account ba join banks b using(bank_id) join currencies c using(currency_id) where ba.subsidiary_id=s.subsidiary_id and coalesce(ba.is_credit_card,false)=false),'[]'::jsonb)) from subsidiaries s where s.subsidiary_id=active_subsidiary_id()$$;
revoke all on function public.bank_deposit_options() from public,anon;grant execute on function public.bank_deposit_options() to authenticated;
notify pgrst,'reload schema';
