create or replace function public.bank_reconciliation_close_report(p_bank_account_id bigint,p_cutoff date)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare rec bank_reconciliation%rowtype;period_row fiscal_periods%rowtype;account_row record;closer_name text;result jsonb;
begin
 select r.*into rec from bank_reconciliation r join bank_account ba using(bank_account_id)join user_subsidiaries us using(subsidiary_id)where r.bank_account_id=p_bank_account_id and r.reconciliation_date=p_cutoff and r.status='CERRADA'and us.user_id=app_user_id();
 if rec.reconciliation_id is null then raise exception'No existe una conciliación cerrada para la cuenta y fecha seleccionadas.';end if;
 select*into period_row from fiscal_periods where fiscal_period_id=rec.fiscal_period_id;
 select ba.account_number,b.bank_name,c.currency_code,c.symbol,s.name subsidiary into account_row from bank_account ba join banks b using(bank_id)join currencies c using(currency_id)join subsidiaries s using(subsidiary_id)where ba.bank_account_id=p_bank_account_id;
 select coalesce(nullif(concat_ws(' ',u.first_name,u.last_name),''),u.email,'Sistema')into closer_name from users u where u.user_id=rec.closed_by;closer_name:=coalesce(closer_name,'Sistema');
 select jsonb_build_object(
  'header',jsonb_build_object('reconciliationId',rec.reconciliation_id,'subsidiary',account_row.subsidiary,'bank',account_row.bank_name,'account',account_row.account_number,'currency',account_row.currency_code,'symbol',account_row.symbol,'period',period_row.period_name,'periodStart',period_row.start_date,'periodEnd',period_row.end_date,'cutoff',rec.reconciliation_date,'closedAt',rec.closed_at,'closedBy',closer_name),
  'summary',jsonb_build_object('openingBalance',coalesce((select sum(bt.amount)from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date<period_row.start_date),0),'entries',coalesce((select sum(greatest(bt.amount,0))from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),0),'exits',coalesce((select sum(greatest(-bt.amount,0))from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),0),'transitEntries',coalesce(rec.transit_deposits,0),'transitExits',coalesce(rec.transit_payments,0),'adjustments',coalesce(rec.bank_adjustments,0),'bookBalance',coalesce(rec.book_balance,0),'statementBalance',coalesce(rec.statement_balance,0),'difference',coalesce(rec.difference,0)),
  'movements',coalesce((select jsonb_agg(jsonb_build_object('id',bt.bank_tran_id,'date',bt.tran_date,'valueDate',coalesce(bt.value_date,bt.tran_date),'type',coalesce(tt.abbreviation,bt.tran_type),'reference',coalesce(bt.reference_number,t.tran_number),'beneficiary',coalesce(bt.beneficiary,cu.company_name,sp.company_name,'—'),'note',coalesce(nullif(j.memo,''),notes.line_notes,nullif(bt.description,''),'Sin nota registrada'),'entry',greatest(bt.amount,0),'exit',greatest(-bt.amount,0),'status',bt.reconciliation_status)order by bt.tran_date,bt.bank_tran_id)from bank_transaction bt left join"transaction"t using(transaction_id)left join transaction_types tt using(transaction_type_id)left join customers cu on cu.customer_id=t.customer_id left join suppliers sp on sp.supplier_id=t.supplier_id left join journal j using(transaction_id)left join lateral(select string_agg(distinct nullif(trim(jl.note),''),' · ')line_notes from journal_line jl where jl.journal_id=j.journal_id)notes on true where bt.bank_account_id=p_bank_account_id and bt.tran_date between period_row.start_date and rec.reconciliation_date),'[]'::jsonb),
  'transitMovements',coalesce((select jsonb_agg(jsonb_build_object('id',bt.bank_tran_id,'date',bt.tran_date,'reference',bt.reference_number,'note',coalesce(bt.description,'Sin nota registrada'),'entry',greatest(bt.amount,0),'exit',greatest(-bt.amount,0))order by bt.tran_date,bt.bank_tran_id)from bank_transaction bt where bt.bank_account_id=p_bank_account_id and bt.tran_date<=rec.reconciliation_date and bt.reconciliation_status='PENDIENTE_EN_TRANSITO'),'[]'::jsonb)
 )into result;
 return result;
end$$;
revoke all on function public.bank_reconciliation_close_report(bigint,date)from public,anon;
grant execute on function public.bank_reconciliation_close_report(bigint,date)to authenticated;
notify pgrst,'reload schema';
