alter table public.number_sequences add column if not exists scope_type text,add column if not exists entity_key text,add column if not exists transaction_type_id bigint references public.transaction_types(transaction_type_id) on delete cascade,add column if not exists subsidiary_id bigint references public.subsidiaries(subsidiary_id) on delete cascade,add column if not exists allow_manual_update boolean not null default true;
update public.number_sequences set scope_type='Entidad',entity_key='LEGACY-'||sequence_id where scope_type is null;
alter table public.number_sequences alter column scope_type set not null;
alter table public.number_sequences drop constraint if exists number_sequences_scope_allowed;
alter table public.number_sequences add constraint number_sequences_scope_allowed check(scope_type in('Entidad','Transacción'));
alter table public.number_sequences drop constraint if exists number_sequences_scope_fields;
alter table public.number_sequences add constraint number_sequences_scope_fields check((scope_type='Entidad' and entity_key is not null and transaction_type_id is null and subsidiary_id is null)or(scope_type='Transacción' and entity_key is null and transaction_type_id is not null and subsidiary_id is not null));
create unique index if not exists number_sequences_entity_uidx on public.number_sequences(entity_key) where scope_type='Entidad';
create unique index if not exists number_sequences_transaction_uidx on public.number_sequences(transaction_type_id,subsidiary_id) where scope_type='Transacción';
insert into public.number_sequences(scope_type,entity_key,prefix,current_number,padding_length) values
('Entidad','Clientes','CLI-',(select last_value from public.customer_number_seq),8),('Entidad','Proveedores','PROV-',(select last_value from public.supplier_number_seq),8),('Entidad','Empleados','EMP-',(select last_value from public.employee_number_seq),8),('Entidad','Productos','PRD-',(select last_value from public.product_code_seq),8),('Entidad','Tipos de artículo','TA-',(select last_value from public.item_type_code_seq),8),('Entidad','Unidades de medida','UM-',(select last_value from public.uom_code_seq),8),('Entidad','Tipos de transacción','TT-',(select last_value from public.transaction_type_code_seq),8),('Entidad','Acreedores financieros','ACF-',(select last_value from public.financial_creditor_code_seq),8),('Entidad','Empresas relacionadas','INT-',(select last_value from public.related_company_code_seq),8)
on conflict(entity_key) where scope_type='Entidad' do update set prefix=excluded.prefix,current_number=excluded.current_number,padding_length=excluded.padding_length;
insert into public.number_sequences(scope_type,transaction_type_id,subsidiary_id,prefix,current_number,padding_length)
select 'Transacción',tt.transaction_type_id,s.subsidiary_id,tt.abbreviation||'-',0,8 from public.transaction_types tt cross join public.subsidiaries s where s.is_active=true and tt.abbreviation not in('FAC_PRO','NC_PRO','ND_PRO')
on conflict(transaction_type_id,subsidiary_id) where scope_type='Transacción' do nothing;
create or replace function public.next_transaction_number(target_type bigint,target_subsidiary bigint)returns text language plpgsql security definer set search_path=public,pg_temp as $$declare result text;begin update number_sequences set current_number=current_number+1 where scope_type='Transacción' and transaction_type_id=target_type and subsidiary_id=target_subsidiary returning coalesce(prefix,'')||lpad(current_number::text,padding_length,'0')||coalesce(suffix,'') into result;if result is null then raise exception 'No existe una secuencia para el tipo de transacción y subsidiaria seleccionados.';end if;return result;end$$;
revoke all on function public.next_transaction_number(bigint,bigint) from public,anon;grant execute on function public.next_transaction_number(bigint,bigint) to authenticated,service_role;
