alter table invoice add column if not exists opening_run_id bigint references opening_balance_runs,add column if not exists is_opening_balance boolean not null default false;
alter table supplier_invoice add column if not exists opening_run_id bigint references opening_balance_runs,add column if not exists is_opening_balance boolean not null default false;
create unique index if not exists one_posted_opening_per_subsidiary on opening_balance_runs(subsidiary_id)where status='POSTED';

create or replace function opening_balance_preview(p_run_id bigint)returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('run',to_jsonb(r),'rows',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'sourceType',l.source_type,'row',l.row_number,'account',a.account_number||' · '||a.account_name,'document',l.document_number,'currency',c.currency_code,'rate',l.historical_rate,'foreignAmount',l.foreign_amount,'debit',l.local_debit,'credit',l.local_credit,'costCenter',cc.code,'location',lo.name,'project',l.project_code,'note',l.note)order by l.source_type,l.row_number)from opening_balance_lines l join chart_accounts a on a.account_id=l.account_id join currencies c on c.currency_id=l.currency_id left join cost_centers cc on cc.cost_center_id=l.cost_center_id left join locations lo on lo.location_id=l.location_id where l.run_id=r.id),'[]'),'summary',(select jsonb_build_object('debit',coalesce(sum(local_debit),0),'credit',coalesce(sum(local_credit),0),'difference',coalesce(sum(local_debit-local_credit),0),'count',count(*))from opening_balance_lines where run_id=r.id))from opening_balance_runs r where r.id=p_run_id and r.subsidiary_id=active_subsidiary_id()$$;

create or replace function opening_balance_post(p_run_id bigint)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare r opening_balance_runs%rowtype;l opening_balance_lines%rowtype;per bigint;base bigint;jid bigint;num text;diff numeric;cid bigint;sid_entity bigint;
begin select * into r from opening_balance_runs where id=p_run_id and subsidiary_id=active_subsidiary_id()for update;if r.id is null or r.status not in('DRAFT','VALIDATED')then raise exception'Lote no disponible para contabilizar.';end if;select coalesce(sum(local_debit-local_credit),0)into diff from opening_balance_lines where run_id=r.id;if abs(diff)>.005 then raise exception'La apertura no cuadra. Diferencia: %.',diff;end if;select fiscal_period_id into per from fiscal_periods where subsidiary_id=r.subsidiary_id and r.opening_date between start_date and end_date and not is_closed limit 1;if per is null then raise exception'No existe un período contable abierto para la fecha de apertura.';end if;select currency_id into base from subsidiaries where subsidiary_id=r.subsidiary_id;num:='ASI-APERTURA-'||r.subsidiary_id||'-'||to_char(r.opening_date,'YYYYMMDD');insert into journal(journal_number,journal_date,subsidiary_id,currency_id,fiscal_period_id,exchange_rate,memo,journal_type,total_debit,total_credit,status,created_by,is_opening_balance)select num,r.opening_date,r.subsidiary_id,base,per,1,'Carga de saldos iniciales','APERTURA',sum(local_debit),sum(local_credit),'CONTABILIZADO',app_user_id(),true from opening_balance_lines where run_id=r.id returning journal_id into jid;
for l in select * from opening_balance_lines where run_id=r.id order by id loop
 cid:=null;sid_entity:=null;if l.source_type='AR'then select customer_id into cid from customers where tax_id=l.raw_data->>'entityTaxId'and(primary_subsidiary_id=r.subsidiary_id or exists(select 1 from entity_subsidiaries e where e.customer_id=customers.customer_id and e.subsidiary_id=r.subsidiary_id));if cid is null then raise exception'Fila % CxC: cliente no encontrado.',l.row_number;end if;if l.document_number is null or l.issue_date is null or l.due_date is null then raise exception'Fila % CxC: complete documento, emisión y vencimiento.',l.row_number;end if;if exists(select 1 from invoice where invoice_number=l.document_number and customer_id=cid)then raise exception'La factura CxC % ya existe.',l.document_number;end if;insert into invoice(invoice_number,customer_id,subsidiary_id,due_date,total_amount,invoice_date,fiscal_period_id,currency_id,exchange_rate,memo,journal_id,location_id,opening_run_id,is_opening_balance)values(l.document_number,cid,r.subsidiary_id,l.due_date,l.foreign_amount,l.issue_date,per,l.currency_id,l.historical_rate,coalesce(l.note,'Saldo inicial CxC'),jid,l.location_id,r.id,true);
 elsif l.source_type='AP'then select supplier_id into sid_entity from suppliers where tax_id=l.raw_data->>'entityTaxId'and(primary_subsidiary_id=r.subsidiary_id or exists(select 1 from entity_subsidiaries e where e.supplier_id=suppliers.supplier_id and e.subsidiary_id=r.subsidiary_id));if sid_entity is null then raise exception'Fila % CxP: proveedor no encontrado.',l.row_number;end if;if l.document_number is null or l.issue_date is null or l.due_date is null then raise exception'Fila % CxP: complete documento, emisión y vencimiento.',l.row_number;end if;if exists(select 1 from supplier_invoice where invoice_number=l.document_number and supplier_id=sid_entity)then raise exception'La factura CxP % ya existe.',l.document_number;end if;insert into supplier_invoice(invoice_number,supplier_id,subsidiary_id,due_date,total_amount,invoice_date,fiscal_period_id,currency_id,exchange_rate,memo,journal_id,location_id,opening_run_id,is_opening_balance)values(l.document_number,sid_entity,r.subsidiary_id,l.due_date,l.foreign_amount,l.issue_date,per,l.currency_id,l.historical_rate,coalesce(l.note,'Saldo inicial CxP'),jid,l.location_id,r.id,true);end if;
 insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,location_id,cost_center_id,note,entity_type,customer_id,supplier_id,historical_exchange_rate,original_currency_id,opening_balance_line_id)values(jid,l.account_id,l.local_debit,l.local_credit,case when l.local_debit>0 then l.foreign_amount else 0 end,case when l.local_credit>0 then l.foreign_amount else 0 end,l.location_id,l.cost_center_id,coalesce(l.note,'Saldo inicial'),case l.source_type when'AR'then'Cliente'when'AP'then'Proveedor'end,cid,sid_entity,l.historical_rate,l.currency_id,l.id);end loop;perform sync_journal_gl_impacts(jid);update opening_balance_runs set status='POSTED',journal_id=jid,posted_at=now()where id=r.id;return jsonb_build_object('runId',r.id,'journalId',jid,'journalNumber',num);end$$;

create or replace function opening_balance_reverse(p_run_id bigint)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare r opening_balance_runs%rowtype;rev bigint;n text;begin select * into r from opening_balance_runs where id=p_run_id and subsidiary_id=active_subsidiary_id()and status='POSTED'for update;if r.id is null then raise exception'Apertura contabilizada no encontrada.';end if;if exists(select 1 from customer_payment_application a join invoice i using(invoice_id)where i.opening_run_id=r.id)or exists(select 1 from supplier_payment_application a join supplier_invoice i using(invoice_id)where i.opening_run_id=r.id)then raise exception'No se puede reversar: existen cobros o pagos aplicados a documentos iniciales.';end if;n:='REV-'||(select journal_number from journal where journal_id=r.journal_id);insert into journal(journal_number,journal_date,subsidiary_id,currency_id,fiscal_period_id,exchange_rate,memo,journal_type,total_debit,total_credit,status,created_by,reversed_from_journal_id)select n,current_date,subsidiary_id,currency_id,fiscal_period_id,1,'Reversión de apertura','Reversión',total_credit,total_debit,'CONTABILIZADO',app_user_id(),journal_id from journal where journal_id=r.journal_id returning journal_id into rev;insert into journal_line(journal_id,account_id,debit,credit,debit_fx,credit_fx,department_id,class_id,location_id,cost_center_id,note,entity_type,customer_id,supplier_id)select rev,account_id,credit,debit,credit_fx,debit_fx,department_id,class_id,location_id,cost_center_id,'Reversión de apertura',entity_type,customer_id,supplier_id from journal_line where journal_id=r.journal_id;perform sync_journal_gl_impacts(rev);delete from invoice where opening_run_id=r.id;delete from supplier_invoice where opening_run_id=r.id;update opening_balance_runs set status='REVERSED',reversed_at=now()where id=r.id;return jsonb_build_object('reversalJournalId',rev,'number',n);end$$;

create or replace function prevent_before_opening_lock()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare d date;sid bigint;begin d:=case tg_table_name when'journal'then new.journal_date when'invoice'then new.invoice_date when'supplier_invoice'then new.invoice_date when'purchase_document'then new.document_date else new.document_date end;sid:=new.subsidiary_id;if coalesce(new.is_opening_balance,false)=false and exists(select 1 from opening_balance_runs where subsidiary_id=sid and status='POSTED'and d<=opening_date)then raise exception'La fecha está bloqueada por la contabilización de saldos iniciales.';end if;return new;end$$;
drop trigger if exists opening_lock_journal on journal;create trigger opening_lock_journal before insert or update of journal_date on journal for each row execute function prevent_before_opening_lock();
grant execute on function opening_balance_preview(bigint),opening_balance_post(bigint),opening_balance_reverse(bigint)to authenticated;notify pgrst,'reload schema';
