create or replace function public.run_bank_balance_period_report(p_filters jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare sid bigint:=active_subsidiary_id();period_key bigint:=nullif(p_filters->>'periodId','')::bigint;period_row fiscal_periods%rowtype;local_currency record;result jsonb;
begin
 if period_key is null then raise exception 'Seleccione el período contable que desea consultar.';end if;
 select*into period_row from fiscal_periods where fiscal_period_id=period_key and subsidiary_id=sid;
 if period_row.fiscal_period_id is null then raise exception 'El período seleccionado no pertenece a la empresa activa.';end if;
 select c.currency_id,c.currency_code,c.name,c.symbol into local_currency from subsidiaries s join currencies c using(currency_id)where s.subsidiary_id=sid;
 with accounts as(
  select ba.bank_account_id,b.bank_name,ba.account_number,ba.account_id,ca.account_number ledger_account_number,ca.account_name ledger_account_name,c.currency_id,c.currency_code,c.name currency_name,c.symbol,fx.run_id revaluation_run_id,fx.status revaluation_run_status,fx.journal_number revaluation_journal,fx.posted_at revalued_at,coalesce(fx.includes_account,false)revaluation_includes_account,
   coalesce((select sum(bt.amount)from bank_transaction bt where bt.bank_account_id=ba.bank_account_id and bt.tran_date<=period_row.end_date),0)foreign_balance,
   coalesce((select sum(g.debit_amount-g.credit_amount)from gl_impact g where g.subsidiary_id=sid and g.account_id=ba.account_id and g.posting_date<=period_row.end_date),0)ledger_balance,
   case when c.currency_id=local_currency.currency_id then 1 else coalesce((select er.spot_rate from exchange_rates er where er.from_currency_id=c.currency_id and er.to_currency_id=local_currency.currency_id and er.effective_date<=period_row.end_date order by er.effective_date desc,er.exchange_rate_id desc limit 1),(select 1/er.spot_rate from exchange_rates er where er.from_currency_id=local_currency.currency_id and er.to_currency_id=c.currency_id and er.effective_date<=period_row.end_date order by er.effective_date desc,er.exchange_rate_id desc limit 1))end closing_rate
  from bank_account ba join banks b using(bank_id)join currencies c using(currency_id)join chart_accounts ca using(account_id)
  left join lateral(select r.run_id,r.status,r.posted_at,j.journal_number,exists(select 1 from jsonb_array_elements(coalesce(r.snapshot,'[]'::jsonb))item where(item->>'accountId')::bigint=ba.account_id)includes_account from fx_revaluation_runs r left join journal j on j.journal_id=r.journal_id where r.subsidiary_id=sid and r.fiscal_period_id=period_row.fiscal_period_id and r.currency_id=ba.currency_id order by case r.status when'CONTABILIZADO'then 1 when'PENDIENTE'then 2 else 3 end,r.run_id desc limit 1)fx on true
  where ba.subsidiary_id=sid and not coalesce(ba.is_credit_card,false)
 ),rows as(select*,case when closing_rate is null then null else round(foreign_balance*closing_rate,2)end local_equivalent from accounts),validation_groups as(
  select account_id,ledger_account_number,ledger_account_name,currency_id=local_currency.currency_id is_local,sum(local_equivalent)bank_total,max(ledger_balance)ledger_balance,bool_or(closing_rate is null)missing_rate,
   case when bool_or(closing_rate is null)then null else round(sum(local_equivalent)-max(ledger_balance),2)end difference
  from rows group by account_id,ledger_account_number,ledger_account_name,currency_id=local_currency.currency_id
 )
 select jsonb_build_object(
  'period',jsonb_build_object('id',period_row.fiscal_period_id,'name',period_row.period_name,'start',period_row.start_date,'end',period_row.end_date),
  'localCurrency',jsonb_build_object('id',local_currency.currency_id,'code',local_currency.currency_code,'name',local_currency.name,'symbol',local_currency.symbol),
  'localAccounts',coalesce((select jsonb_agg(jsonb_build_object('id',bank_account_id,'bank',bank_name,'account',account_number,'currency',currency_code,'currencyName',currency_name,'symbol',symbol,'balance',foreign_balance,'rate',closing_rate,'localEquivalent',local_equivalent,'ledgerAccount',ledger_account_number,'ledgerAccountName',ledger_account_name)order by bank_name,account_number)from rows where currency_id=local_currency.currency_id),'[]'::jsonb),
  'foreignAccounts',coalesce((select jsonb_agg(jsonb_build_object('id',bank_account_id,'bank',bank_name,'account',account_number,'currency',currency_code,'currencyName',currency_name,'symbol',symbol,'balance',foreign_balance,'rate',closing_rate,'localEquivalent',local_equivalent,'ledgerAccount',ledger_account_number,'ledgerAccountName',ledger_account_name,'missingRate',closing_rate is null,'revalued',revaluation_run_status='CONTABILIZADO'and revaluation_includes_account,'revaluationStatus',case when revaluation_run_id is null then'NO_REVALUADA'when revaluation_run_status='CONTABILIZADO'and revaluation_includes_account then'REVALUADA'when revaluation_run_status='CONTABILIZADO'then'NO_INCLUIDA'else revaluation_run_status end,'revaluationRunId',revaluation_run_id,'revaluationJournal',revaluation_journal,'revaluedAt',revalued_at)order by currency_code,bank_name,account_number)from rows where currency_id<>local_currency.currency_id),'[]'::jsonb),
  'localValidationGroups',coalesce((select jsonb_agg(jsonb_build_object('ledgerAccount',ledger_account_number,'ledgerAccountName',ledger_account_name,'bankTotal',bank_total,'ledgerBalance',ledger_balance,'difference',difference,'matches',abs(difference)<.005,'missingRate',missing_rate)order by ledger_account_number)from validation_groups where is_local),'[]'::jsonb),
  'foreignValidationGroups',coalesce((select jsonb_agg(jsonb_build_object('ledgerAccount',ledger_account_number,'ledgerAccountName',ledger_account_name,'bankTotal',bank_total,'ledgerBalance',ledger_balance,'difference',difference,'matches',case when difference is null then false else abs(difference)<.005 end,'missingRate',missing_rate)order by ledger_account_number)from validation_groups where not is_local),'[]'::jsonb),
  'summary',jsonb_build_object('localBankBalance',coalesce((select sum(bank_total)from validation_groups where is_local),0),'localLedgerBalance',coalesce((select sum(ledger_balance)from validation_groups where is_local),0),'foreignLocalEquivalent',coalesce((select sum(bank_total)from validation_groups where not is_local),0),'foreignLedgerBalance',coalesce((select sum(ledger_balance)from validation_groups where not is_local),0),'totalLocalEquivalent',coalesce((select sum(bank_total)from validation_groups),0),'totalLedgerBalance',coalesce((select sum(ledger_balance)from validation_groups),0),'allMatch',not exists(select 1 from validation_groups where difference is null or abs(difference)>=.005),'missingRates',coalesce((select count(*)from rows where currency_id<>local_currency.currency_id and closing_rate is null),0))
 )into result;return result;
end$$;
revoke all on function public.run_bank_balance_period_report(jsonb)from public,anon;
grant execute on function public.run_bank_balance_period_report(jsonb)to authenticated;
notify pgrst,'reload schema';
