create table if not exists asset_revaluation(
 revaluation_id bigint generated always as identity primary key,asset_id bigint not null references asset on delete restrict,revaluation_date date not null,previous_value numeric(24,6)not null,new_value numeric(24,6)not null,revaluation_amount numeric(24,6)not null,note text,transaction_id bigint references "transaction",created_at timestamptz not null default now()
);
create table if not exists asset_impairment(
 impairment_id bigint generated always as identity primary key,asset_id bigint not null references asset on delete restrict,assessment_date date not null,carrying_amount numeric(24,6)not null,recoverable_amount numeric(24,6)not null,impairment_loss numeric(24,6)not null check(impairment_loss>=0),note text,transaction_id bigint references "transaction",created_at timestamptz not null default now()
);
alter table asset_revaluation enable row level security;alter table asset_impairment enable row level security;
drop policy if exists fixed_asset_revaluation_select on asset_revaluation;create policy fixed_asset_revaluation_select on asset_revaluation for select to authenticated using(exists(select 1 from asset a where a.asset_id=asset_revaluation.asset_id and a.subsidiary_id=active_subsidiary_id()));
drop policy if exists fixed_asset_impairment_select on asset_impairment;create policy fixed_asset_impairment_select on asset_impairment for select to authenticated using(exists(select 1 from asset a where a.asset_id=asset_impairment.asset_id and a.subsidiary_id=active_subsidiary_id()));

create or replace function fixed_asset_analytics(p_filters jsonb default'{}')returns jsonb language plpgsql stable security definer set search_path=public,pg_temp as $$
declare sid bigint:=active_subsidiary_id();date_from date:=coalesce(nullif(p_filters->>'from','')::date,date_trunc('year',current_date)::date);date_to date:=coalesce(nullif(p_filters->>'to','')::date,current_date);asset_key bigint:=nullif(p_filters->>'assetId','')::bigint;result jsonb;
begin
 select jsonb_build_object(
 'subsidiary',(select jsonb_build_object('id',s.subsidiary_id,'name',s.name,'currency',c.currency_code)from subsidiaries s join currencies c using(currency_id)where s.subsidiary_id=sid),
 'assets',coalesce((select jsonb_agg(jsonb_build_object('id',a.asset_id,'number',a.asset_number,'name',a.asset_name,'category',ac.category_name,'location',l.name,'purchaseDate',a.purchase_date,'serviceDate',a.in_service_date,'cost',a.purchase_cost,'status',a.status,'accumulated',coalesce(dep.accumulated,0),'periodDepreciation',coalesce(dep.period_amount,0),'bookValue',greatest(a.purchase_cost-coalesce(dep.accumulated,0)-coalesce(imp.loss,0),0),'impairment',coalesce(imp.loss,0))order by a.asset_number)from asset a join asset_category ac using(category_id)join locations l using(location_id)left join lateral(select sum(depreciation_amount)filter(where depreciation_date<=date_to)accumulated,sum(depreciation_amount)filter(where depreciation_date between date_from and date_to)period_amount from asset_depreciation where asset_id=a.asset_id)dep on true left join lateral(select sum(impairment_loss)filter(where assessment_date<=date_to)loss from asset_impairment where asset_id=a.asset_id)imp on true where a.subsidiary_id=sid and(asset_key is null or a.asset_id=asset_key)),'[]'),
 'depreciations',coalesce((select jsonb_agg(jsonb_build_object('id',d.depreciation_id,'assetId',a.asset_id,'number',a.asset_number,'asset',a.asset_name,'category',c.category_name,'date',d.depreciation_date,'period',p.period_name,'amount',d.depreciation_amount,'accumulated',d.accumulated_depreciation,'journalId',j.journal_id)order by d.depreciation_date,a.asset_number)from asset_depreciation d join asset a using(asset_id)join asset_category c using(category_id)join fiscal_periods p using(fiscal_period_id)left join gl_impact g on g.gl_impact_id=d.gl_impact_id left join journal j on j.transaction_id=g.transaction_id where a.subsidiary_id=sid and d.depreciation_date between date_from and date_to and(asset_key is null or a.asset_id=asset_key)),'[]'),
 'movements',coalesce((select jsonb_agg(x order by x->>'date',x->>'number')from(select jsonb_build_object('type','ALTA','date',a.purchase_date,'number',a.asset_number,'asset',a.asset_name,'amount',a.purchase_cost,'note','Alta del activo')x from asset a where a.subsidiary_id=sid and a.purchase_date between date_from and date_to union all select jsonb_build_object('type','BAJA','date',d.disposal_date,'number',a.asset_number,'asset',a.asset_name,'amount',d.sale_amount,'note',d.disposal_type)from asset_disposal d join asset a using(asset_id)where a.subsidiary_id=sid and d.disposal_date between date_from and date_to union all select jsonb_build_object('type','REVALUACIÓN','date',r.revaluation_date,'number',a.asset_number,'asset',a.asset_name,'amount',r.revaluation_amount,'note',r.note)from asset_revaluation r join asset a using(asset_id)where a.subsidiary_id=sid and r.revaluation_date between date_from and date_to)x),'[]'),
 'reconciliation',coalesce((select jsonb_agg(jsonb_build_object('category',c.category_name,'assetAccount',aa.account_number||' · '||aa.account_name,'depreciationAccount',da.account_number||' · '||da.account_name,'registerCost',x.register_cost,'ledgerCost',x.ledger_cost,'costDifference',x.register_cost-x.ledger_cost,'registerDepreciation',x.register_depreciation,'ledgerDepreciation',x.ledger_depreciation,'depreciationDifference',x.register_depreciation-x.ledger_depreciation)order by c.category_name)from asset_category c join chart_accounts aa on aa.account_id=c.asset_account_id join chart_accounts da on da.account_id=c.depreciation_account_id join lateral(select coalesce(sum(a.purchase_cost),0)register_cost,coalesce((select sum(g.debit_amount-g.credit_amount)from gl_impact g where g.subsidiary_id=sid and g.account_id=c.asset_account_id and g.posting_date<=date_to),0)ledger_cost,coalesce((select sum(d.depreciation_amount)from asset_depreciation d join asset z using(asset_id)where z.category_id=c.category_id and d.depreciation_date<=date_to),0)register_depreciation,coalesce((select sum(g.credit_amount-g.debit_amount)from gl_impact g where g.subsidiary_id=sid and g.account_id=c.depreciation_account_id and g.posting_date<=date_to),0)ledger_depreciation from asset a where a.category_id=c.category_id and a.subsidiary_id=sid)x on true where c.subsidiary_id=sid),'[]'),
 'projection',coalesce((select jsonb_agg(jsonb_build_object('assetId',a.asset_id,'number',a.asset_number,'asset',a.asset_name,'category',c.category_name,'monthly',round((a.purchase_cost-a.purchase_cost*c.residual_value_percentage/100)/greatest(c.useful_life_months,1),2),'remaining',greatest(a.purchase_cost-a.purchase_cost*c.residual_value_percentage/100-coalesce(d.accumulated,0),0),'remainingMonths',greatest(c.useful_life_months-coalesce(d.months,0),0),'projectedEnd',(date_trunc('month',coalesce(maxdep.last_date,a.in_service_date))+(greatest(c.useful_life_months-coalesce(d.months,0),0)||' months')::interval)::date)order by a.asset_number)from asset a join asset_category c using(category_id)left join lateral(select sum(depreciation_amount)accumulated,count(*)months from asset_depreciation where asset_id=a.asset_id)d on true left join lateral(select max(depreciation_date)last_date from asset_depreciation where asset_id=a.asset_id)maxdep on true where a.subsidiary_id=sid and a.status='ACTIVO'and c.depreciation_method<>'No Depreciable'),'[]'),
 'impairments',coalesce((select jsonb_agg(jsonb_build_object('date',i.assessment_date,'number',a.asset_number,'asset',a.asset_name,'carryingAmount',i.carrying_amount,'recoverableAmount',i.recoverable_amount,'loss',i.impairment_loss,'note',i.note)order by i.assessment_date desc)from asset_impairment i join asset a using(asset_id)where a.subsidiary_id=sid and i.assessment_date between date_from and date_to),'[]'),
 'disposals',coalesce((select jsonb_agg(jsonb_build_object('date',d.disposal_date,'number',a.asset_number,'asset',a.asset_name,'type',d.disposal_type,'saleAmount',d.sale_amount,'gainLoss',d.gain_loss_amount)order by d.disposal_date desc)from asset_disposal d join asset a using(asset_id)where a.subsidiary_id=sid and d.disposal_date between date_from and date_to),'[]'),
 'assetOptions',coalesce((select jsonb_agg(jsonb_build_object('id',asset_id,'number',asset_number,'name',asset_name)order by asset_number)from asset where subsidiary_id=sid),'[]')
 )into result;return result;
end$$;
grant execute on function fixed_asset_analytics(jsonb)to authenticated;
notify pgrst,'reload schema';
