import{getSupabaseConfig}from'../../core/database/supabase.client.js';type T='text'|'number'|'datetime-local';export interface AuditField{key:string;label:string;type:T;required?:boolean;reference?:string;}export interface AuditCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:AuditField[];}
export const auditCatalogs:AuditCatalog[]=[
{slug:'audit-logs',table:'audit_log',title:'Bitácora de auditoría',description:'Bitácora general de auditoría del sistema',primaryKey:'log_id',fields:[{key:'user_id',label:'Usuario',type:'number',reference:'security/users'},{key:'action',label:'Acción',type:'text',required:true},{key:'entity_type',label:'Tipo de entidad',type:'text',required:true},{key:'entity_id',label:'ID de entidad',type:'number',required:true},{key:'timestamp',label:'Fecha y hora',type:'datetime-local',required:true},{key:'ip_address',label:'Dirección IP',type:'text'}]},
{slug:'change-logs',table:'change_log',title:'Historial de cambios',description:'Cambios anteriores y posteriores por campo',primaryKey:'change_id',fields:[{key:'audit_log_id',label:'Registro de auditoría',type:'number',required:true,reference:'audit/audit-logs'},{key:'field_name',label:'Campo',type:'text',required:true},{key:'old_value',label:'Valor anterior',type:'text'},{key:'new_value',label:'Valor nuevo',type:'text'}]},
{slug:'event-logs',table:'event_log',title:'Eventos del sistema',description:'Registro de eventos del sistema',primaryKey:'event_id',fields:[{key:'event_type',label:'Tipo de evento',type:'text',required:true},{key:'source_component',label:'Componente origen',type:'text',required:true},{key:'description',label:'Descripción',type:'text',required:true},{key:'timestamp',label:'Fecha y hora',type:'datetime-local',required:true}]},
{slug:'activity-logs',table:'activity_log',title:'Actividad de usuarios',description:'Registro de actividades de usuario',primaryKey:'activity_id',fields:[{key:'user_id',label:'Usuario',type:'number',required:true,reference:'security/users'},{key:'activity_type',label:'Tipo de actividad',type:'text',required:true},{key:'path_accessed',label:'Ruta consultada',type:'text',required:true},{key:'timestamp',label:'Fecha y hora',type:'datetime-local',required:true}]},
{slug:'deleted-records',table:'deleted_records',title:'Registros eliminados',description:'Papelera y registro de eliminaciones',primaryKey:'deleted_id',fields:[{key:'original_table_name',label:'Tabla original',type:'text',required:true},{key:'original_record_id',label:'ID original',type:'number',required:true},{key:'deleted_by_user_id',label:'Eliminado por',type:'number',required:true,reference:'security/users'},{key:'deleted_at',label:'Fecha de eliminación',type:'datetime-local',required:true},{key:'record_data_json',label:'Datos del registro',type:'text',required:true}]}
];
export function getAuditCatalog(s:string){const c=auditCatalogs.find(x=>x.slug===s);if(!c)throw new Error('El catálogo de Auditoría no existe.');return c;}function sanitize(c:AuditCatalog,i:Record<string,unknown>){return Object.fromEntries(c.fields.map(f=>{const r=i[f.key];if(f.required&&(r===undefined||r===null||String(r).trim()===''))throw new Error(`${f.label} es obligatorio.`);if(f.type==='number')return[f.key,r===undefined||r===null||r===''?null:Number(r)];return[f.key,r===undefined||r===null||String(r).trim()===''?null:String(r).trim()];}));}async function request<R>(c:AuditCatalog,t:string,q='',i:RequestInit={}):Promise<R>{const g=getSupabaseConfig();if(!g)throw new Error('Supabase no está configurado.');const r=await fetch(new URL(`/rest/v1/${c.table}${q}`,g.url),{...i,headers:{apikey:g.anonKey,Authorization:t,'Content-Type':'application/json',...(i.headers??{})}});const x=r.status===204?'':await r.text();const p:unknown=x?JSON.parse(x):null;if(!r.ok){const m=typeof p==='object'&&p!==null&&'message'in p?String(p.message):'No fue posible completar la operación.';throw new Error(m);}return p as R;}
export const listAuditRows=(c:AuditCatalog,t:string)=>request<Record<string,unknown>[]>(c,t,`?select=*&order=${c.primaryKey}.asc`);export async function createAuditRow(c:AuditCatalog,t:string,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export async function updateAuditRow(c:AuditCatalog,t:string,id:number,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export const deleteAuditRow=(c:AuditCatalog,t:string,id:number)=>request<null>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'DELETE'});
