import{getSupabaseConfig}from'../../core/database/supabase.client.js';
type FieldType='text'|'number'|'boolean'|'date';export interface ConfigurationField{key:string;label:string;type:FieldType;required?:boolean;reference?:string;}export interface ConfigurationCatalog{slug:string;table:string;title:string;description:string;primaryKey:string;fields:ConfigurationField[];}
export const configurationCatalogs:ConfigurationCatalog[]=[
{slug:'exchange-rates',table:'exchange_rates',title:'Tipos de cambio',description:'Tipos de cambio diarios operativos',primaryKey:'exchange_rate_id',fields:[{key:'from_currency_id',label:'Moneda origen',type:'number',required:true,reference:'core/currencies'},{key:'to_currency_id',label:'Moneda destino',type:'number',required:true,reference:'core/currencies'},{key:'effective_date',label:'Fecha efectiva',type:'date',required:true},{key:'spot_rate',label:'Tipo de cambio',type:'number',required:true}]},
{slug:'fiscal-periods',table:'fiscal_periods',title:'Períodos fiscales',description:'Períodos contables mensuales',primaryKey:'fiscal_period_id',fields:[{key:'period_name',label:'Período',type:'text',required:true},{key:'start_date',label:'Fecha inicial',type:'date',required:true},{key:'end_date',label:'Fecha final',type:'date',required:true},{key:'is_closed',label:'Cerrado',type:'boolean'},{key:'fiscal_year_id',label:'Año fiscal',type:'number',required:true,reference:'organization/fiscal-years'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'}]},
{slug:'consolidated-exchange-rates',table:'consolidated_exchange_rates',title:'Tipos de cambio consolidados',description:'Tipos de cambio Spot, promedio e histórico',primaryKey:'rate_id',fields:[{key:'from_currency_id',label:'Moneda origen',type:'number',required:true,reference:'core/currencies'},{key:'to_currency_id',label:'Moneda destino',type:'number',required:true,reference:'core/currencies'},{key:'fiscal_period_id',label:'Período fiscal',type:'number',required:true,reference:'configuration/fiscal-periods'},{key:'average_rate',label:'Tasa promedio',type:'number',required:true},{key:'current_rate',label:'Tasa actual',type:'number',required:true},{key:'historical_rate',label:'Tasa histórica',type:'number',required:true}]},
{slug:'payment-terms',table:'payment_terms',title:'Términos de pago',description:'Términos y condiciones de pago',primaryKey:'term_id',fields:[{key:'term_name',label:'Término',type:'text',required:true},{key:'days_due',label:'Días de vencimiento',type:'number',required:true},{key:'discount_days',label:'Días de descuento',type:'number',required:true},{key:'discount_percentage',label:'Porcentaje descuento',type:'number',required:true}]},
{slug:'payment-methods',table:'payment_methods',title:'Métodos de pago',description:'Métodos de pago',primaryKey:'payment_method_id',fields:[{key:'method_name',label:'Método',type:'text',required:true},{key:'is_credit_card',label:'Tarjeta de crédito',type:'boolean'},{key:'is_bank_transfer',label:'Transferencia bancaria',type:'boolean'}]},
{slug:'uom',table:'uom',title:'Unidades de medida',description:'Unidades de medida UOM',primaryKey:'uom_id',fields:[{key:'unit_code',label:'Código',type:'text',required:true},{key:'name',label:'Nombre',type:'text',required:true},{key:'symbol',label:'Símbolo',type:'text',required:true}]},
{slug:'tax-agencies',table:'tax_agencies',title:'Agencias tributarias',description:'Agencias impositivas por país',primaryKey:'tax_agency_id',fields:[{key:'agency_name',label:'Agencia',type:'text',required:true},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',reference:'organization/subsidiaries'},{key:'tax_id',label:'Identificación fiscal',type:'text',required:true}]},
{slug:'tax-types',table:'tax_types',title:'Tipos de impuesto',description:'Tipos de impuestos: IVA, retención y arancel',primaryKey:'tax_type_id',fields:[{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'type_name',label:'Tipo',type:'text',required:true}]},
{slug:'tax-codes',table:'tax_codes',title:'Códigos de impuesto',description:'Códigos de impuestos aplicables',primaryKey:'tax_code_id',fields:[{key:'code_name',label:'Código',type:'text',required:true},{key:'rate_percentage',label:'Porcentaje',type:'number',required:true},{key:'is_withholding',label:'Es retención',type:'boolean'},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'tax_agency_id',label:'Agencia',type:'number',required:true,reference:'configuration/tax-agencies'},{key:'tax_type_id',label:'Tipo de impuesto',type:'number',required:true,reference:'configuration/tax-types'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',reference:'organization/subsidiaries'}]},
{slug:'tax-groups',table:'tax_groups',title:'Grupos de impuestos',description:'Grupos de impuestos combinados',primaryKey:'tax_group_id',fields:[{key:'group_code',label:'Código',type:'text',required:true},{key:'group_name',label:'Nombre',type:'text',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'}]},
{slug:'series',table:'series',title:'Series de documentos',description:'Series de numeración de documentos',primaryKey:'series_id',fields:[{key:'series_name',label:'Serie',type:'text',required:true},{key:'prefix',label:'Prefijo',type:'text'},{key:'current_number',label:'Número actual',type:'number',required:true},{key:'subsidiary_id',label:'Subsidiaria',type:'number',required:true,reference:'organization/subsidiaries'},{key:'transaction_type_id',label:'Tipo de transacción',type:'number',required:true,reference:'core/transaction-types'}]},
{slug:'document-types',table:'document_types',title:'Tipos de documento',description:'Tipos de documentos comprobantes',primaryKey:'document_type_id',fields:[{key:'type_code',label:'Código',type:'text',required:true},{key:'type_name',label:'Nombre',type:'text',required:true},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'}]},
{slug:'holidays',table:'holidays',title:'Días feriados',description:'Días feriados por país y subsidiaria',primaryKey:'holiday_id',fields:[{key:'holiday_date',label:'Fecha',type:'date',required:true},{key:'description',label:'Descripción',type:'text',required:true},{key:'country_id',label:'País',type:'number',required:true,reference:'core/countries'},{key:'subsidiary_id',label:'Subsidiaria',type:'number',reference:'organization/subsidiaries'}]}
];
export function getConfigurationCatalog(slug:string){const catalog=configurationCatalogs.find(x=>x.slug===slug);if(!catalog)throw new Error('El catálogo de Configuración no existe.');return catalog;}function sanitize(catalog:ConfigurationCatalog,input:Record<string,unknown>){return Object.fromEntries(catalog.fields.map(f=>{const raw=input[f.key];if(f.required&&(raw===undefined||raw===null||String(raw).trim()===''))throw new Error(`${f.label} es obligatorio.`);if(f.type==='boolean')return[f.key,raw===true||raw==='true'];if(f.type==='number')return[f.key,raw===undefined||raw===null||raw===''?null:Number(raw)];return[f.key,raw===undefined||raw===null||String(raw).trim()===''?null:String(raw).trim()];}));}async function request<T>(catalog:ConfigurationCatalog,token:string,query='',init:RequestInit={}):Promise<T>{const config=getSupabaseConfig();if(!config)throw new Error('Supabase no está configurado.');const response=await fetch(new URL(`/rest/v1/${catalog.table}${query}`,config.url),{...init,headers:{apikey:config.anonKey,Authorization:token,'Content-Type':'application/json',...(init.headers??{})}});const raw=response.status===204?'':await response.text();const payload:unknown=raw?JSON.parse(raw):null;if(!response.ok){const message=typeof payload==='object'&&payload!==null&&'message'in payload?String(payload.message):'No fue posible completar la operación.';throw new Error(message);}return payload as T;}
export const listConfigurationRows=(c:ConfigurationCatalog,t:string)=>request<Record<string,unknown>[]>(c,t,`?select=*&order=${c.primaryKey}.asc`);export async function createConfigurationRow(c:ConfigurationCatalog,t:string,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,'',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export async function updateConfigurationRow(c:ConfigurationCatalog,t:string,id:number,i:Record<string,unknown>){const r=await request<Record<string,unknown>[]>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(sanitize(c,i))});return r[0];}export const deleteConfigurationRow=(c:ConfigurationCatalog,t:string,id:number)=>request<null>(c,t,`?${c.primaryKey}=eq.${id}`,{method:'DELETE'});
